// The roadmap content. This file is only the SOURCE for the database:
// `pnpm seed` copies it into MongoDB, and the app reads it from there.
//
// Keep each `id` the same when you reword a step. Progress and notes are saved
// by id. Edit this file, then run `pnpm seed` again to update the database.
//
// This file must not import anything except types: the seed script runs it
// directly with Node.
import type { Link, ModuleDoc, Project, Search, StageDoc, Step } from "./roadmap-types";

const yt = (q: string): Search => ({ q, on: "yt" });
const web = (q: string): Search => ({ q, on: "web" });
const link = (label: string, url: string): Link => ({ label, url });

type StepIn = Omit<Step, "links"> & { links?: Link[] };
type ProjectIn = StepIn & { label: string; kind?: "mini" | "major" };
type ModuleIn = {
  id: string;
  stage: string;
  week: string;
  title: string;
  goal: string;
  nodeTip?: string;
  tasks: StepIn[];
  project: ProjectIn;
};

export const ROADMAP_VERSION = 1;

export const STAGES: StageDoc[] = [
  { _id: "s1", order: 1, title: "Python for a Node developer", blurb: "You already know how to program. Learn Python's idioms, modern tooling, types and async by mapping them to JS. About 4 weeks." },
  { _id: "s2", order: 2, title: "FastAPI core", blurb: "Everything you did in Express, rebuilt with validation, dependency injection, auth and auto-generated docs. About 5 weeks." },
  { _id: "s3", order: 3, title: "Databases and background work", blurb: "PostgreSQL with SQLAlchemy and Alembic, MongoDB if you want it, Redis, and job queues. About 4 weeks." },
  { _id: "s4", order: 4, title: "Testing and code quality", blurb: "The habits that separate junior from job-ready: tests, API design, linting, CI. About 3 weeks." },
  { _id: "s5", order: 5, title: "Production", blurb: "Docker, deployment, performance, observability and the real-world features every API needs. About 4 weeks." },
  { _id: "s6", order: 6, title: "Job-ready", blurb: "Architecture patterns, the Python ecosystem beyond web, interview prep and a portfolio. About 5 weeks." },
];

const MODULES_IN: ModuleIn[] = [
  // ───────────────────────── Stage 1 ─────────────────────────
  {
    id: "m01",
    stage: "s1",
    week: "Week 1",
    title: "Python language through JS eyes",
    goal: "Write idiomatic Python, not JavaScript with different punctuation. Skip beginner programming; learn only what differs.",
    nodeTip:
      "const/let → plain assignment, arrays → lists, objects → dicts, map/filter → comprehensions, null → None, === → ==, undefined doesn't exist. Indentation is syntax, and everything is an object.",
    tasks: [
      {
        id: "m01-core",
        title: "Syntax, built-in types and truthiness",
        learn: "int/float/str/bool/None, f-strings, list/tuple/dict/set, slicing, unpacking, truthiness rules, `is` vs `==`, mutable vs immutable, and the mutable default argument trap.",
        doneWhen: "You can explain why `def f(x=[])` is a bug and rewrite a Node utility using slicing and unpacking.",
        minutes: 180,
        keywords: ["list slicing", "tuple unpacking", "dict methods", "set", "f-string", "is vs ==", "mutable default argument", "truthiness"],
        search: [yt("Python for JavaScript developers"), yt("Python crash course for experienced programmers"), web("python mutable default argument gotcha")],
        links: [
          link("Python tutorial (official)", "https://docs.python.org/3/tutorial/"),
          link("Exercism: Python track (free, mentored practice)", "https://exercism.org/tracks/python"),
        ],
      },
      {
        id: "m01-fn",
        title: "Functions, comprehensions, closures and decorators",
        learn: "*args/**kwargs, keyword-only args, default values, list/dict/set comprehensions, lambda, first-class functions, closures, and decorators (a function that wraps a function, like Express middleware).",
        doneWhen: "You wrote a `@timed` decorator that logs how long any function takes and a comprehension that replaces a map+filter chain.",
        minutes: 150,
        keywords: ["comprehension", "*args **kwargs", "decorator", "functools.wraps", "closure", "lambda", "keyword-only arguments"],
        search: [yt("Python decorators explained Corey Schafer"), yt("Python list comprehension tutorial")],
        links: [link("Real Python: decorators (free article)", "https://realpython.com/primer-on-python-decorators/")],
      },
      {
        id: "m01-iter",
        title: "Iterators, generators and context managers",
        learn: "The iteration protocol, `yield`, generator expressions (lazy, like streams), `with` statements, `contextlib`, itertools basics.",
        doneWhen: "You streamed a 1 GB-style file line by line with a generator and wrote a context manager that opens and closes a resource.",
        minutes: 120,
        keywords: ["generator", "yield", "iterator protocol", "with statement", "contextlib", "itertools", "lazy evaluation"],
        search: [yt("Python generators yield explained"), yt("Python context managers with statement")],
        links: [link("Real Python: generators", "https://realpython.com/introduction-to-python-generators/")],
      },
      {
        id: "m01-oop",
        title: "Classes, dunder methods and the data model",
        learn: "Classes, `self`, `__init__`, `__repr__`, `__eq__`, properties, class vs static methods, inheritance and `super()`, dataclasses. Duck typing instead of interfaces.",
        doneWhen: "You built a small `Money` class with comparison, addition and a readable repr, as a dataclass and by hand.",
        minutes: 150,
        keywords: ["__init__", "__repr__", "dunder methods", "@property", "@dataclass", "inheritance", "super()", "duck typing", "@classmethod"],
        search: [yt("Python OOP classes tutorial"), yt("Python dataclasses tutorial")],
        links: [link("Python data model (reference)", "https://docs.python.org/3/reference/datamodel.html")],
      },
      {
        id: "m01-errors",
        title: "Exceptions, modules and packages",
        learn: "try/except/else/finally, raising and custom exceptions, EAFP vs LBYL, imports, `__init__.py`, `if __name__ == \"__main__\"`, and why circular imports bite.",
        doneWhen: "You split a script into a package with 3 modules and a custom exception hierarchy, and can say what `__name__` is for.",
        minutes: 90,
        keywords: ["try except", "custom exception", "raise from", "import system", "__init__.py", "__main__", "circular import", "EAFP"],
        search: [yt("Python exceptions try except finally"), yt("Python modules and packages imports explained")],
      },
    ],
    project: {
      id: "m01-proj",
      label: "Mini project · Port a Node utility",
      kind: "mini",
      title: "Rewrite a CLI or script you wrote in Node (a file processor, log parser or API client) in idiomatic Python: a package, a generator-based pipeline, a decorator and custom exceptions.",
      learn: "Proves you write Python, not translated JavaScript.",
      doneWhen: "The Python version matches the Node output and you can point to where you used a comprehension, a generator and a context manager.",
      minutes: 180,
      keywords: ["argparse", "pathlib", "json module", "logging"],
      search: [web("python argparse tutorial"), web("python pathlib tutorial")],
    },
  },
  {
    id: "m02",
    stage: "s1",
    week: "Week 2",
    title: "Modern Python tooling and project setup",
    goal: "Set up a Python project the way a professional team does: reproducible environments, linting, formatting, type checking and tests wired together.",
    nodeTip: "npm → uv (or pip), package.json → pyproject.toml, node_modules → .venv, package-lock.json → uv.lock, eslint+prettier → ruff, TypeScript → type hints + mypy/pyright, nodemon → `uvicorn --reload`.",
    tasks: [
      {
        id: "m02-uv",
        title: "Virtual environments, uv and pyproject.toml",
        learn: "Why Python needs virtual environments, `uv init/add/run/sync`, dependency groups (dev vs runtime), lockfiles, and pinning a Python version.",
        doneWhen: "A fresh clone of your project runs with `uv sync` and `uv run pytest` and nothing else.",
        minutes: 75,
        keywords: ["uv", "venv", "pyproject.toml", "uv.lock", "dependency groups", "pip", "pinned Python version"],
        search: [yt("uv python package manager tutorial"), yt("Python virtual environments explained")],
        links: [
          link("uv docs", "https://docs.astral.sh/uv/"),
          link("Python Packaging User Guide", "https://packaging.python.org/en/latest/tutorials/packaging-projects/"),
        ],
      },
      {
        id: "m02-lint",
        title: "Ruff, formatting and pre-commit",
        learn: "Ruff replaces flake8, isort and black in one fast tool. Configure it in pyproject.toml, read PEP 8 once, and run checks automatically with pre-commit.",
        doneWhen: "Committing a badly formatted file is blocked by a pre-commit hook that fixes it.",
        minutes: 60,
        keywords: ["ruff", "ruff format", "PEP 8", "pre-commit", "isort", "linting rules"],
        search: [yt("Ruff python linter formatter tutorial"), web("pre-commit hooks python ruff")],
        links: [
          link("Ruff docs", "https://docs.astral.sh/ruff/"),
          link("PEP 8", "https://peps.python.org/pep-0008/"),
          link("pre-commit", "https://pre-commit.com/"),
        ],
      },
      {
        id: "m02-types",
        title: "Type hints and mypy / pyright",
        learn: "Annotations for params and returns, Optional and `X | None`, list[int]/dict[str, int], Union, Callable, TypedDict, Protocol, generics at a basic level, and running mypy in strict-ish mode. FastAPI depends on this.",
        doneWhen: "mypy passes on a 200-line module you annotated, and you fixed at least 3 real bugs it found.",
        minutes: 150,
        keywords: ["type hints", "Optional", "X | None", "TypedDict", "Protocol", "Generic", "TypeVar", "mypy", "pyright"],
        search: [yt("Python type hints tutorial mypy"), yt("Python typing Protocol TypedDict explained")],
        links: [
          link("mypy cheat sheet", "https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html"),
          link("typing module docs", "https://docs.python.org/3/library/typing.html"),
        ],
      },
      {
        id: "m02-pytest",
        title: "pytest basics",
        learn: "Plain assert tests, naming, fixtures, parametrize, `pytest.raises`, running a subset. Jest's describe/it become simple functions.",
        doneWhen: "You have 10 passing tests for your module 1 project, using at least one fixture and one parametrized test.",
        minutes: 90,
        keywords: ["pytest", "fixture", "parametrize", "pytest.raises", "conftest.py", "assert rewriting"],
        search: [yt("pytest tutorial for beginners"), yt("pytest fixtures explained")],
        links: [link("pytest docs", "https://docs.pytest.org/en/stable/")],
      },
    ],
    project: {
      id: "m02-proj",
      label: "Mini project · Project template",
      kind: "mini",
      title: "Make a reusable project skeleton: uv, src layout, pyproject with ruff/mypy/pytest config, pre-commit, a README and a GitHub Actions workflow that runs lint, types and tests.",
      learn: "The starting point for every project from here on.",
      doneWhen: "Push to GitHub and the workflow goes green; mark the repo as a template.",
      minutes: 120,
      keywords: ["src layout", "GitHub Actions", "astral-sh/setup-uv", "template repository"],
      search: [web("python project template uv ruff mypy pytest github actions")],
    },
  },
  {
    id: "m03",
    stage: "s1",
    week: "Week 3",
    title: "Pydantic and data validation",
    goal: "Master the library FastAPI is built on: typed models that validate and serialize your data. This is Zod/Joi on steroids.",
    nodeTip: "A Pydantic model is a Zod schema and its TypeScript type in one class. Bad input raises a ValidationError with exactly which field failed and why.",
    tasks: [
      {
        id: "m03-models",
        title: "Pydantic v2 models and field types",
        learn: "BaseModel, required vs optional fields, defaults, Field constraints (min_length, ge, pattern), nested models, lists, enums, EmailStr, datetime, UUID.",
        doneWhen: "You modelled an Order with nested items and constraints, and invalid data gives a precise error list.",
        minutes: 120,
        keywords: ["BaseModel", "Field", "nested model", "Enum", "EmailStr", "ValidationError", "Optional field", "default_factory"],
        search: [yt("Pydantic v2 tutorial"), web("pydantic models fields validation")],
        links: [link("Pydantic docs", "https://docs.pydantic.dev/latest/")],
      },
      {
        id: "m03-validators",
        title: "Validators, computed fields and serialization",
        learn: "field_validator and model_validator, computed_field, model_dump / model_dump_json, aliases (camelCase for JSON), excluding fields, `model_config`.",
        doneWhen: "Your model accepts camelCase JSON, validates a cross-field rule (end date after start) and dumps clean output.",
        minutes: 90,
        keywords: ["field_validator", "model_validator", "model_dump", "alias", "ConfigDict", "computed_field", "from_attributes"],
        search: [yt("Pydantic validators model_validator tutorial")],
        links: [link("Pydantic: validators", "https://docs.pydantic.dev/latest/concepts/validators/")],
      },
      {
        id: "m03-settings",
        title: "Settings and environment config",
        learn: "pydantic-settings loads typed config from environment variables and .env files. The Pythonic dotenv + validation in one.",
        doneWhen: "App config is a typed Settings class and a missing DATABASE_URL fails at startup with a clear message.",
        minutes: 45,
        keywords: ["pydantic-settings", "BaseSettings", ".env", "environment variables", "SecretStr", "lru_cache"],
        search: [yt("pydantic settings environment variables tutorial")],
        links: [link("pydantic-settings", "https://docs.pydantic.dev/latest/concepts/pydantic_settings/")],
      },
    ],
    project: {
      id: "m03-proj",
      label: "Mini project · Validate messy data",
      kind: "mini",
      title: "Take a messy JSON file (a public API dump or export), define Pydantic models for it, load all records, and report which fail and why, with typed Settings for the file path and strictness.",
      learn: "The validation instinct you'll use at every API boundary.",
      doneWhen: "A summary prints valid and invalid counts with the top 3 error reasons.",
      minutes: 120,
      keywords: ["TypeAdapter", "ValidationError.errors()", "strict mode"],
      search: [web("pydantic validate list of models TypeAdapter")],
    },
  },
  {
    id: "m04",
    stage: "s1",
    week: "Week 4",
    title: "Async Python (asyncio) for a Node developer",
    goal: "Understand how Python's event loop differs from Node's, so you never accidentally block a FastAPI server.",
    nodeTip: "Same idea as Node: one thread, an event loop, async/await. The difference: Python won't await for you. A blocking call inside `async def` (requests, time.sleep, a sync DB driver) freezes the whole server, exactly like a sync loop in Node.",
    tasks: [
      {
        id: "m04-basics",
        title: "async/await, coroutines and tasks",
        learn: "`async def` returns a coroutine that does nothing until awaited, `asyncio.run`, `create_task`, `gather`, timeouts, cancellation, and `TaskGroup`.",
        doneWhen: "You ran 20 slow fake requests concurrently with gather and showed they finish in about the time of one.",
        minutes: 150,
        keywords: ["asyncio", "coroutine", "await", "asyncio.gather", "create_task", "TaskGroup", "asyncio.run", "timeout", "cancellation"],
        search: [yt("Python asyncio tutorial for JavaScript developers"), yt("Python asyncio gather create_task explained")],
        links: [link("asyncio: coroutines and tasks", "https://docs.python.org/3/library/asyncio-task.html")],
      },
      {
        id: "m04-blocking",
        title: "Blocking code, threads, processes and the GIL",
        learn: "Why a sync call blocks the loop, `asyncio.to_thread`, ThreadPool vs ProcessPool, I/O-bound vs CPU-bound work, and what the GIL actually limits.",
        doneWhen: "You proved a `time.sleep` inside async code stalls other tasks, then fixed it two ways.",
        minutes: 120,
        keywords: ["GIL", "asyncio.to_thread", "run_in_executor", "ThreadPoolExecutor", "ProcessPoolExecutor", "I/O-bound vs CPU-bound", "blocking call"],
        search: [yt("Python GIL explained"), yt("asyncio blocking code run_in_executor")],
        links: [link("Real Python: the GIL", "https://realpython.com/python-gil/")],
      },
      {
        id: "m04-httpx",
        title: "Async HTTP and I/O with httpx",
        learn: "httpx AsyncClient (the async `fetch`/axios), connection reuse, timeouts and retries, async context managers, async generators and `async for`.",
        doneWhen: "A script fetches 50 URLs concurrently with a concurrency cap (semaphore) and handles timeouts and failures.",
        minutes: 90,
        keywords: ["httpx", "AsyncClient", "asyncio.Semaphore", "async with", "async for", "timeouts", "retry with backoff"],
        search: [yt("httpx async python tutorial"), web("asyncio semaphore limit concurrency")],
        links: [link("httpx docs", "https://www.python-httpx.org/")],
      },
      {
        id: "m04-asgi",
        title: "WSGI vs ASGI, Uvicorn and Starlette",
        learn: "What a Python web server interface is, why ASGI exists (async, WebSockets), what Uvicorn does, and that FastAPI is Starlette plus Pydantic.",
        doneWhen: "You can explain what happens between a request arriving at Uvicorn and your function running.",
        minutes: 45,
        keywords: ["ASGI", "WSGI", "Uvicorn", "Starlette", "event loop", "gunicorn"],
        search: [yt("ASGI vs WSGI explained"), web("what is uvicorn starlette fastapi relationship")],
        links: [link("Starlette", "https://starlette.dev/")],
      },
    ],
    project: {
      id: "m04-proj",
      label: "Mini project · Concurrent API aggregator",
      kind: "mini",
      title: "A script that calls 3 public APIs concurrently (weather, GitHub, a news feed), merges the results into a Pydantic model, uses timeouts and retries, and compares sequential vs concurrent timing.",
      learn: "Async, validation and HTTP in one realistic task.",
      doneWhen: "Concurrent run is about 3× faster than sequential, and a failing API doesn't crash the rest.",
      minutes: 150,
      keywords: ["gather return_exceptions", "httpx", "pydantic", "timing"],
      search: [web("asyncio gather return_exceptions partial failure")],
    },
  },

  // ───────────────────────── Stage 2 ─────────────────────────
  {
    id: "m05",
    stage: "s2",
    week: "Week 5",
    title: "Your first FastAPI app",
    goal: "Build routes, read inputs and return typed responses, and see how much boilerplate Express made you write.",
    nodeTip: "app.get('/items/:id') → `@app.get('/items/{item_id}')` with `item_id: int` validated and documented for free. res.json() → just return a dict or model. Swagger UI appears at /docs without you writing it.",
    tasks: [
      {
        id: "m05-hello",
        title: "Install, run and read the auto docs",
        learn: "FastAPI + Uvicorn, `uvicorn main:app --reload`, `fastapi dev`, Swagger UI at /docs, ReDoc at /redoc, and the OpenAPI JSON at /openapi.json.",
        doneWhen: "You have a running app and used /docs to call your own endpoint.",
        minutes: 45,
        keywords: ["FastAPI", "uvicorn --reload", "fastapi dev", "Swagger UI", "OpenAPI", "ReDoc", "/docs"],
        search: [yt("FastAPI tutorial for beginners"), yt("FastAPI full course Express developer")],
        links: [
          link("FastAPI tutorial (official, excellent)", "https://fastapi.tiangolo.com/tutorial/"),
          link("FastAPI first steps", "https://fastapi.tiangolo.com/tutorial/first-steps/"),
        ],
      },
      {
        id: "m05-params",
        title: "Path, query and body parameters",
        learn: "Path params with types, query params with defaults and validation (`Query`), JSON bodies as Pydantic models, `Path`/`Query`/`Body`, headers and cookies.",
        doneWhen: "You built GET /items?skip&limit&q and POST /items with a validated body, and sent a bad request to see the 422 error.",
        minutes: 120,
        keywords: ["path parameter", "query parameter", "request body", "Query()", "Path()", "Header()", "Cookie()", "422 Unprocessable Entity"],
        search: [yt("FastAPI path query body parameters"), web("FastAPI query parameters validation")],
        links: [link("FastAPI: query params", "https://fastapi.tiangolo.com/tutorial/query-params/")],
      },
      {
        id: "m05-response",
        title: "Response models and status codes",
        learn: "`response_model` to filter output (never leak a password hash), `status_code`, `Response`, `JSONResponse`, `HTTPException`, tags and summaries for docs.",
        doneWhen: "POST /users takes a password and returns the user without it, with a 201, enforced by response_model.",
        minutes: 90,
        keywords: ["response_model", "status_code", "HTTPException", "JSONResponse", "response_model_exclude", "tags", "201 Created"],
        search: [yt("FastAPI response_model status code HTTPException")],
        links: [link("FastAPI: response model", "https://fastapi.tiangolo.com/tutorial/response-model/")],
      },
      {
        id: "m05-async",
        title: "`def` vs `async def` endpoints",
        learn: "FastAPI runs plain `def` endpoints in a threadpool and `async def` on the event loop. Pick `async def` only when everything inside is awaitable.",
        doneWhen: "You can say which to use with a sync DB driver and which with httpx, and why a wrong choice slows the whole app.",
        minutes: 45,
        keywords: ["async def vs def", "threadpool", "blocking in async", "concurrency", "anyio"],
        search: [yt("FastAPI async def vs def when to use")],
        links: [link("FastAPI: Concurrency and async/await", "https://fastapi.tiangolo.com/async/")],
      },
    ],
    project: {
      id: "m05-proj",
      label: "Mini project · In-memory CRUD API",
      kind: "mini",
      title: "Port a small Express CRUD API you've built (todos, notes or books) to FastAPI with in-memory storage: Pydantic models, response models, proper status codes and 404s.",
      learn: "The mapping from Express to FastAPI, one endpoint at a time.",
      doneWhen: "All CRUD calls work from /docs and an invalid request returns a helpful 422.",
      minutes: 180,
      keywords: ["CRUD", "uuid", "404 Not Found", "PATCH partial update"],
      search: [web("FastAPI CRUD example in memory")],
    },
  },
  {
    id: "m06",
    stage: "s2",
    week: "Week 6",
    title: "Structure, errors and API conventions",
    goal: "Organise a real app into routers and layers, return consistent errors, and add pagination and filtering.",
    nodeTip: "express.Router() → APIRouter. app.use(errorHandler) → @app.exception_handler. A folder per feature, not one giant main.py.",
    tasks: [
      {
        id: "m06-routers",
        title: "APIRouter and project layout",
        learn: "Split into routers with prefixes and tags, a sensible folder layout (routers, schemas, services, models, core), and `include_router`.",
        doneWhen: "Your app has users and items routers in separate files and main.py is under 30 lines.",
        minutes: 75,
        keywords: ["APIRouter", "include_router", "prefix", "project structure", "bigger applications", "schemas vs models"],
        search: [yt("FastAPI project structure best practices"), web("FastAPI bigger applications APIRouter")],
        links: [
          link("FastAPI: bigger applications", "https://fastapi.tiangolo.com/tutorial/bigger-applications/"),
          link("Official full-stack FastAPI template (study the layout)", "https://github.com/fastapi/full-stack-fastapi-template"),
        ],
      },
      {
        id: "m06-errors",
        title: "Consistent error handling",
        learn: "Custom exception classes, `exception_handler` for them and for validation errors, a single error JSON shape, and problem details (RFC 9457).",
        doneWhen: "Every error from your API (404, 422, 500, domain errors) has the same JSON shape with a code and message.",
        minutes: 90,
        keywords: ["exception_handler", "RequestValidationError", "custom exception", "error response schema", "RFC 9457", "problem details"],
        search: [yt("FastAPI custom exception handlers"), web("FastAPI handling errors")],
        links: [link("FastAPI: handling errors", "https://fastapi.tiangolo.com/tutorial/handling-errors/")],
      },
      {
        id: "m06-paging",
        title: "Pagination, filtering and sorting",
        learn: "Limit/offset vs cursor pagination, filter models via query params, sorting whitelists, returning `total` and `next`, and why `skip` doesn't scale.",
        doneWhen: "GET /items supports page size, a filter, a sort field (whitelisted) and returns a paginated envelope.",
        minutes: 90,
        keywords: ["pagination", "limit offset", "cursor pagination", "filtering", "sorting", "query parameter models", "envelope response"],
        search: [yt("cursor vs offset pagination explained"), web("FastAPI pagination filtering")],
      },
      {
        id: "m06-rest",
        title: "REST design that survives contact with users",
        learn: "Resource naming, idempotency (PUT/DELETE vs POST), PATCH semantics, API versioning (/v1), HATEOAS skepticism, and idempotency keys.",
        doneWhen: "You reviewed your own API against a checklist and changed 3 things.",
        minutes: 60,
        keywords: ["REST", "idempotency", "API versioning", "idempotency key", "resource naming", "PUT vs PATCH"],
        search: [yt("REST API design best practices"), web("API versioning strategies")],
        links: [link("Microsoft: web API design guide", "https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design")],
      },
    ],
    project: {
      id: "m06-proj",
      label: "Mini project · Structured API",
      kind: "mini",
      title: "Grow the CRUD API into a layered app with 3 resources (users, projects, tasks), routers, a service layer, uniform errors, pagination and /v1 prefix.",
      learn: "The shape every FastAPI codebase at work will have.",
      doneWhen: "Adding a fourth resource means adding files, not editing existing ones.",
      minutes: 210,
      keywords: ["service layer", "router", "v1", "error envelope"],
      search: [web("FastAPI service layer repository pattern project")],
    },
  },
  {
    id: "m07",
    stage: "s2",
    week: "Week 7",
    title: "Dependency injection, middleware and app lifecycle",
    goal: "Use the feature that makes FastAPI different from Express: `Depends`.",
    nodeTip: "Express middleware chains mutate `req`. FastAPI dependencies are plain functions your endpoint declares it needs; they can have their own dependencies and run per request. It makes testing and auth trivial.",
    tasks: [
      {
        id: "m07-depends",
        title: "Depends: the dependency system",
        learn: "Function dependencies, sub-dependencies, class dependencies, `yield` dependencies for setup/teardown (a DB session), router-level and app-level dependencies.",
        doneWhen: "A `get_db` yield-dependency gives each request a session and closes it, and a router-level dependency guards all its routes.",
        minutes: 120,
        keywords: ["Depends", "dependency injection", "yield dependency", "sub-dependency", "Annotated", "router dependencies", "dependency caching"],
        search: [yt("FastAPI dependency injection Depends explained"), web("FastAPI dependencies with yield")],
        links: [link("FastAPI: dependencies", "https://fastapi.tiangolo.com/tutorial/dependencies/")],
      },
      {
        id: "m07-middleware",
        title: "Middleware and CORS",
        learn: "Writing request/response middleware (timing, request IDs), the built-in CORSMiddleware, GZip, TrustedHost, and when to use a dependency instead.",
        doneWhen: "Every response has an `X-Request-ID` and `X-Process-Time` header and your frontend origin is the only allowed CORS origin.",
        minutes: 75,
        keywords: ["middleware", "CORSMiddleware", "BaseHTTPMiddleware", "request id", "GZipMiddleware", "TrustedHostMiddleware", "CORS preflight"],
        search: [yt("FastAPI middleware CORS tutorial")],
        links: [
          link("FastAPI: middleware", "https://fastapi.tiangolo.com/tutorial/middleware/"),
          link("FastAPI: CORS", "https://fastapi.tiangolo.com/tutorial/cors/"),
        ],
      },
      {
        id: "m07-lifespan",
        title: "Lifespan, settings and background tasks",
        learn: "The `lifespan` context manager to create and close pools at startup/shutdown, settings as a cached dependency, and `BackgroundTasks` for small after-response work (and its limits).",
        doneWhen: "A DB pool and an httpx client are created once at startup, closed at shutdown, and a welcome email 'sends' after the response.",
        minutes: 90,
        keywords: ["lifespan", "startup shutdown", "app.state", "BackgroundTasks", "settings dependency", "connection pool"],
        search: [yt("FastAPI lifespan events startup shutdown"), web("FastAPI BackgroundTasks vs Celery")],
        links: [
          link("FastAPI: lifespan events", "https://fastapi.tiangolo.com/advanced/events/"),
          link("FastAPI: background tasks", "https://fastapi.tiangolo.com/tutorial/background-tasks/"),
        ],
      },
      {
        id: "m07-logging",
        title: "Logging that you can use in production",
        learn: "The `logging` module (loggers, levels, handlers), JSON logs, request-scoped context, and never logging secrets.",
        doneWhen: "Each request logs one structured line with method, path, status, duration and request ID.",
        minutes: 60,
        keywords: ["logging module", "log levels", "structured logging", "JSON logs", "contextvars", "structlog"],
        search: [yt("Python logging tutorial best practices"), web("structlog FastAPI request id")],
        links: [link("Python logging HOWTO", "https://docs.python.org/3/howto/logging.html")],
      },
    ],
    project: {
      id: "m07-proj",
      label: "Mini project · Production plumbing",
      kind: "mini",
      title: "Add to your structured API: typed Settings as a dependency, a lifespan-managed httpx client, request-ID + timing middleware, structured logging and CORS.",
      learn: "The cross-cutting concerns every real service has.",
      doneWhen: "You can trace one request through the logs by its request ID.",
      minutes: 150,
      keywords: ["lifespan", "middleware", "request id", "settings"],
      search: [web("FastAPI request id middleware logging contextvars")],
    },
  },
  {
    id: "m08",
    stage: "s2",
    week: "Weeks 8–9",
    title: "Authentication, authorization and API security",
    goal: "Ship auth you'd trust in production: hashed passwords, JWT access and refresh tokens, roles and the common protections.",
    nodeTip: "Same concepts as passport/jsonwebtoken. FastAPI's `OAuth2PasswordBearer` plugs the login into Swagger's Authorize button, so you can test auth from /docs.",
    tasks: [
      {
        id: "m08-passwords",
        title: "Password hashing and user registration",
        learn: "Never store passwords; use Argon2id or bcrypt through a maintained library, salting, timing-safe comparison, and sensible password rules.",
        doneWhen: "Registration stores only a hash and login verifies it; you can say why SHA-256 is wrong for passwords.",
        minutes: 75,
        keywords: ["Argon2", "bcrypt", "pwdlib", "password hashing", "salt", "timing attack", "passlib deprecated"],
        search: [yt("password hashing argon2 bcrypt explained"), web("FastAPI password hashing pwdlib argon2")],
        links: [link("OWASP: password storage cheat sheet", "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html")],
      },
      {
        id: "m08-jwt",
        title: "OAuth2 password flow and JWT access tokens",
        learn: "`OAuth2PasswordBearer`, `OAuth2PasswordRequestForm`, signing and verifying JWTs (PyJWT), expiry, a `get_current_user` dependency, and 401 vs 403.",
        doneWhen: "You log in from /docs, click Authorize, and a protected endpoint returns the current user.",
        minutes: 120,
        keywords: ["OAuth2PasswordBearer", "JWT", "PyJWT", "get_current_user", "bearer token", "401 vs 403", "token expiry"],
        search: [yt("FastAPI JWT authentication tutorial OAuth2"), web("FastAPI OAuth2 password JWT")],
        links: [link("FastAPI: security", "https://fastapi.tiangolo.com/tutorial/security/")],
      },
      {
        id: "m08-refresh",
        title: "Refresh tokens, logout and sessions",
        learn: "Short-lived access tokens plus rotating refresh tokens, httpOnly cookies vs Authorization header, revocation lists, and logout that actually logs out.",
        doneWhen: "An expired access token is renewed with a refresh token, and a used refresh token can't be reused.",
        minutes: 120,
        keywords: ["refresh token", "token rotation", "httpOnly cookie", "revocation", "logout", "session", "CSRF"],
        search: [yt("refresh token rotation explained"), web("JWT refresh token best practices httpOnly cookie")],
      },
      {
        id: "m08-rbac",
        title: "Roles, permissions and ownership checks",
        learn: "Role-based dependencies (`require_role('admin')`), resource ownership (user can edit only their own), and avoiding IDOR, the most common API bug.",
        doneWhen: "User A gets a 404 (not data) when requesting user B's resource, and admin-only routes reject normal users.",
        minutes: 75,
        keywords: ["RBAC", "authorization", "IDOR", "ownership check", "scopes", "permissions dependency"],
        search: [yt("FastAPI role based access control"), web("OWASP BOLA broken object level authorization")],
        links: [link("OWASP API Security Top 10", "https://owasp.org/API-Security/")],
      },
      {
        id: "m08-hardening",
        title: "Rate limiting, input safety and security headers",
        learn: "Rate limiting (slowapi or Redis), request size limits, SQL-injection safety via parameters, SSRF and mass-assignment awareness, HTTPS and security headers.",
        doneWhen: "Login is limited to 5 tries a minute per IP and you can name 3 OWASP API risks your API now covers.",
        minutes: 90,
        keywords: ["rate limiting", "slowapi", "SQL injection", "mass assignment", "SSRF", "security headers", "OWASP API Top 10"],
        search: [yt("OWASP API security top 10 explained"), web("FastAPI rate limiting slowapi")],
      },
    ],
    project: {
      id: "m08-proj",
      label: "Major project · Auth service",
      kind: "major",
      title: "Add full auth to your structured API: register, login, refresh with rotation, logout, role-based admin routes, ownership checks and login rate limiting. Keep it in-memory for now.",
      learn: "The part of backend interviews where juniors are weakest.",
      doneWhen: "From /docs you can register, log in, refresh, hit an admin route as user and admin, and get blocked after 5 bad logins.",
      minutes: 360,
      keywords: ["JWT", "refresh rotation", "RBAC", "rate limit"],
      search: [web("FastAPI JWT refresh token rotation example")],
    },
  },

  // ───────────────────────── Stage 3 ─────────────────────────
  {
    id: "m09",
    stage: "s3",
    week: "Week 10",
    title: "SQL and PostgreSQL fundamentals",
    goal: "Be solid with relational databases, since most Python backend jobs run on PostgreSQL.",
    nodeTip: "If your Express apps were mostly MongoDB, this is the biggest mindset shift: schemas, joins and transactions instead of embedded documents. Learn SQL itself before the ORM.",
    tasks: [
      {
        id: "m09-sql",
        title: "SQL queries: select, joins and aggregates",
        learn: "SELECT/WHERE/ORDER BY, INNER and LEFT JOINs, GROUP BY and HAVING, subqueries, CTEs, window functions at a taste level.",
        doneWhen: "You solved the PG Exercises joins and aggregates sections without peeking.",
        minutes: 240,
        keywords: ["SELECT", "JOIN", "LEFT JOIN", "GROUP BY", "HAVING", "CTE", "window function", "subquery"],
        search: [yt("SQL tutorial full course"), web("SQLBolt interactive lessons")],
        links: [
          link("SQLBolt (interactive)", "https://sqlbolt.com/"),
          link("PG Exercises (practice)", "https://pgexercises.com/"),
        ],
      },
      {
        id: "m09-design",
        title: "Schema design, keys and constraints",
        learn: "Tables and types, primary and foreign keys, NOT NULL/UNIQUE/CHECK, one-to-many and many-to-many with join tables, normalisation to 3NF, UUID vs serial IDs.",
        doneWhen: "You designed and created a schema for a blog or shop with 5 tables, FKs and constraints, in plain SQL.",
        minutes: 120,
        keywords: ["primary key", "foreign key", "constraints", "normalization", "many-to-many", "join table", "UUID vs bigint", "ON DELETE CASCADE"],
        search: [yt("database normalization explained"), yt("PostgreSQL schema design tutorial")],
        links: [link("PostgreSQL tutorial (official)", "https://www.postgresql.org/docs/current/tutorial.html")],
      },
      {
        id: "m09-index",
        title: "Indexes, EXPLAIN and transactions",
        learn: "How B-tree indexes speed reads and slow writes, `EXPLAIN ANALYZE`, composite indexes, ACID, isolation levels at a basic level, and deadlocks.",
        doneWhen: "A slow query dropped from a sequential scan to an index scan and you showed it with EXPLAIN ANALYZE.",
        minutes: 150,
        keywords: ["index", "B-tree", "EXPLAIN ANALYZE", "composite index", "transaction", "ACID", "isolation level", "deadlock"],
        search: [yt("PostgreSQL indexes explained EXPLAIN ANALYZE"), yt("database transactions ACID isolation levels")],
        links: [link("Use The Index, Luke (free book)", "https://use-the-index-luke.com/")],
      },
      {
        id: "m09-docker",
        title: "Run Postgres locally with Docker",
        learn: "A Postgres container with a volume, psql, a GUI client (DBeaver or pgAdmin), and a docker compose file you'll reuse for every project.",
        doneWhen: "`docker compose up -d db` gives you a Postgres you can connect to with psql and a GUI.",
        minutes: 45,
        keywords: ["docker compose", "postgres image", "psql", "volume", "DBeaver", "pgAdmin"],
        search: [yt("PostgreSQL docker compose tutorial")],
        links: [link("Docker: get started", "https://docs.docker.com/get-started/")],
      },
    ],
    project: {
      id: "m09-proj",
      label: "Mini project · Schema and queries",
      kind: "mini",
      title: "Design a schema for your API's domain (users, projects, tasks, comments), seed it with 10k rows by script, write 8 queries (joins, aggregates, a CTE), and index the slowest.",
      learn: "SQL fluency before the ORM hides it.",
      doneWhen: "You can show a before/after EXPLAIN ANALYZE for one query.",
      minutes: 210,
      keywords: ["seed script", "generate_series", "index", "EXPLAIN"],
      search: [web("postgres generate_series seed data")],
    },
  },
  {
    id: "m10",
    stage: "s3",
    week: "Weeks 11–12",
    title: "SQLAlchemy 2.0 and Alembic with FastAPI",
    goal: "Connect your API to Postgres the way real FastAPI companies do, with async sessions and versioned migrations.",
    nodeTip: "SQLAlchemy is Prisma/Sequelize/TypeORM's older, more powerful cousin. Alembic is `prisma migrate`. Learn the Session lifecycle; it's the thing that confuses everyone coming from Mongoose.",
    tasks: [
      {
        id: "m10-orm",
        title: "SQLAlchemy 2.0 models and queries",
        learn: "`DeclarativeBase`, `Mapped[...]` / `mapped_column`, `select()` queries, `session.execute/scalars`, insert/update/delete, and the unit-of-work idea of a Session.",
        doneWhen: "You mapped your schema to models and performed CRUD with `select()` in a script.",
        minutes: 180,
        keywords: ["SQLAlchemy 2.0", "DeclarativeBase", "Mapped", "mapped_column", "select()", "Session", "scalars", "unit of work"],
        search: [yt("SQLAlchemy 2.0 tutorial"), web("SQLAlchemy 2.0 unified tutorial")],
        links: [link("SQLAlchemy 2.0 tutorial (official)", "https://docs.sqlalchemy.org/en/20/tutorial/")],
      },
      {
        id: "m10-rel",
        title: "Relationships, loading strategies and the N+1 problem",
        learn: "`relationship()`, back_populates, one-to-many and many-to-many, lazy vs `selectinload` / `joinedload`, why lazy loading breaks in async, and finding N+1 queries.",
        doneWhen: "Listing 50 projects with their tasks runs 2 queries, not 51, and you can show the SQL log.",
        minutes: 150,
        keywords: ["relationship", "back_populates", "selectinload", "joinedload", "N+1 query", "lazy loading", "echo=True", "MissingGreenlet"],
        search: [yt("SQLAlchemy relationships eager loading N+1"), web("SQLAlchemy selectinload vs joinedload")],
      },
      {
        id: "m10-async",
        title: "Async engine and sessions in FastAPI",
        learn: "`create_async_engine` with asyncpg, `async_sessionmaker`, a `get_session` yield dependency, commit/rollback per request, `expire_on_commit=False`, connection pool settings.",
        doneWhen: "Endpoints use an injected AsyncSession and a failed request rolls back its changes.",
        minutes: 120,
        keywords: ["AsyncSession", "create_async_engine", "asyncpg", "async_sessionmaker", "expire_on_commit", "pool_size", "session per request"],
        search: [yt("FastAPI SQLAlchemy async session tutorial"), web("FastAPI SQLAlchemy 2.0 async dependency")],
        links: [link("FastAPI: SQL databases", "https://fastapi.tiangolo.com/tutorial/sql-databases/")],
      },
      {
        id: "m10-alembic",
        title: "Alembic migrations",
        learn: "`alembic init`, autogenerate revisions, reviewing the generated diff, upgrade/downgrade, data migrations, async env.py, and zero-downtime habits (add nullable first).",
        doneWhen: "You added a column via a migration, rolled it back and forward, and never used `create_all` in the app.",
        minutes: 120,
        keywords: ["Alembic", "autogenerate", "alembic upgrade head", "downgrade", "migration", "env.py", "data migration"],
        search: [yt("Alembic migrations tutorial SQLAlchemy"), web("Alembic async FastAPI setup")],
        links: [link("Alembic tutorial", "https://alembic.sqlalchemy.org/en/latest/tutorial.html")],
      },
      {
        id: "m10-patterns",
        title: "Repository pattern, transactions and common pitfalls",
        learn: "A thin repository or service layer around queries, multi-step transactions with rollback, `SELECT ... FOR UPDATE`, unique violations to 409, soft deletes, timestamps.",
        doneWhen: "Transferring a balance between two rows is atomic and a duplicate email returns 409, not a 500.",
        minutes: 120,
        keywords: ["repository pattern", "transaction", "IntegrityError", "409 Conflict", "soft delete", "with_for_update", "created_at updated_at"],
        search: [yt("repository pattern SQLAlchemy FastAPI"), web("SQLAlchemy IntegrityError handle unique violation")],
      },
    ],
    project: {
      id: "m10-proj",
      label: "Major project · Real persistence",
      kind: "major",
      title: "Move your structured, authenticated API to PostgreSQL: async SQLAlchemy models with relationships, Alembic migrations, a repository layer, eager loading, pagination in SQL and unique-constraint errors as 409s.",
      learn: "The core of a job-ready FastAPI backend.",
      doneWhen: "`alembic upgrade head` on an empty database plus `uvicorn` gives a working, persistent API; no N+1 in the SQL log.",
      minutes: 480,
      keywords: ["Postgres", "async SQLAlchemy", "Alembic", "pagination SQL"],
      search: [web("FastAPI async SQLAlchemy Postgres Alembic example project")],
    },
  },
  {
    id: "m11",
    stage: "s3",
    week: "Week 13",
    title: "Redis, caching, queues and MongoDB",
    goal: "Cover the rest of the data layer a backend job expects: caching, background jobs, and your Mongo experience in Python.",
    nodeTip: "Bull/BullMQ → Celery or ARQ. ioredis → redis-py (async). Mongoose → Beanie (or PyMongo's async API). You already know the concepts; learn the Python spellings.",
    tasks: [
      {
        id: "m11-redis",
        title: "Redis fundamentals and caching patterns",
        learn: "Strings, hashes, lists, sets, TTLs, cache-aside, cache invalidation, rate-limit counters, and `redis.asyncio` in FastAPI.",
        doneWhen: "A slow endpoint is cached with a TTL and you can say how you'd invalidate it on update.",
        minutes: 120,
        keywords: ["Redis", "cache-aside", "TTL", "redis.asyncio", "cache invalidation", "INCR", "pub/sub"],
        search: [yt("Redis tutorial for beginners"), yt("FastAPI Redis caching tutorial")],
        links: [
          link("Redis docs", "https://redis.io/docs/latest/"),
          link("redis-py docs", "https://redis.readthedocs.io/en/stable/"),
        ],
      },
      {
        id: "m11-jobs",
        title: "Background jobs with Celery or ARQ",
        learn: "Why you can't do heavy work in the request, brokers and workers, retries with backoff, scheduled tasks, idempotent jobs, and monitoring with Flower.",
        doneWhen: "An endpoint enqueues an email-sending job, a worker processes it, and a failing job retries with backoff.",
        minutes: 150,
        keywords: ["Celery", "ARQ", "task queue", "worker", "broker", "retry", "Celery beat", "idempotent task", "Flower"],
        search: [yt("Celery FastAPI tutorial background tasks Redis"), web("ARQ async job queue python")],
        links: [
          link("Celery: first steps", "https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html"),
          link("ARQ (async, simpler)", "https://arq-docs.helpmanual.io/"),
        ],
      },
      {
        id: "m11-mongo",
        title: "MongoDB from Python (Motor/PyMongo async, Beanie)",
        learn: "PyMongo's async client, documents as Pydantic with Beanie, queries and indexes, and when Mongo or Postgres is the better pick.",
        doneWhen: "One resource of your API runs on Mongo and you can explain when you'd choose it over Postgres.",
        minutes: 90,
        keywords: ["PyMongo async", "Motor", "Beanie ODM", "Pydantic documents", "Mongo vs Postgres", "ObjectId"],
        search: [yt("FastAPI MongoDB Beanie tutorial"), web("PyMongo async tutorial")],
        links: [
          link("PyMongo async API", "https://pymongo.readthedocs.io/en/stable/api/pymongo/asynchronous/index.html"),
          link("Beanie ODM", "https://beanie-odm.dev/"),
        ],
      },
    ],
    project: {
      id: "m11-proj",
      label: "Mini project · Async work and caching",
      kind: "mini",
      title: "Add to your Postgres API: Redis caching on a hot read endpoint, a Celery or ARQ worker that sends a welcome email and generates a report asynchronously, and a job-status endpoint.",
      learn: "The three patterns that fill most backend system designs: cache, queue, worker.",
      doneWhen: "Docker compose runs api, worker, Postgres and Redis together, and a failed job retries.",
      minutes: 240,
      keywords: ["docker compose", "worker", "job status", "cache"],
      search: [web("FastAPI Celery Redis docker compose example")],
    },
  },

  // ───────────────────────── Stage 4 ─────────────────────────
  {
    id: "m12",
    stage: "s4",
    week: "Weeks 14–15",
    title: "Testing FastAPI apps",
    goal: "Write tests that let you change code without fear. This is a top differentiator in job interviews and take-home tasks.",
    nodeTip: "Jest + supertest → pytest + httpx. `jest.mock` → `unittest.mock` / monkeypatch, and FastAPI's `dependency_overrides` replaces mocking for most things.",
    tasks: [
      {
        id: "m12-client",
        title: "Testing endpoints with TestClient and AsyncClient",
        learn: "`TestClient` for sync tests, `httpx.AsyncClient` with `ASGITransport` for async, arrange/act/assert, status codes and JSON bodies.",
        doneWhen: "Every endpoint of your API has a happy-path and a failure-path test.",
        minutes: 120,
        keywords: ["TestClient", "httpx AsyncClient", "ASGITransport", "pytest-asyncio", "anyio", "arrange act assert"],
        search: [yt("FastAPI testing pytest tutorial"), web("FastAPI async tests httpx pytest-asyncio")],
        links: [link("FastAPI: testing", "https://fastapi.tiangolo.com/tutorial/testing/")],
      },
      {
        id: "m12-fixtures",
        title: "Fixtures, test database and dependency overrides",
        learn: "Fixture scopes, a separate test database, rolling back each test in a transaction, `app.dependency_overrides` to swap auth or the DB, and factories for test data.",
        doneWhen: "Tests run against a real Postgres, each test is isolated and leaves no data behind, and auth is overridden in one line.",
        minutes: 150,
        keywords: ["fixture scope", "dependency_overrides", "test database", "transaction rollback", "factory", "conftest.py", "pytest-asyncio loop scope"],
        search: [yt("pytest fixtures database rollback FastAPI"), web("FastAPI dependency_overrides testing")],
        links: [link("FastAPI: testing dependencies", "https://fastapi.tiangolo.com/advanced/testing-dependencies/")],
      },
      {
        id: "m12-mock",
        title: "Mocking, patching and testcontainers",
        learn: "`unittest.mock`, `monkeypatch`, patching where it's used (not defined), faking HTTP with respx, and real throwaway Postgres/Redis with testcontainers.",
        doneWhen: "Your email-sending and external-API code is tested with fakes, and DB tests can run with testcontainers.",
        minutes: 120,
        keywords: ["unittest.mock", "monkeypatch", "patch where used", "respx", "testcontainers", "fake vs mock", "freezegun"],
        search: [yt("Python mocking unittest.mock patch tutorial"), web("testcontainers python postgres pytest")],
        links: [link("testcontainers-python", "https://testcontainers-python.readthedocs.io/")],
      },
      {
        id: "m12-cov",
        title: "Coverage and property-based tests",
        learn: "`pytest-cov`, what coverage does and doesn't tell you, testing edge cases, and a taste of Hypothesis for generating inputs.",
        doneWhen: "Coverage is above 85% on services and auth, and one Hypothesis test found an input you hadn't thought of.",
        minutes: 75,
        keywords: ["pytest-cov", "coverage", "Hypothesis", "property-based testing", "edge cases", "test pyramid"],
        search: [yt("pytest-cov coverage report tutorial"), yt("Hypothesis property based testing python")],
        links: [link("Hypothesis docs", "https://hypothesis.readthedocs.io/en/latest/")],
      },
    ],
    project: {
      id: "m12-proj",
      label: "Major project · Test suite",
      kind: "major",
      title: "Write a full test suite for your Postgres API: auth flows, ownership checks, validation errors, pagination, a mocked external call, the background job, with a transactional test DB and coverage in CI.",
      learn: "What 'we have tests' means at a real company.",
      doneWhen: "Break an endpoint on purpose and the suite catches it; CI fails below your coverage threshold.",
      minutes: 420,
      keywords: ["pytest", "coverage gate", "CI", "factories"],
      search: [web("FastAPI pytest full test suite async SQLAlchemy example")],
    },
  },
  {
    id: "m13",
    stage: "s4",
    week: "Week 16",
    title: "Code quality, contracts and CI",
    goal: "Keep a codebase healthy as it grows: strict types, automatic checks and a pipeline that guards main.",
    tasks: [
      {
        id: "m13-strict",
        title: "Strict typing and linting in practice",
        learn: "mypy/pyright strict mode on a real app, typing SQLAlchemy and Pydantic well, ruff rule sets (B, UP, S for security, SIM), and fixing instead of `# type: ignore`.",
        doneWhen: "mypy --strict (or pyright) is clean on your API with fewer than 3 documented ignores.",
        minutes: 120,
        keywords: ["mypy --strict", "pyright", "ruff rules", "bandit rules S", "type: ignore", "py.typed", "Annotated"],
        search: [yt("mypy strict mode real project"), web("ruff rules flake8-bugbear flake8-bandit")],
      },
      {
        id: "m13-openapi",
        title: "OpenAPI as a contract",
        learn: "Writing good docs from code (summaries, examples, response models for errors), exporting openapi.json, generating a typed client for your frontend, and detecting breaking changes.",
        doneWhen: "You generated a TypeScript client from your OpenAPI schema and used it in a small Node or React script.",
        minutes: 75,
        keywords: ["OpenAPI", "openapi.json", "response examples", "openapi-typescript", "client generation", "breaking changes", "schema_extra"],
        search: [yt("FastAPI OpenAPI generate typescript client"), web("openapi-typescript generate types")],
        links: [link("FastAPI: generate clients", "https://fastapi.tiangolo.com/advanced/generate-clients/")],
      },
      {
        id: "m13-ci",
        title: "A CI pipeline for Python",
        learn: "GitHub Actions with uv: lint, format check, type check, tests with a Postgres service container, coverage, and caching. Required checks on main.",
        doneWhen: "A PR with a failing test or type error can't be merged.",
        minutes: 90,
        keywords: ["GitHub Actions", "setup-uv", "service containers", "matrix Python versions", "required status checks", "cache"],
        search: [yt("GitHub Actions python uv pytest postgres service"), web("GitHub Actions service containers postgres")],
        links: [link("GitHub Actions docs", "https://docs.github.com/en/actions")],
      },
      {
        id: "m13-style",
        title: "Readable code habits",
        learn: "Naming, small functions, docstrings, Google or NumPy docstring style, avoiding clever code, reading other people's code, and common Python anti-patterns.",
        doneWhen: "You refactored one 100-line function into small named pieces and wrote docstrings for your public functions.",
        minutes: 60,
        keywords: ["docstring", "naming conventions", "PEP 20 Zen of Python", "refactoring", "anti-patterns", "Google Python style guide"],
        search: [yt("clean code python refactoring"), web("Google Python style guide docstrings")],
        links: [link("Google Python Style Guide", "https://google.github.io/styleguide/pyguide.html")],
      },
    ],
    project: {
      id: "m13-proj",
      label: "Mini project · Quality gates",
      kind: "mini",
      title: "Put quality gates on your API repo: strict mypy, ruff with security rules, pre-commit, a CI workflow with Postgres, coverage threshold, a README with badges and a generated TypeScript client.",
      learn: "A repo that looks professional at first glance.",
      doneWhen: "CI is green on main and a deliberately bad PR is blocked.",
      minutes: 180,
      keywords: ["CI", "badges", "branch protection", "client generation"],
      search: [web("python repo github actions badges coverage codecov")],
    },
  },

  // ───────────────────────── Stage 5 ─────────────────────────
  {
    id: "m14",
    stage: "s5",
    week: "Weeks 17–18",
    title: "Docker and deploying FastAPI",
    goal: "Ship your API to the internet in a container, with migrations, config and zero-downtime basics.",
    nodeTip: "PM2/cluster → Gunicorn managing several Uvicorn workers (or `fastapi run --workers`). `node:20-alpine` → `python:3.12-slim`. `npm ci` → `uv sync --frozen`.",
    tasks: [
      {
        id: "m14-docker",
        title: "A production Dockerfile for FastAPI",
        learn: "Slim base images, uv in Docker, multi-stage builds, layer caching for dependencies, non-root user, `.dockerignore`, healthchecks.",
        doneWhen: "Your image is under ~250 MB, runs as non-root, and rebuilds fast when only code changes.",
        minutes: 120,
        keywords: ["Dockerfile", "python slim", "uv docker", "multi-stage build", "non-root user", "HEALTHCHECK", ".dockerignore", "layer caching"],
        search: [yt("FastAPI Docker tutorial production"), web("uv docker best practices multi-stage")],
        links: [
          link("uv: Docker guide", "https://docs.astral.sh/uv/guides/integration/docker/"),
          link("FastAPI in containers", "https://fastapi.tiangolo.com/deployment/docker/"),
        ],
      },
      {
        id: "m14-run",
        title: "Workers, proxies and running in production",
        learn: "Uvicorn workers vs Gunicorn, `--proxy-headers` behind Nginx/Traefik, graceful shutdown, one process per container, number of workers, and migrations on deploy.",
        doneWhen: "You can explain how many workers to run for a 2-vCPU box and why migrations don't run in every replica.",
        minutes: 90,
        keywords: ["gunicorn", "uvicorn workers", "--proxy-headers", "reverse proxy", "graceful shutdown", "migration on deploy", "worker count"],
        search: [yt("FastAPI deployment gunicorn uvicorn workers"), web("FastAPI behind a proxy")],
        links: [link("FastAPI: deployment", "https://fastapi.tiangolo.com/deployment/")],
      },
      {
        id: "m14-compose",
        title: "Compose for the whole stack",
        learn: "A compose file for api, worker, Postgres, Redis and a migration job; env files and secrets; volumes and healthchecks with `depends_on`.",
        doneWhen: "`docker compose up` on a fresh clone gives a migrated, working stack.",
        minutes: 90,
        keywords: ["docker compose", "depends_on healthcheck", "env_file", "migration job", "volumes", "profiles"],
        search: [yt("docker compose fastapi postgres redis")],
        links: [link("Docker Compose docs", "https://docs.docker.com/compose/")],
      },
      {
        id: "m14-deploy",
        title: "Deploy to a real host with CI/CD",
        learn: "Pick one: Fly.io, Render, Railway or a VPS with Docker. Build and push an image from CI, set secrets, run migrations, add a health endpoint, a custom domain and HTTPS.",
        doneWhen: "Merging to main deploys your API to a public HTTPS URL with a working /health.",
        minutes: 180,
        keywords: ["Fly.io", "Render", "Railway", "VPS deploy", "CI/CD", "health check", "secrets", "managed Postgres"],
        search: [yt("deploy FastAPI to Fly.io"), yt("deploy FastAPI Render Postgres")],
        links: [
          link("Fly.io docs", "https://fly.io/docs/"),
          link("Render docs", "https://render.com/docs"),
        ],
      },
    ],
    project: {
      id: "m14-proj",
      label: "Major project · Live API",
      kind: "major",
      title: "Deploy your tested, authenticated Postgres API with its worker and Redis to a public URL, with CI/CD, migrations on deploy, HTTPS, secrets from env and a /health endpoint.",
      learn: "A link you can put on a CV and an interviewer can click.",
      doneWhen: "The /docs page is live, you can register a user on it, and a push to main redeploys it.",
      minutes: 360,
      keywords: ["deploy", "HTTPS", "CI/CD", "managed Postgres"],
      search: [web("deploy fastapi docker postgres CI CD github actions fly.io")],
    },
  },
  {
    id: "m15",
    stage: "s5",
    week: "Week 19",
    title: "Performance and observability",
    goal: "Find out why it's slow, know when it breaks, and answer 'how would you scale this?'",
    nodeTip: "Same questions as Node: where's the time going, are you blocking the loop, is the DB the bottleneck? The tools differ: py-spy, cProfile, Prometheus client, OpenTelemetry (same standard you may know).",
    tasks: [
      {
        id: "m15-profile",
        title: "Profiling and finding bottlenecks",
        learn: "`cProfile`, py-spy flame graphs, slow query logging, `asyncio` debug mode to catch blocked loops, and measuring before optimising.",
        doneWhen: "You found and fixed one real bottleneck in your API using a profiler, with before/after numbers.",
        minutes: 90,
        keywords: ["cProfile", "py-spy", "flame graph", "asyncio debug mode", "slow query log", "profiling"],
        search: [yt("Python profiling cProfile py-spy"), web("py-spy flame graph FastAPI")],
        links: [link("py-spy", "https://github.com/benfred/py-spy")],
      },
      {
        id: "m15-load",
        title: "Load testing with Locust or k6",
        learn: "Writing a user scenario, ramping load, reading p50/p95/p99 and error rate, and finding the breaking point.",
        doneWhen: "You ran a load test, found the requests-per-second your API tops out at, and know which resource saturated.",
        minutes: 90,
        keywords: ["Locust", "k6", "load testing", "p95 latency", "throughput", "RPS", "saturation"],
        search: [yt("Locust load testing tutorial python"), yt("k6 load testing tutorial")],
        links: [
          link("Locust docs", "https://docs.locust.io/"),
          link("k6 docs", "https://grafana.com/docs/k6/latest/"),
        ],
      },
      {
        id: "m15-scale",
        title: "Scaling levers: pooling, caching, indexes, workers",
        learn: "DB connection pooling (and PgBouncer), query tuning, caching layers, horizontal scaling of stateless instances, read replicas at a concept level, and what not to optimise early.",
        doneWhen: "You can walk through how you'd take the API from 10 to 1,000 requests per second in order of effort.",
        minutes: 75,
        keywords: ["connection pooling", "PgBouncer", "horizontal scaling", "read replica", "caching layers", "stateless", "premature optimisation"],
        search: [yt("scaling a backend API connection pool caching"), web("system design scaling web app from one server")],
      },
      {
        id: "m15-observe",
        title: "Metrics, tracing and error tracking",
        learn: "Prometheus metrics (prometheus-fastapi-instrumentator), OpenTelemetry tracing, Sentry for exceptions, structured logs, and the health vs readiness split.",
        doneWhen: "A dashboard or a Sentry event shows you a deliberately thrown error with the request context.",
        minutes: 120,
        keywords: ["Prometheus", "OpenTelemetry", "Sentry", "prometheus-fastapi-instrumentator", "tracing", "readiness probe", "golden signals"],
        search: [yt("FastAPI Prometheus Grafana monitoring"), yt("OpenTelemetry FastAPI tracing")],
        links: [
          link("Sentry for Python", "https://docs.sentry.io/platforms/python/"),
          link("OpenTelemetry Python", "https://opentelemetry.io/docs/languages/python/"),
          link("structlog", "https://www.structlog.org/en/stable/"),
        ],
      },
    ],
    project: {
      id: "m15-proj",
      label: "Mini project · Make it measurable",
      kind: "mini",
      title: "Instrument the deployed API with metrics, Sentry and structured logs; load-test it with Locust; fix the top bottleneck; and write a one-page performance note with before/after numbers.",
      learn: "Evidence-based performance work, which is rare and impressive in juniors.",
      doneWhen: "Your note shows a baseline RPS/p95, the change you made, and the improved numbers.",
      minutes: 240,
      keywords: ["Locust", "Sentry", "metrics", "baseline"],
      search: [web("fastapi performance tuning locust results postgres bottleneck")],
    },
  },
  {
    id: "m16",
    stage: "s5",
    week: "Week 20",
    title: "Real-world API features",
    goal: "Cover the features nearly every job's API ends up needing: realtime, files, third-party integrations and email.",
    nodeTip: "ws/socket.io → FastAPI's built-in WebSockets. multer → UploadFile. axios → httpx. nodemailer → fastapi-mail or an email provider's SDK.",
    tasks: [
      {
        id: "m16-ws",
        title: "WebSockets and Server-Sent Events",
        learn: "WebSocket endpoints, a connection manager for rooms and broadcast, auth on connect, and SSE streaming (including streaming LLM-style responses).",
        doneWhen: "A tiny chat or live-notification feature works across two browser tabs, with auth.",
        minutes: 120,
        keywords: ["WebSocket", "connection manager", "Server-Sent Events", "StreamingResponse", "broadcast", "heartbeat", "sse-starlette"],
        search: [yt("FastAPI WebSockets tutorial"), web("FastAPI server sent events streaming")],
        links: [link("FastAPI: WebSockets", "https://fastapi.tiangolo.com/advanced/websockets/")],
      },
      {
        id: "m16-files",
        title: "File uploads and object storage",
        learn: "`UploadFile`, size and type limits, streaming to disk, S3-compatible storage (boto3 or aioboto3), presigned upload and download URLs.",
        doneWhen: "A user uploads an image directly to S3 (or MinIO) with a presigned URL and your API stores only the key.",
        minutes: 120,
        keywords: ["UploadFile", "multipart/form-data", "boto3", "S3", "presigned URL", "MinIO", "content-type validation"],
        search: [yt("FastAPI file upload S3 presigned url"), web("boto3 presigned url upload")],
        links: [link("boto3 quickstart", "https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html")],
      },
      {
        id: "m16-integrations",
        title: "Third-party APIs, webhooks and email",
        learn: "Calling external APIs with timeouts and retries (tenacity), receiving webhooks with signature verification (Stripe-style), idempotent handlers, and sending email via a provider.",
        doneWhen: "A webhook endpoint verifies an HMAC signature and ignores duplicate deliveries.",
        minutes: 120,
        keywords: ["webhook", "HMAC signature", "tenacity", "retries", "idempotency", "Stripe", "transactional email", "circuit breaker"],
        search: [yt("FastAPI webhook signature verification stripe"), web("tenacity retry python httpx")],
      },
    ],
    project: {
      id: "m16-proj",
      label: "Mini project · Feature pack",
      kind: "mini",
      title: "Add three features to your live API: image upload via presigned S3 URLs, a WebSocket or SSE live-updates endpoint, and a signed webhook receiver with idempotency.",
      learn: "Breadth that makes your project feel like a real product.",
      doneWhen: "All three work in the deployed version and each has at least one test.",
      minutes: 300,
      keywords: ["S3", "WebSocket", "webhook", "idempotency key"],
      search: [web("FastAPI presigned url upload websocket webhook project")],
    },
  },

  // ───────────────────────── Stage 6 ─────────────────────────
  {
    id: "m17",
    stage: "s6",
    week: "Weeks 21–22",
    title: "Architecture and system design for backend roles",
    goal: "Reason about how pieces fit together, the senior-ish skill that interviews and promotions test.",
    tasks: [
      {
        id: "m17-layers",
        title: "Layered architecture and clean boundaries",
        learn: "Routers → services → repositories, keeping business rules out of endpoints and ORM models out of API schemas, dependency inversion with Protocols, and when this is over-engineering.",
        doneWhen: "You can unit-test a service with a fake repository and no database.",
        minutes: 120,
        keywords: ["layered architecture", "service layer", "repository", "dependency inversion", "ports and adapters", "domain model", "over-engineering"],
        search: [yt("clean architecture python fastapi"), web("architecture patterns with python cosmic python")],
        links: [link("Cosmic Python (free book)", "https://www.cosmicpython.com/book/preface.html")],
      },
      {
        id: "m17-events",
        title: "Messaging and event-driven basics",
        learn: "Queues vs pub/sub vs streams, RabbitMQ or Kafka concepts, at-least-once delivery, idempotent consumers, the outbox pattern, and dead-letter queues.",
        doneWhen: "You can explain how to avoid losing or double-processing an 'order placed' event.",
        minutes: 120,
        keywords: ["RabbitMQ", "Kafka", "pub/sub", "at-least-once delivery", "outbox pattern", "dead letter queue", "event-driven", "consumer idempotency"],
        search: [yt("message queue vs pub sub vs kafka explained"), web("transactional outbox pattern")],
        links: [link("RabbitMQ tutorials", "https://www.rabbitmq.com/tutorials")],
      },
      {
        id: "m17-services",
        title: "Monolith vs microservices, and service-to-service calls",
        learn: "Why a modular monolith is the right default, when to split, REST vs gRPC between services, timeouts, retries, and distributed failure.",
        doneWhen: "You can argue for a monolith for a 3-person team and name the trigger that would make you split.",
        minutes: 90,
        keywords: ["monolith", "modular monolith", "microservices", "gRPC", "service boundaries", "distributed systems", "eventual consistency"],
        search: [yt("monolith vs microservices when to use"), web("gRPC python quickstart")],
        links: [link("gRPC Python quickstart", "https://grpc.io/docs/languages/python/quickstart/")],
      },
      {
        id: "m17-design",
        title: "System design interviews, backend edition",
        learn: "The framework: requirements, estimates, API, data model, scale and bottlenecks. Practise designing a URL shortener, a rate limiter, a notification service and a feed.",
        doneWhen: "You've designed 4 systems on paper in 35 minutes each and can say the trade-offs aloud.",
        minutes: 240,
        keywords: ["system design", "back-of-envelope estimation", "CAP theorem", "sharding", "caching", "load balancer", "rate limiter design", "URL shortener"],
        search: [yt("system design interview URL shortener"), yt("system design interview rate limiter")],
        links: [link("System Design Primer (free)", "https://github.com/donnemartin/system-design-primer")],
      },
    ],
    project: {
      id: "m17-proj",
      label: "Mini project · Refactor with boundaries",
      kind: "mini",
      title: "Refactor your live API so business logic lives in services behind Protocol-typed repositories, then add one event-driven flow (order or signup event handled by a worker via a queue, with an idempotent consumer).",
      learn: "Architecture you can defend with real code.",
      doneWhen: "Services have fast DB-free unit tests, and replaying the same event twice has no extra effect.",
      minutes: 300,
      keywords: ["Protocol", "fake repository", "event handler", "idempotent"],
      search: [web("python service layer protocol repository fake unit test")],
    },
  },
  {
    id: "m18",
    stage: "s6",
    week: "Week 23",
    title: "The wider Python ecosystem (what jobs also ask for)",
    goal: "Python backend roles often touch scripting, data and AI. Learn enough to be useful and to say yes in interviews.",
    tasks: [
      {
        id: "m18-cli",
        title: "CLIs and automation scripts",
        learn: "Typer for command-line tools, reading and writing CSV/JSON, `subprocess`, scheduled scripts, and packaging a tool so `uvx` or `pipx` can run it.",
        doneWhen: "You shipped a small CLI with 3 subcommands and `--help` that talks to your API.",
        minutes: 90,
        keywords: ["Typer", "argparse", "subprocess", "csv module", "pipx", "uvx", "entry points"],
        search: [yt("Typer CLI python tutorial"), web("python subprocess run best practices")],
        links: [link("Typer", "https://typer.tiangolo.com/")],
      },
      {
        id: "m18-data",
        title: "Pandas and data wrangling basics",
        learn: "DataFrames, reading CSV, filtering, groupby and merge, and exporting a report. Enough to build a reporting endpoint or answer a data question.",
        doneWhen: "You produced a summary report from a CSV with groupby and served it from an endpoint.",
        minutes: 120,
        keywords: ["pandas", "DataFrame", "groupby", "merge", "read_csv", "vectorization", "to_json"],
        search: [yt("Pandas tutorial for beginners"), web("pandas getting started tutorials")],
        links: [link("pandas: getting started", "https://pandas.pydata.org/docs/getting_started/intro_tutorials/")],
      },
      {
        id: "m18-llm",
        title: "Calling LLM APIs from FastAPI",
        learn: "Using an LLM provider's Python SDK (async client), streaming responses over SSE, structured output validated with Pydantic, prompt and cost basics, and retries and timeouts.",
        doneWhen: "An endpoint streams a model's answer and another returns validated structured JSON.",
        minutes: 120,
        keywords: ["LLM API", "async client", "streaming response", "structured output", "Pydantic validation", "token cost", "prompt"],
        search: [yt("FastAPI streaming LLM response SSE"), web("anthropic python sdk async streaming")],
        links: [link("Anthropic Python SDK", "https://github.com/anthropics/anthropic-sdk-python")],
      },
      {
        id: "m18-vector",
        title: "Embeddings and pgvector (RAG basics)",
        learn: "What embeddings are, storing vectors in Postgres with pgvector, similarity search, and the retrieve-then-generate pattern. The most common 'AI feature' on a backend.",
        doneWhen: "A search endpoint returns the 5 most similar documents to a query from Postgres.",
        minutes: 120,
        keywords: ["embeddings", "pgvector", "vector search", "cosine similarity", "RAG", "chunking", "HNSW index"],
        search: [yt("pgvector postgres tutorial python embeddings"), web("RAG explained for backend developers")],
        links: [link("pgvector", "https://github.com/pgvector/pgvector")],
      },
    ],
    project: {
      id: "m18-proj",
      label: "Mini project · AI-flavoured endpoint",
      kind: "mini",
      title: "Add a 'smart search' or 'summarise' feature to your API: embed documents into pgvector, retrieve the top matches, and stream an LLM answer, with a Typer CLI to load documents.",
      learn: "A modern feature that reuses everything you built.",
      doneWhen: "A question returns a streamed answer citing the retrieved documents.",
      minutes: 240,
      keywords: ["pgvector", "streaming", "Typer", "retrieval"],
      search: [web("fastapi pgvector rag example streaming")],
    },
  },
  {
    id: "m19",
    stage: "s6",
    week: "Weeks 24–25",
    title: "Interview prep, portfolio and job search",
    goal: "Turn the skills into offers: know the Python questions, practise coding rounds, and show proof.",
    nodeTip: "You have 2 years of real experience. Lead with it: 'I built Node/Express services, and here is the FastAPI, Postgres and testing equivalent I shipped.' Most Python backend jobs will treat you as mid-level if the portfolio backs it up.",
    tasks: [
      {
        id: "m19-python-q",
        title: "Python interview questions",
        learn: "GIL, generators vs lists, decorators, mutable defaults, `is` vs `==`, `__slots__`, copy vs deepcopy, how dicts work, async vs threads vs processes, MRO, garbage collection.",
        doneWhen: "You can answer 25 common Python questions aloud in under a minute each, with a code example for 10.",
        minutes: 180,
        keywords: ["GIL", "MRO", "deepcopy", "__slots__", "garbage collection", "dict internals", "generators", "mutable default args", "asyncio vs threading"],
        search: [yt("Python interview questions and answers experienced"), web("Python gotchas common mistakes")],
        links: [link("Hitchhiker's Guide: common gotchas", "https://docs.python-guide.org/writing/gotchas/")],
      },
      {
        id: "m19-dsa",
        title: "Coding rounds in Python",
        learn: "Arrays, hash maps, two pointers, sliding window, stacks, queues, trees, BFS/DFS, basic DP, and Python tools (collections, heapq, bisect, itertools). Aim for fluency on easy and medium.",
        doneWhen: "You solved 40 easy and medium problems in Python, timed, and can explain complexity for each.",
        minutes: 600,
        keywords: ["hash map", "two pointers", "sliding window", "BFS DFS", "heapq", "collections.Counter", "defaultdict", "deque", "Big O"],
        search: [yt("NeetCode 150 python"), web("LeetCode python cheat sheet collections heapq")],
        links: [
          link("NeetCode roadmap", "https://neetcode.io/"),
          link("LeetCode", "https://leetcode.com/"),
        ],
      },
      {
        id: "m19-takehome",
        title: "Take-home tasks and live coding",
        learn: "How to approach a 'build an API in 3 hours' task: read the brief, scope, tests, README and trade-offs. Practise live-coding a CRUD endpoint with auth while talking through it.",
        doneWhen: "You completed one timed practice take-home with tests and a README listing your trade-offs.",
        minutes: 240,
        keywords: ["take-home assignment", "live coding", "scoping", "README trade-offs", "tests", "communication"],
        search: [yt("backend take home assignment tips"), web("backend developer take home test examples github")],
      },
      {
        id: "m19-cv",
        title: "CV, GitHub and applying",
        learn: "A CV that leads with impact (not a tech list), a pinned GitHub with clear READMEs, a LinkedIn that says 'Python/FastAPI', and a target list of 30 companies, plus how to talk about the Node-to-Python switch.",
        doneWhen: "CV and profiles are updated and 10 tailored applications are sent.",
        minutes: 240,
        keywords: ["developer CV", "GitHub README", "LinkedIn", "job search", "referrals", "Python backend jobs", "salary research"],
        search: [web("software developer CV examples backend"), web("how to switch backend language Node to Python job")],
      },
    ],
    project: {
      id: "m19-proj",
      label: "Capstone · Job-ready FastAPI service",
      kind: "major",
      title: "One polished, deployed project: typed FastAPI + PostgreSQL + Redis + background worker, JWT auth with roles, full tests and CI, Docker, observability, an OpenAPI-generated client, and a README with architecture diagram, trade-offs and a live URL.",
      learn: "Everything above, in one link a hiring manager can click.",
      doneWhen: "A stranger can open the live /docs, read the README in 5 minutes and see tests, CI, auth, migrations and monitoring.",
      minutes: 600,
      keywords: ["portfolio project", "architecture diagram", "README", "live demo", "trade-offs"],
      search: [web("FastAPI portfolio project ideas backend"), web("mermaid architecture diagram github readme")],
    },
  },
];

function build(m: ModuleIn, index: number): ModuleDoc {
  const tasks: Step[] = m.tasks.map((t) => ({ ...t, links: t.links ?? [] }));
  const project: Project = {
    ...m.project,
    kind: m.project.kind ?? "mini",
    links: m.project.links ?? [],
  };
  return {
    _id: m.id,
    order: index + 1,
    stage: m.stage,
    week: m.week,
    title: m.title,
    goal: m.goal,
    ...(m.nodeTip && { nodeTip: m.nodeTip }),
    tasks,
    project,
    itemIds: [...tasks.map((t) => t.id), project.id],
  };
}

export const MODULES: ModuleDoc[] = MODULES_IN.map(build);
