// The roadmap content. This file is only the SOURCE for the database:
// `pnpm seed` copies it into MongoDB, and the app reads it from there.
//
// Keep each `id` the same when you reword a step. Progress and notes are saved
// by id. Edit this file, then run `pnpm seed` again to update the database.
//
// This file must not import anything except types: the seed script runs it
// directly with Node.
import type { Link, ModuleDoc, Project, Search, StageDoc, Step } from "./roadmap-types";

const yt = (q: string): Search => ({ q, on: "yt" });
const web = (q: string): Search => ({ q, on: "web" });
const link = (label: string, url: string): Link => ({ label, url });

type StepIn = Omit<Step, "links"> & { links?: Link[] };
type ProjectIn = StepIn & { label: string; kind?: "mini" | "major" };
type ModuleIn = {
  id: string;
  stage: string;
  week: string;
  title: string;
  goal: string;
  nodeTip?: string;
  tasks: StepIn[];
  project: ProjectIn;
};

export const ROADMAP_VERSION = 1;

export const STAGES: StageDoc[] = [
  { _id: "s1", order: 1, title: "Foundations: Linux, Git, networking", blurb: "The ground everything else stands on: the shell, scripts, Git and how the web moves bytes. About 5 weeks." },
  { _id: "s2", order: 2, title: "Containers", blurb: "Package your Node apps so they run the same everywhere. About 3 weeks." },
  { _id: "s3", order: 3, title: "CI/CD and automation", blurb: "Every push is built, tested and shipped by a robot. About 4 weeks." },
  { _id: "s4", order: 4, title: "Cloud and infrastructure as code", blurb: "Rent servers from AWS, then describe them in code with Terraform. About 5 weeks." },
  { _id: "s5", order: 5, title: "Kubernetes and GitOps", blurb: "Run containers at scale and let Git drive deployments. About 6 weeks." },
  { _id: "s6", order: 6, title: "Observability, reliability, security", blurb: "Know when things break, keep them up, and keep them safe. About 5 weeks." },
  { _id: "s7", order: 7, title: "Platform and career", blurb: "Package everything into proof and pick what to go deeper on. About 2 weeks." },
];

const MODULES_IN: ModuleIn[] = [
  // ───────────────────────── Stage 1 ─────────────────────────
  {
    id: "m01",
    stage: "s1",
    week: "Week 1",
    title: "Linux and the command line",
    goal: "Be comfortable driving a Linux machine with only a terminal, since every server and container you'll meet runs Linux.",
    nodeTip: "process.env → environment variables in your shell, `node app.js &` → a background job, nodemon restarting → systemd restarting your service.",
    tasks: [
      {
        id: "m01-nav",
        title: "Files, directories and everyday commands",
        learn: "The filesystem layout (/etc, /var, /home, /usr), ls, cd, cp, mv, rm, find, cat, less, tail -f, man pages and --help.",
        doneWhen: "You can find every .log file under /var/log modified in the last day and read the end of one live, without a GUI.",
        minutes: 150,
        keywords: ["filesystem hierarchy", "ls", "find", "tail -f", "man page", "absolute vs relative path"],
        search: [yt("Linux command line for beginners full course"), yt("Linux filesystem hierarchy explained"), web("linuxjourney command line")],
        links: [
          link("Linux Journey (free, interactive)", "https://linuxjourney.com/"),
          link("The Linux Command Line (free book)", "https://linuxcommand.org/tlcl.php"),
        ],
      },
      {
        id: "m01-perms",
        title: "Users, groups and permissions",
        learn: "rwx bits, chmod and chown, octal modes like 644 and 755, sudo, why you never run services as root.",
        doneWhen: "You can explain what `-rwxr-x---` means and fix a 'permission denied' on a script yourself.",
        minutes: 90,
        keywords: ["chmod", "chown", "sudo", "umask", "setuid", "least privilege"],
        search: [yt("Linux file permissions explained chmod chown"), web("linuxjourney permissions")],
      },
      {
        id: "m01-proc",
        title: "Processes, signals and systemd",
        learn: "ps, top/htop, kill and signals (SIGTERM vs SIGKILL), foreground vs background, systemd units, systemctl and journalctl.",
        doneWhen: "You wrote a systemd unit that runs a small Node server, restarts it on crash, and you read its logs with journalctl.",
        minutes: 150,
        keywords: ["systemctl", "journalctl", "unit file", "SIGTERM", "Restart=always", "htop"],
        search: [yt("systemd service file tutorial"), yt("Linux processes and signals explained"), web("run node app as systemd service")],
        links: [link("systemd.service man page", "https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html")],
      },
      {
        id: "m01-text",
        title: "Pipes and text tools",
        learn: "stdin, stdout, stderr, pipes, redirects, grep, sed, awk, cut, sort, uniq, xargs. The shell's version of array.map/filter.",
        doneWhen: "From a web access log you printed the 10 most frequent IP addresses with one pipeline.",
        minutes: 120,
        keywords: ["pipe", "redirect", "grep", "awk", "sed", "xargs", "stderr 2>&1"],
        search: [yt("grep sed awk tutorial Linux"), web("overthewire bandit wargame")],
        links: [link("OverTheWire Bandit (learn by playing)", "https://overthewire.org/wargames/bandit/")],
      },
    ],
    project: {
      id: "m01-proj",
      label: "Mini project · Run your own service",
      kind: "mini",
      title: "In a free Linux VM or an Ubuntu container, install Node, run a tiny HTTP server as a non-root user under systemd, and make it survive a crash.",
      learn: "Everything above on a real machine: users, permissions, a service and logs.",
      doneWhen: "`kill -9` on the server process brings it back within seconds and `journalctl -u` shows the restart.",
      minutes: 150,
      keywords: ["Multipass", "VirtualBox", "Ubuntu", "systemd", "non-root user"],
      search: [yt("Multipass Ubuntu VM tutorial"), web("systemd restart on failure example")],
      links: [link("Multipass (free local Ubuntu VMs)", "https://multipass.run/")],
    },
  },
  {
    id: "m02",
    stage: "s1",
    week: "Week 2",
    title: "Bash scripting",
    goal: "Automate repetitive work with scripts you can trust to fail loudly instead of silently.",
    nodeTip: "A bash script is your `scripts` section in package.json, with no compiler and a lot of sharp edges. Quote your variables.",
    tasks: [
      {
        id: "m02-basics",
        title: "Variables, conditions, loops and functions",
        learn: "Variables and quoting, if/test ([[ ]]), for/while, functions, arguments ($1, $@), exit codes ($?).",
        doneWhen: "You wrote a script that takes a directory argument, loops over its files and prints a size summary, with a usage message when run without arguments.",
        minutes: 150,
        keywords: ["shebang", "quoting", "$@", "exit code", "[[ ]]", "for loop", "function"],
        search: [yt("Bash scripting full course"), web("bash scripting tutorial beginners")],
        links: [link("Exercism: Bash track (free exercises)", "https://exercism.org/tracks/bash")],
      },
      {
        id: "m02-safe",
        title: "Safe scripts: strict mode, traps and ShellCheck",
        learn: "`set -euo pipefail`, trap for cleanup, mktemp, and linting with ShellCheck so you catch quoting bugs before they delete things.",
        doneWhen: "ShellCheck reports zero warnings on your script and a failing command in the middle stops it.",
        minutes: 90,
        keywords: ["set -euo pipefail", "trap", "ShellCheck", "mktemp", "idempotent"],
        search: [yt("bash strict mode set -euo pipefail"), web("ShellCheck common mistakes")],
        links: [
          link("ShellCheck (paste a script, get fixes)", "https://www.shellcheck.net/"),
          link("Google Shell Style Guide", "https://google.github.io/styleguide/shellguide.html"),
        ],
      },
      {
        id: "m02-cron",
        title: "Scheduling with cron and curl + jq",
        learn: "Crontab syntax, running scripts on a schedule, calling APIs with curl and slicing JSON with jq.",
        doneWhen: "A cron job calls a public JSON API every minute and appends one extracted field to a file.",
        minutes: 90,
        keywords: ["crontab", "curl", "jq", "cron expression", "systemd timer"],
        search: [yt("cron jobs explained crontab"), yt("jq tutorial JSON command line"), web("crontab guru")],
        links: [
          link("crontab.guru (cron expression helper)", "https://crontab.guru/"),
          link("jq manual", "https://jqlang.github.io/jq/manual/"),
        ],
      },
    ],
    project: {
      id: "m02-proj",
      label: "Mini project · Backup script",
      kind: "mini",
      title: "Write a backup script: archive a folder to a timestamped .tar.gz, keep only the last 7, log what it did, and run it nightly from cron.",
      learn: "Arguments, strict mode, cleanup, rotation and scheduling in one useful tool.",
      doneWhen: "Run it 10 times and exactly 7 archives remain; ShellCheck is clean.",
      minutes: 120,
      keywords: ["tar", "rotation", "date format", "logging"],
      search: [web("bash backup script tar rotate old backups")],
    },
  },
  {
    id: "m03",
    stage: "s1",
    week: "Week 3",
    title: "Git beyond add, commit, push",
    goal: "Understand Git well enough to recover from mistakes and to work in the branching flows teams use.",
    nodeTip: "You already use Git. Now learn the model underneath: commits are snapshots, branches are movable labels.",
    tasks: [
      {
        id: "m03-model",
        title: "How Git actually works",
        learn: "Commits, trees, HEAD, branches as pointers, the staging area, reflog. Visualise it until it clicks.",
        doneWhen: "You can explain what `git reset --hard HEAD~1` does to the branch, and recover that commit using reflog.",
        minutes: 120,
        keywords: ["HEAD", "reflog", "detached HEAD", "reset vs revert", "staging area"],
        search: [yt("Git internals explained how git works"), web("learn git branching")],
        links: [
          link("Learn Git Branching (visual, interactive)", "https://learngitbranching.js.org/"),
          link("Pro Git book (free)", "https://git-scm.com/book/en/v2"),
        ],
      },
      {
        id: "m03-rebase",
        title: "Merge, rebase and resolving conflicts",
        learn: "Merge vs rebase, interactive rebase to tidy commits, cherry-pick, stash, and calmly resolving conflicts.",
        doneWhen: "You made a conflict on purpose, resolved it, then squashed 4 messy commits into 1 with `git rebase -i`.",
        minutes: 120,
        keywords: ["git rebase -i", "merge conflict", "cherry-pick", "git stash", "squash"],
        search: [yt("git rebase vs merge explained"), yt("git interactive rebase tutorial")],
      },
      {
        id: "m03-flow",
        title: "Branching strategies and pull requests",
        learn: "Trunk-based development vs GitFlow, short-lived branches, PR review habits, protected branches, semantic versioning and Conventional Commits.",
        doneWhen: "You can say why trunk-based suits CI/CD and set up branch protection requiring a PR on a repo of yours.",
        minutes: 90,
        keywords: ["trunk-based development", "GitFlow", "branch protection", "semver", "Conventional Commits"],
        search: [yt("trunk based development vs gitflow"), web("conventional commits semantic versioning")],
        links: [
          link("trunkbaseddevelopment.com", "https://trunkbaseddevelopment.com/"),
          link("GitHub Skills (free hands-on courses)", "https://skills.github.com/"),
        ],
      },
    ],
    project: {
      id: "m03-proj",
      label: "Mini project · Team workflow on your own repo",
      kind: "mini",
      title: "On a practice repo, protect main, work through 3 feature branches via pull requests, create a release tag v1.0.0 and revert one bad commit.",
      learn: "The daily loop of a team, done solo.",
      doneWhen: "main only changes through merged PRs, and a tagged release exists on GitHub.",
      minutes: 120,
      keywords: ["pull request", "git tag", "GitHub release", "git revert"],
      search: [web("GitHub protected branches require pull request")],
    },
  },
  {
    id: "m04",
    stage: "s1",
    week: "Weeks 4–5",
    title: "Networking and the web",
    goal: "Know what happens between a browser and your server, so you can debug 'it can't connect' like an adult.",
    nodeTip: "app.listen(3000) binds a port on an interface. Most 'works on my machine' pain is binding to 127.0.0.1 instead of 0.0.0.0.",
    tasks: [
      {
        id: "m04-ip",
        title: "IP, ports, TCP and subnets",
        learn: "IP addresses, CIDR notation, private ranges, ports, TCP vs UDP, NAT, and the tools: ping, ss/netstat, traceroute, curl -v.",
        doneWhen: "You can say how many hosts a /24 holds and use `ss -tlnp` to find which process owns port 3000.",
        minutes: 150,
        keywords: ["CIDR", "subnet", "TCP handshake", "NAT", "ss -tlnp", "private IP ranges"],
        search: [yt("networking fundamentals for DevOps"), yt("subnetting explained CIDR"), web("what is a port TCP vs UDP")],
        links: [link("Cloudflare Learning Center", "https://www.cloudflare.com/learning/")],
      },
      {
        id: "m04-dns",
        title: "DNS",
        learn: "How a name becomes an IP: resolvers, records (A, AAAA, CNAME, MX, TXT), TTL, and dig/nslookup.",
        doneWhen: "You used dig to trace a domain's A record and can explain why a DNS change 'hasn't propagated'.",
        minutes: 75,
        keywords: ["A record", "CNAME", "TTL", "dig", "recursive resolver", "nameserver"],
        search: [yt("how DNS works explained"), web("howdns.works")],
        links: [link("How DNS works (comic)", "https://howdns.works/")],
      },
      {
        id: "m04-http",
        title: "HTTP and TLS",
        learn: "Methods, status codes, headers, keep-alive, HTTP/2, what TLS and certificates do, Let's Encrypt, and reading a request with curl -v.",
        doneWhen: "You inspected a site's certificate chain from the terminal and explained the TLS handshake in 3 sentences.",
        minutes: 120,
        keywords: ["HTTP headers", "status codes", "TLS handshake", "certificate", "Let's Encrypt", "openssl s_client"],
        search: [yt("HTTPS TLS handshake explained"), yt("HTTP crash course status codes headers")],
        links: [link("MDN: HTTP", "https://developer.mozilla.org/en-US/docs/Web/HTTP")],
      },
      {
        id: "m04-nginx",
        title: "Nginx as a reverse proxy and load balancer",
        learn: "Server blocks, proxy_pass to a Node app, static files, upstream load balancing, gzip, and where TLS terminates.",
        doneWhen: "Nginx proxies port 80 to two Node instances and you can see requests alternate between them.",
        minutes: 150,
        keywords: ["nginx", "reverse proxy", "proxy_pass", "upstream", "load balancer", "TLS termination"],
        search: [yt("nginx reverse proxy tutorial node"), yt("nginx load balancing round robin")],
        links: [link("Nginx beginner's guide", "https://nginx.org/en/docs/beginners_guide.html")],
      },
    ],
    project: {
      id: "m04-proj",
      label: "Mini project · Node app behind Nginx with HTTPS",
      kind: "mini",
      title: "Run a Node API on two ports, put Nginx in front as a load balancer, and serve it over local HTTPS using a mkcert certificate and a hosts-file name.",
      learn: "Reverse proxy, load balancing and TLS together, the shape of nearly every production web setup.",
      doneWhen: "https://myapp.local loads with a green lock and traffic splits across both instances.",
      minutes: 180,
      keywords: ["mkcert", "/etc/hosts", "upstream", "ssl_certificate"],
      search: [web("mkcert local https nginx"), web("nginx upstream two node servers")],
      links: [link("mkcert", "https://github.com/FiloSottile/mkcert")],
    },
  },

  // ───────────────────────── Stage 2 ─────────────────────────
  {
    id: "m05",
    stage: "s2",
    week: "Week 6",
    title: "Docker fundamentals",
    goal: "Understand images, containers, layers and how to package a Node app so it runs identically anywhere.",
    nodeTip: "An image is like a published npm package of your whole runtime; a container is a running instance of it. `npm ci` belongs inside the Dockerfile.",
    tasks: [
      {
        id: "m05-concepts",
        title: "Containers vs VMs, images and layers",
        learn: "What a container really is (namespaces + cgroups, a process with walls), how image layers and caching work, registries and tags.",
        doneWhen: "You can explain why a container starts in under a second and why changing line 1 of a Dockerfile rebuilds everything after it.",
        minutes: 90,
        keywords: ["container", "image", "layer", "namespace", "cgroup", "registry", "tag"],
        search: [yt("Docker explained containers vs virtual machines"), yt("Docker tutorial for beginners full course")],
        links: [link("Docker: Get started", "https://docs.docker.com/get-started/")],
      },
      {
        id: "m05-cli",
        title: "Run and manage containers",
        learn: "docker run (-d, -p, -e, --name, --rm), ps, logs, exec, stop, rm, images, pull. Run Nginx and Mongo from Docker Hub.",
        doneWhen: "You ran Mongo in a container, connected to it from a local Node script, then removed it cleanly.",
        minutes: 90,
        keywords: ["docker run", "port mapping -p", "docker exec", "docker logs", "Docker Hub", "--rm"],
        search: [yt("docker run docker exec docker logs tutorial"), web("Play with Docker labs")],
        links: [link("Play with Docker (free browser labs)", "https://labs.play-with-docker.com/")],
      },
      {
        id: "m05-dockerfile",
        title: "Writing a Dockerfile",
        learn: "FROM, WORKDIR, COPY, RUN, ENV, EXPOSE, CMD vs ENTRYPOINT, .dockerignore, and ordering instructions so dependency installs are cached.",
        doneWhen: "You built an image of a Node app where editing source code does not re-run `npm ci`.",
        minutes: 120,
        keywords: ["Dockerfile", "FROM", "COPY", "CMD vs ENTRYPOINT", ".dockerignore", "layer caching"],
        search: [yt("Dockerfile node.js tutorial best practices"), web("dockerize node app dockerfile")],
        links: [link("Dockerfile reference", "https://docs.docker.com/reference/dockerfile/")],
      },
      {
        id: "m05-data",
        title: "Volumes, bind mounts and networks",
        learn: "Containers are disposable, so data goes in volumes. Bind mounts for dev, user-defined networks so containers reach each other by name.",
        doneWhen: "A Mongo container keeps its data after you delete and recreate it, and a Node container reaches it by service name.",
        minutes: 90,
        keywords: ["volume", "bind mount", "docker network", "container DNS", "persistent data"],
        search: [yt("Docker volumes and networks explained")],
        links: [link("Docker: volumes", "https://docs.docker.com/engine/storage/volumes/")],
      },
    ],
    project: {
      id: "m05-proj",
      label: "Mini project · Dockerize a Node app",
      kind: "mini",
      title: "Containerize one of your own Node apps: write the Dockerfile and .dockerignore, run it with environment variables, and push the image to Docker Hub or GHCR.",
      learn: "The whole build, run, ship loop for one service.",
      doneWhen: "A friend (or a second machine) runs your app with a single `docker run` from the registry.",
      minutes: 150,
      keywords: ["docker build", "docker push", "GHCR", "image tag"],
      search: [web("docker build tag push to GitHub Container Registry")],
    },
  },
  {
    id: "m06",
    stage: "s2",
    week: "Weeks 7–8",
    title: "Docker in practice: Compose, small images, secure images",
    goal: "Run multi-service apps locally and build production-grade images: small, fast and not running as root.",
    tasks: [
      {
        id: "m06-compose",
        title: "Docker Compose",
        learn: "A compose.yaml for app + database + cache: services, ports, env files, volumes, depends_on with healthchecks, profiles.",
        doneWhen: "`docker compose up` starts your Node app, Mongo and Redis together and `docker compose down -v` wipes them.",
        minutes: 120,
        keywords: ["docker compose", "compose.yaml", "depends_on", "healthcheck", "env_file", "profiles"],
        search: [yt("docker compose tutorial node mongo"), web("docker compose healthcheck depends_on condition")],
        links: [link("Docker Compose docs", "https://docs.docker.com/compose/")],
      },
      {
        id: "m06-multistage",
        title: "Multi-stage builds and small images",
        learn: "Build in one stage, copy only the output into a slim runtime stage. alpine vs slim vs distroless, and why size matters for speed and attack surface.",
        doneWhen: "Your Node image dropped from over 1 GB to under 200 MB and you can say what you removed.",
        minutes: 120,
        keywords: ["multi-stage build", "alpine", "distroless", "node:slim", "image size", "dive"],
        search: [yt("Docker multi-stage build node typescript"), web("reduce docker image size node")],
        links: [link("Docker: Building best practices", "https://docs.docker.com/build/building/best-practices/")],
      },
      {
        id: "m06-secure",
        title: "Container security basics",
        learn: "Run as a non-root USER, pin base image versions, never bake secrets into layers, read-only filesystems, and scan with Trivy.",
        doneWhen: "Your image runs as a non-root user and a Trivy scan result is saved in your note with the top issue explained.",
        minutes: 90,
        keywords: ["USER node", "Trivy", "image scanning", "pin versions", "secrets in layers", "read-only rootfs"],
        search: [yt("Docker security best practices"), yt("Trivy scan docker image tutorial")],
        links: [link("Trivy docs", "https://trivy.dev/latest/docs/")],
      },
      {
        id: "m06-twelve",
        title: "The Twelve-Factor App",
        learn: "The rules that make apps container-friendly: config in env, logs to stdout, stateless processes, disposability, dev/prod parity.",
        doneWhen: "You audited one of your apps against all 12 factors and noted the 3 it breaks.",
        minutes: 60,
        keywords: ["twelve-factor", "config in environment", "stateless", "logs to stdout", "disposability"],
        search: [yt("twelve factor app explained")],
        links: [link("12factor.net", "https://12factor.net/")],
      },
    ],
    project: {
      id: "m06-proj",
      label: "Major project · Full stack in Compose",
      kind: "major",
      title: "Compose a production-style stack: Nginx → two replicas of your Node API (multi-stage, non-root image) → MongoDB with a volume, all started by one command.",
      learn: "Containers, networking, persistence and security together.",
      doneWhen: "A fresh clone plus `docker compose up` gives a working app; a Trivy scan has no critical issues.",
      minutes: 240,
      keywords: ["compose replicas", "nginx upstream", "volume", "trivy"],
      search: [web("docker compose nginx node mongo example")],
    },
  },

  // ───────────────────────── Stage 3 ─────────────────────────
  {
    id: "m07",
    stage: "s3",
    week: "Week 9",
    title: "CI with GitHub Actions",
    goal: "Make every push build, lint, test and package your code automatically.",
    nodeTip: "A workflow is `npm ci && npm test && npm run build` run by a robot on a fresh machine every time. If it only works on yours, it's broken.",
    tasks: [
      {
        id: "m07-basics",
        title: "Workflows, jobs, steps and triggers",
        learn: "The YAML anatomy: on (push, pull_request, schedule, workflow_dispatch), jobs, runs-on, steps, uses vs run, and reading logs.",
        doneWhen: "A workflow runs on every PR, checks out the repo, sets up Node and runs your tests, and the PR shows a red or green check.",
        minutes: 120,
        keywords: ["GitHub Actions", "workflow YAML", "on: pull_request", "runs-on", "actions/checkout", "setup-node"],
        search: [yt("GitHub Actions tutorial CI node"), web("GitHub Actions quickstart")],
        links: [link("GitHub Actions docs", "https://docs.github.com/en/actions")],
      },
      {
        id: "m07-speed",
        title: "Caching, matrices and artifacts",
        learn: "Cache node_modules, a build matrix across Node versions, upload and download artifacts, job dependencies with needs.",
        doneWhen: "Tests run on Node 20 and 22 in parallel and a repeat run is visibly faster thanks to cache.",
        minutes: 90,
        keywords: ["actions/cache", "matrix strategy", "artifacts", "needs", "concurrency"],
        search: [yt("GitHub Actions matrix cache artifacts")],
      },
      {
        id: "m07-secrets",
        title: "Secrets, environments and reusable workflows",
        learn: "Encrypted secrets, environment protection rules, the GITHUB_TOKEN, and reusable workflows so 10 repos share one pipeline.",
        doneWhen: "A deploy job reads a secret, never prints it, and waits for your manual approval via an environment.",
        minutes: 90,
        keywords: ["secrets", "environments", "GITHUB_TOKEN", "reusable workflow", "workflow_call", "approval"],
        search: [yt("GitHub Actions secrets environments approval")],
        links: [link("GitHub: using secrets", "https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions")],
      },
      {
        id: "m07-image",
        title: "Build and push a Docker image from CI",
        learn: "docker/build-push-action, logging in to GHCR with GITHUB_TOKEN, tagging by git SHA and semver, build cache.",
        doneWhen: "Merging to main publishes ghcr.io/you/app:<sha> automatically.",
        minutes: 90,
        keywords: ["docker/build-push-action", "GHCR", "image tag by SHA", "docker/metadata-action", "buildx cache"],
        search: [yt("GitHub Actions build and push docker image ghcr")],
        links: [link("Docker: GitHub Actions guide", "https://docs.docker.com/build/ci/github-actions/")],
      },
    ],
    project: {
      id: "m07-proj",
      label: "Mini project · Full CI pipeline",
      kind: "mini",
      title: "Pipeline for your Node app: lint, test (matrix), build the image, scan with Trivy, and push to GHCR on main. Add a status badge to the README.",
      learn: "A real CI pipeline you'd be happy to inherit.",
      doneWhen: "A deliberately broken test blocks the merge and a good change ships an image tagged with its commit SHA.",
      minutes: 180,
      keywords: ["CI pipeline", "status badge", "trivy-action", "required checks"],
      search: [web("github actions trivy scan docker image workflow")],
    },
  },
  {
    id: "m08",
    stage: "s3",
    week: "Week 10",
    title: "Continuous delivery and release strategies",
    goal: "Ship changes safely and be able to undo them fast.",
    tasks: [
      {
        id: "m08-cd",
        title: "CI vs delivery vs deployment, and DORA metrics",
        learn: "Continuous integration, delivery and deployment are different things. The four DORA metrics: deployment frequency, lead time, change failure rate, time to restore.",
        doneWhen: "You can describe your own project's current lead time for a change and where it is slow.",
        minutes: 60,
        keywords: ["continuous delivery", "continuous deployment", "DORA metrics", "lead time", "change failure rate"],
        search: [yt("CI vs CD continuous delivery vs deployment"), web("DORA four key metrics")],
        links: [link("dora.dev", "https://dora.dev/")],
      },
      {
        id: "m08-strategies",
        title: "Rolling, blue-green and canary releases",
        learn: "How each strategy trades speed, cost and risk; rollbacks; database migrations that stay backward compatible (expand and contract).",
        doneWhen: "You can pick a strategy for a payments service vs a marketing page and defend it.",
        minutes: 75,
        keywords: ["blue-green deployment", "canary release", "rolling update", "rollback", "expand and contract migration"],
        search: [yt("blue green vs canary vs rolling deployment")],
      },
      {
        id: "m08-flags",
        title: "Feature flags and zero-downtime deploys",
        learn: "Decouple deploy from release with flags; health checks, graceful shutdown (handle SIGTERM in Node) and connection draining.",
        doneWhen: "Your Node server finishes in-flight requests on SIGTERM and exits 0.",
        minutes: 75,
        keywords: ["feature flag", "graceful shutdown", "SIGTERM", "health check endpoint", "readiness"],
        search: [yt("feature flags explained"), web("node.js graceful shutdown SIGTERM express")],
      },
      {
        id: "m08-vps",
        title: "Deploy over SSH to a server",
        learn: "SSH keys, a deploy user, pulling and restarting a container on a VPS from a pipeline, and a rollback by re-deploying the previous tag.",
        doneWhen: "Pushing to main updates a running container on a cheap or free VPS with no manual steps.",
        minutes: 150,
        keywords: ["SSH key", "appleboy/ssh-action", "docker compose pull", "deploy user", "rollback tag"],
        search: [yt("deploy docker container to VPS with GitHub Actions SSH"), web("Oracle Cloud always free VM")],
        links: [link("Oracle Cloud Always Free", "https://www.oracle.com/cloud/free/")],
      },
    ],
    project: {
      id: "m08-proj",
      label: "Major project · Push-to-deploy",
      kind: "major",
      title: "Extend your pipeline into CD: on merge to main it builds the image, deploys to a server, runs a smoke test, and auto-rolls back to the previous tag if the health check fails.",
      learn: "A deploy pipeline with a safety net, which is the whole point of DevOps.",
      doneWhen: "You shipped a deliberately broken release and the pipeline rolled it back by itself.",
      minutes: 300,
      keywords: ["smoke test", "health check", "auto rollback", "deploy pipeline"],
      search: [web("github actions deploy docker rollback on failed health check")],
    },
  },
  {
    id: "m09",
    stage: "s3",
    week: "Weeks 11–12",
    title: "Configuration management with Ansible",
    goal: "Configure servers from code instead of by hand, safely repeatable.",
    nodeTip: "An Ansible playbook is a declarative YAML script. Idempotent means running it twice changes nothing the second time.",
    tasks: [
      {
        id: "m09-basics",
        title: "Inventory, ad-hoc commands and your first playbook",
        learn: "Agentless over SSH, inventory files, modules (apt, copy, service), plays and tasks, running with ansible-playbook.",
        doneWhen: "A playbook installs Nginx on a VM and ansible-playbook says `changed=0` on the second run.",
        minutes: 150,
        keywords: ["Ansible", "inventory", "playbook", "module", "idempotent", "ansible-playbook"],
        search: [yt("Ansible tutorial for beginners playbook"), web("Ansible getting started")],
        links: [link("Ansible: Getting started", "https://docs.ansible.com/ansible/latest/getting_started/index.html")],
      },
      {
        id: "m09-roles",
        title: "Variables, templates, handlers and roles",
        learn: "Jinja2 templates, group_vars, handlers that restart a service only on change, structuring work into roles, Ansible Vault for secrets.",
        doneWhen: "Changing one template variable updates the Nginx config and reloads the service, only when it changed.",
        minutes: 150,
        keywords: ["Jinja2 template", "handlers", "roles", "group_vars", "ansible-vault", "ansible-galaxy"],
        search: [yt("Ansible roles templates handlers tutorial")],
        links: [link("Ansible Galaxy", "https://galaxy.ansible.com/")],
      },
    ],
    project: {
      id: "m09-proj",
      label: "Mini project · One-command server",
      kind: "mini",
      title: "Write a role that takes a blank Ubuntu VM to a hardened app server: non-root deploy user, SSH key only, firewall (ufw), Docker, Nginx, and your app container.",
      learn: "The server you built by hand in module 1, now reproducible from a single command.",
      doneWhen: "You destroyed the VM, created a new one, ran the playbook, and the app was back with zero manual steps.",
      minutes: 240,
      keywords: ["ufw", "sshd_config", "hardening", "role"],
      search: [web("ansible role harden ubuntu server ssh ufw docker")],
    },
  },

  // ───────────────────────── Stage 4 ─────────────────────────
  {
    id: "m10",
    stage: "s4",
    week: "Weeks 13–14",
    title: "Cloud fundamentals (AWS as the example)",
    goal: "Know the core building blocks of a cloud and use them without a surprise bill. The ideas carry over to GCP and Azure.",
    nodeTip: "Do step one before anything else: set a billing budget alert. Then tear down every experiment the same day.",
    tasks: [
      {
        id: "m10-account",
        title: "Account safety, billing alerts and IAM",
        learn: "Create an AWS free-tier account, turn on MFA, never use the root user, set a budget alert, and learn IAM users, roles, policies and least privilege.",
        doneWhen: "A $1 budget alert is active, root has MFA, and you work as an IAM user whose policy only allows what you need.",
        minutes: 120,
        keywords: ["AWS free tier", "AWS Budgets", "IAM user", "IAM role", "IAM policy", "MFA", "least privilege"],
        search: [yt("AWS IAM tutorial for beginners"), yt("AWS free tier set billing alarm budget")],
        links: [
          link("AWS Free Tier", "https://aws.amazon.com/free/"),
          link("AWS Skill Builder (free courses)", "https://skillbuilder.aws/"),
        ],
      },
      {
        id: "m10-compute",
        title: "Compute and storage: EC2 and S3",
        learn: "Launch a Linux instance, security groups, key pairs, instance types; S3 buckets, objects, public vs private, presigned URLs.",
        doneWhen: "You SSH'd into an EC2 instance, ran your container on it, then terminated it; and uploaded a file to a private S3 bucket and shared it with a presigned URL.",
        minutes: 150,
        keywords: ["EC2", "security group", "key pair", "AMI", "S3 bucket", "presigned URL", "AWS CLI"],
        search: [yt("AWS EC2 tutorial launch instance ssh"), yt("AWS S3 tutorial for beginners")],
        links: [link("AWS CLI getting started", "https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html")],
      },
      {
        id: "m10-network",
        title: "Cloud networking: VPC, subnets and load balancers",
        learn: "A VPC with public and private subnets, route tables, internet and NAT gateways, and an Application Load Balancer in front of instances.",
        doneWhen: "You drew your VPC on paper and can say why a database sits in a private subnet.",
        minutes: 150,
        keywords: ["VPC", "public subnet", "private subnet", "internet gateway", "NAT gateway", "ALB", "route table"],
        search: [yt("AWS VPC explained subnets route tables"), yt("AWS application load balancer tutorial")],
      },
      {
        id: "m10-data",
        title: "Managed databases, DNS and cost thinking",
        learn: "RDS vs running a database yourself, Route 53 for DNS, CloudWatch basics, and how to read the bill and find what costs money.",
        doneWhen: "You can estimate the monthly cost of your stack with the AWS pricing calculator.",
        minutes: 90,
        keywords: ["RDS", "Route 53", "CloudWatch", "AWS pricing calculator", "Cost Explorer"],
        search: [yt("AWS RDS vs self managed database"), web("AWS pricing calculator")],
        links: [link("AWS Pricing Calculator", "https://calculator.aws/")],
      },
    ],
    project: {
      id: "m10-proj",
      label: "Mini project · Hand-built deployment (then delete it)",
      kind: "mini",
      title: "By hand in the console: a VPC, a public EC2 instance running your container behind Nginx, and an S3 bucket for uploads. Then tear down everything.",
      learn: "Doing it manually once is how you appreciate Terraform in the next module.",
      doneWhen: "The app answers on a public IP, and the Billing page shows nothing left running.",
      minutes: 240,
      keywords: ["console", "teardown", "cost check"],
      search: [web("deploy docker container on EC2 tutorial")],
    },
  },
  {
    id: "m11",
    stage: "s4",
    week: "Weeks 15–16",
    title: "Infrastructure as code with Terraform",
    goal: "Describe infrastructure in files, review it like code, and create or destroy it with one command.",
    nodeTip: "Terraform is package.json plus a lockfile for servers. `plan` is a dry run, `apply` makes it real, and the state file is the dangerous part.",
    tasks: [
      {
        id: "m11-basics",
        title: "HCL, providers, resources and the plan/apply loop",
        learn: "Install Terraform (or OpenTofu), the AWS provider, resources, init/plan/apply/destroy, reading a plan before you apply it.",
        doneWhen: "You created and destroyed an S3 bucket from a .tf file and read the plan output line by line.",
        minutes: 150,
        keywords: ["Terraform", "HCL", "provider", "terraform plan", "terraform apply", "resource block"],
        search: [yt("Terraform tutorial for beginners AWS"), web("HashiCorp Terraform AWS get started")],
        links: [
          link("Terraform tutorials (HashiCorp)", "https://developer.hashicorp.com/terraform/tutorials"),
          link("OpenTofu docs (open-source fork)", "https://opentofu.org/docs/"),
        ],
      },
      {
        id: "m11-vars",
        title: "Variables, outputs, data sources and dependencies",
        learn: "Input variables, locals, outputs, data sources, implicit vs explicit dependencies, count and for_each, tfvars files.",
        doneWhen: "One config creates 3 similar resources with for_each and outputs their IDs.",
        minutes: 120,
        keywords: ["variable", "output", "data source", "for_each", "count", "locals", "tfvars"],
        search: [yt("Terraform variables outputs for_each tutorial")],
      },
      {
        id: "m11-state",
        title: "State, remote backends and locking",
        learn: "What the state file is, why it must never be committed, remote state in S3 with locking, and drift (someone changed it by hand).",
        doneWhen: "State lives in a remote backend and you detected and fixed drift after changing a tag in the console.",
        minutes: 120,
        keywords: ["terraform state", "remote backend", "S3 backend", "state locking", "drift", "terraform import"],
        search: [yt("Terraform remote state S3 backend locking"), web("terraform drift detection")],
        links: [link("Terraform: state", "https://developer.hashicorp.com/terraform/language/state")],
      },
      {
        id: "m11-modules",
        title: "Modules and a CI workflow for infrastructure",
        learn: "Reusable modules, the public registry, fmt and validate, running plan on every PR and apply only on merge, plus tflint and a security scanner (Trivy config).",
        doneWhen: "A pull request shows its Terraform plan and a merge applies it.",
        minutes: 150,
        keywords: ["terraform module", "terraform fmt", "terraform validate", "tflint", "plan on PR", "OIDC to AWS"],
        search: [yt("Terraform modules tutorial"), yt("Terraform GitHub Actions plan apply pull request")],
        links: [link("GitHub Actions OIDC with AWS", "https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services")],
      },
    ],
    project: {
      id: "m11-proj",
      label: "Major project · Your stack as code",
      kind: "major",
      title: "Rebuild the module 10 deployment in Terraform: a VPC module, an EC2 instance with a security group and user-data that runs your container, and an S3 bucket. Remote state, variables, outputs, and a CI plan on each PR.",
      learn: "A reproducible environment you can create and destroy in minutes.",
      doneWhen: "`terraform apply` from a clean checkout gives a working app URL and `terraform destroy` leaves nothing behind.",
      minutes: 300,
      keywords: ["VPC module", "user_data", "terraform destroy", "remote state"],
      search: [web("terraform aws ec2 docker user_data example")],
    },
  },
  {
    id: "m12",
    stage: "s4",
    week: "Week 17",
    title: "Managed containers and serverless",
    goal: "Know when not to run servers at all: managed container platforms and functions.",
    tasks: [
      {
        id: "m12-containers",
        title: "Managed container services",
        learn: "Google Cloud Run, AWS ECS on Fargate or App Runner: you hand over an image and they run, scale and load balance it.",
        doneWhen: "Your Docker image is serving public traffic from a managed service with no server for you to patch.",
        minutes: 150,
        keywords: ["Cloud Run", "ECS Fargate", "App Runner", "scale to zero", "managed containers"],
        search: [yt("Google Cloud Run deploy docker container tutorial"), yt("AWS ECS Fargate tutorial")],
        links: [
          link("Cloud Run quickstart", "https://cloud.google.com/run/docs/quickstarts"),
          link("Google Cloud Free Program", "https://cloud.google.com/free"),
        ],
      },
      {
        id: "m12-functions",
        title: "Serverless functions and events",
        learn: "AWS Lambda or Cloud Functions, cold starts, triggers (HTTP, queue, schedule), and the limits that make some workloads a bad fit.",
        doneWhen: "A Node function triggered by an S3 upload or a schedule runs and writes a log line you can find.",
        minutes: 120,
        keywords: ["AWS Lambda", "cold start", "event trigger", "API Gateway", "serverless", "SQS"],
        search: [yt("AWS Lambda tutorial node.js"), web("serverless vs containers when to use")],
        links: [link("LocalStack (run AWS locally, free tier)", "https://docs.localstack.cloud/")],
      },
      {
        id: "m12-choose",
        title: "Choosing: VMs, containers, Kubernetes or serverless",
        learn: "The trade-offs in cost, control, scaling and team skill. Most apps do not need Kubernetes, so know why you'd pick it.",
        doneWhen: "A decision table for 3 of your own apps is saved in your note with a one-line reason each.",
        minutes: 45,
        keywords: ["trade-offs", "PaaS vs IaaS", "when to use Kubernetes", "vendor lock-in"],
        search: [yt("Do you need Kubernetes? alternatives"), web("PaaS vs IaaS vs serverless")],
      },
    ],
    project: {
      id: "m12-proj",
      label: "Mini project · Ship it with no servers",
      kind: "mini",
      title: "Deploy your container to Cloud Run (or ECS Fargate) from your CI pipeline, with a custom domain or the default URL, and compare its cost and effort with the Terraform EC2 version in a note.",
      learn: "You can now choose between abstraction levels based on evidence, not hype.",
      doneWhen: "Pushing to main deploys to the managed service and your note lists the trade-offs you actually felt.",
      minutes: 180,
      keywords: ["gcloud run deploy", "workload identity", "CI deploy"],
      search: [web("deploy to Cloud Run from GitHub Actions")],
    },
  },

  // ───────────────────────── Stage 5 ─────────────────────────
  {
    id: "m13",
    stage: "s5",
    week: "Weeks 18–19",
    title: "Kubernetes core",
    goal: "Understand what Kubernetes does and run your own app on a local cluster.",
    nodeTip: "Kubernetes is a control loop: you declare 'I want 3 copies of this container', and it keeps making reality match. Think of it as a process manager for a whole fleet.",
    tasks: [
      {
        id: "m13-arch",
        title: "Why Kubernetes and how it is built",
        learn: "The control plane (API server, etcd, scheduler, controllers) and nodes (kubelet, container runtime), and the declarative model.",
        doneWhen: "You can draw the cluster on a napkin and say what happens between `kubectl apply` and a running pod.",
        minutes: 90,
        keywords: ["control plane", "kube-apiserver", "etcd", "scheduler", "kubelet", "declarative", "desired state"],
        search: [yt("Kubernetes explained architecture"), yt("Kubernetes tutorial for beginners full course")],
        links: [link("Kubernetes Basics (official interactive)", "https://kubernetes.io/docs/tutorials/kubernetes-basics/")],
      },
      {
        id: "m13-local",
        title: "A local cluster and kubectl",
        learn: "Install kind (or minikube), kubectl, contexts, get/describe/logs/exec, and reading YAML manifests.",
        doneWhen: "You created a cluster with kind, deployed Nginx and read its logs with kubectl.",
        minutes: 90,
        keywords: ["kind", "minikube", "kubectl", "kubeconfig", "context", "kubectl describe"],
        search: [yt("kind kubernetes local cluster tutorial"), web("kubectl cheat sheet")],
        links: [
          link("kind", "https://kind.sigs.k8s.io/"),
          link("kubectl cheat sheet", "https://kubernetes.io/docs/reference/kubectl/quick-reference/"),
        ],
      },
      {
        id: "m13-workloads",
        title: "Pods, Deployments and ReplicaSets",
        learn: "A pod is one or more containers; a Deployment keeps N replicas and does rolling updates and rollbacks.",
        doneWhen: "You scaled a Deployment to 5, deleted a pod and watched it return, then rolled out a bad image and undid it with `kubectl rollout undo`.",
        minutes: 120,
        keywords: ["Pod", "Deployment", "ReplicaSet", "rolling update", "kubectl rollout undo", "replicas"],
        search: [yt("Kubernetes pods deployments replicasets explained")],
        links: [link("Kubernetes: Deployments", "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/")],
      },
      {
        id: "m13-services",
        title: "Services and Ingress",
        learn: "ClusterIP, NodePort and LoadBalancer Services, label selectors, how pods find each other, and an Ingress controller for HTTP routing.",
        doneWhen: "Two Deployments are reachable on different paths of one host through an Ingress.",
        minutes: 150,
        keywords: ["Service", "ClusterIP", "NodePort", "LoadBalancer", "labels and selectors", "Ingress", "ingress-nginx"],
        search: [yt("Kubernetes services ingress explained"), web("kind ingress nginx setup")],
        links: [link("Kubernetes: Service", "https://kubernetes.io/docs/concepts/services-networking/service/")],
      },
    ],
    project: {
      id: "m13-proj",
      label: "Mini project · Your API on a cluster",
      kind: "mini",
      title: "Run your Node API (image from GHCR) on a kind cluster with 3 replicas, a Service and an Ingress, and perform a rolling update to a new version without dropped requests.",
      learn: "The basic Kubernetes loop on your own code.",
      doneWhen: "A curl loop hits the app during the update and never sees an error.",
      minutes: 210,
      keywords: ["rolling update", "maxUnavailable", "kind ingress", "curl loop"],
      search: [web("kubernetes zero downtime rolling update maxUnavailable")],
    },
  },
  {
    id: "m14",
    stage: "s5",
    week: "Week 20",
    title: "Kubernetes config, storage and health",
    goal: "Make workloads production-shaped: configurable, persistent, self-healing and well-behaved.",
    tasks: [
      {
        id: "m14-config",
        title: "ConfigMaps and Secrets",
        learn: "Inject configuration as env vars or files; Secrets are only base64, not encryption, so know the limits and what to use instead.",
        doneWhen: "Your app reads its Mongo URI from a Secret and its log level from a ConfigMap, with no values baked into the image.",
        minutes: 75,
        keywords: ["ConfigMap", "Secret", "envFrom", "volume mount", "base64 is not encryption"],
        search: [yt("Kubernetes ConfigMaps and Secrets explained")],
      },
      {
        id: "m14-probes",
        title: "Probes, requests and limits",
        learn: "Liveness, readiness and startup probes, CPU and memory requests vs limits, what OOMKilled means, and a Horizontal Pod Autoscaler.",
        doneWhen: "A pod with a failing readiness probe gets no traffic, and you caused and diagnosed an OOMKilled pod on purpose.",
        minutes: 120,
        keywords: ["liveness probe", "readiness probe", "resource requests", "limits", "OOMKilled", "HPA", "metrics-server"],
        search: [yt("Kubernetes probes liveness readiness"), yt("Kubernetes resource requests and limits explained")],
        links: [link("Kubernetes: probes", "https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/")],
      },
      {
        id: "m14-storage",
        title: "Persistent storage and StatefulSets",
        learn: "PersistentVolumes and Claims, StorageClasses, StatefulSets for databases, and why running databases in Kubernetes is a decision, not a default.",
        doneWhen: "A StatefulSet database keeps its data after its pod is deleted.",
        minutes: 120,
        keywords: ["PersistentVolume", "PersistentVolumeClaim", "StorageClass", "StatefulSet", "headless service"],
        search: [yt("Kubernetes persistent volumes StatefulSet tutorial")],
      },
      {
        id: "m14-debug",
        title: "Debugging a broken cluster",
        learn: "CrashLoopBackOff, ImagePullBackOff, Pending pods: use describe, events, logs --previous and exec to find the cause.",
        doneWhen: "You fixed 3 deliberately broken manifests using only kubectl diagnostics.",
        minutes: 90,
        keywords: ["CrashLoopBackOff", "ImagePullBackOff", "Pending", "kubectl events", "logs --previous"],
        search: [yt("Kubernetes troubleshooting CrashLoopBackOff ImagePullBackOff"), web("killercoda kubernetes troubleshooting")],
        links: [link("Killercoda (free browser Kubernetes labs)", "https://killercoda.com/")],
      },
    ],
    project: {
      id: "m14-proj",
      label: "Major project · Full app on Kubernetes",
      kind: "major",
      title: "Deploy the full module 6 stack to kind: API (probes, limits, HPA) + MongoDB StatefulSet with a volume + Ingress, config via ConfigMap and Secret.",
      learn: "Every core object working together.",
      doneWhen: "You delete the API pods and the DB pod; the app recovers by itself and keeps its data.",
      minutes: 300,
      keywords: ["StatefulSet", "HPA", "Ingress", "Secret"],
      search: [web("deploy node mongodb kubernetes statefulset")],
    },
  },
  {
    id: "m15",
    stage: "s5",
    week: "Week 21",
    title: "Helm and Kustomize",
    goal: "Stop copy-pasting YAML: package and vary Kubernetes manifests per environment.",
    tasks: [
      {
        id: "m15-helm",
        title: "Helm: install and write a chart",
        learn: "Charts, releases, values.yaml, templates, helm install/upgrade/rollback; install a public chart, then write your own.",
        doneWhen: "You installed a chart from a public repo, then upgraded and rolled back a release of your own chart.",
        minutes: 150,
        keywords: ["Helm", "chart", "values.yaml", "helm upgrade", "helm rollback", "Go templates"],
        search: [yt("Helm tutorial for beginners create chart"), web("helm chart best practices")],
        links: [link("Helm quickstart", "https://helm.sh/docs/intro/quickstart/")],
      },
      {
        id: "m15-kustomize",
        title: "Kustomize overlays",
        learn: "Base manifests with dev and prod overlays, patches, and image tag overrides, built into `kubectl` with `-k`.",
        doneWhen: "One base produces a 1-replica dev and a 3-replica prod with different hostnames.",
        minutes: 90,
        keywords: ["Kustomize", "overlay", "patch", "kubectl apply -k", "images transformer"],
        search: [yt("Kustomize tutorial overlays base")],
        links: [link("Kustomize docs", "https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/")],
      },
    ],
    project: {
      id: "m15-proj",
      label: "Mini project · Chart for your app",
      kind: "mini",
      title: "Package your app as a Helm chart with values for image tag, replicas, ingress host and resources; install it as `staging` and `prod` releases with different values.",
      learn: "One chart, many environments.",
      doneWhen: "`helm install` on a fresh cluster brings the app up and `helm rollback` undoes a bad value change.",
      minutes: 180,
      keywords: ["helm create", "helm lint", "helm template"],
      search: [web("helm create chart deploy node app")],
    },
  },
  {
    id: "m16",
    stage: "s5",
    week: "Weeks 22–23",
    title: "GitOps with Argo CD",
    goal: "Make Git the single source of truth: the cluster pulls its desired state from a repo and heals itself.",
    nodeTip: "CI builds and tests, then bumps an image tag in a Git repo. A controller inside the cluster notices and applies it. Nobody runs kubectl against prod.",
    tasks: [
      {
        id: "m16-concepts",
        title: "GitOps principles",
        learn: "Declarative state in Git, pull-based sync, drift correction, and how it differs from push-based CD from a pipeline.",
        doneWhen: "You can explain why pull-based deploys are safer, and where secrets fit in.",
        minutes: 60,
        keywords: ["GitOps", "pull vs push deployment", "drift", "reconciliation", "single source of truth"],
        search: [yt("GitOps explained"), web("OpenGitOps principles")],
        links: [link("OpenGitOps", "https://opengitops.dev/")],
      },
      {
        id: "m16-argocd",
        title: "Install Argo CD and sync an app",
        learn: "Install Argo CD on kind, create an Application pointing at a repo path, sync, auto-sync with self-heal and prune, and the UI.",
        doneWhen: "You edited the replica count in Git and the cluster changed without you touching kubectl; a manual change was reverted by self-heal.",
        minutes: 150,
        keywords: ["Argo CD", "Application", "sync policy", "self-heal", "prune", "app of apps"],
        search: [yt("Argo CD tutorial for beginners"), web("Argo CD getting started")],
        links: [
          link("Argo CD: Getting started", "https://argo-cd.readthedocs.io/en/stable/getting_started/"),
          link("Flux (the alternative)", "https://fluxcd.io/flux/get-started/"),
        ],
      },
      {
        id: "m16-secrets",
        title: "Secrets in GitOps",
        learn: "You cannot commit plain Secrets. Options: Sealed Secrets, SOPS with age, or External Secrets Operator pulling from a vault.",
        doneWhen: "An encrypted secret lives in Git and is decrypted only inside the cluster.",
        minutes: 120,
        keywords: ["Sealed Secrets", "SOPS", "age", "External Secrets Operator", "secret encryption"],
        search: [yt("Sealed Secrets kubernetes tutorial"), yt("SOPS age encrypt secrets git")],
      },
    ],
    project: {
      id: "m16-proj",
      label: "Major project · Commit to deploy",
      kind: "major",
      title: "Full GitOps loop: CI builds an image, then opens a commit that bumps the tag in a separate manifests repo; Argo CD syncs it to a kind cluster. Secrets are encrypted in Git.",
      learn: "The modern deployment pipeline end to end.",
      doneWhen: "A code change on GitHub reaches the running cluster with no manual step, and `git revert` rolls it back.",
      minutes: 360,
      keywords: ["image tag bump", "manifests repo", "Argo CD", "Sealed Secrets"],
      search: [web("github actions update image tag gitops repo argo cd")],
    },
  },

  // ───────────────────────── Stage 6 ─────────────────────────
  {
    id: "m17",
    stage: "s6",
    week: "Weeks 24–25",
    title: "Monitoring, logging and tracing",
    goal: "See inside running systems: know it's broken before users tell you.",
    nodeTip: "console.log is not observability. You need metrics (numbers over time), logs (events) and traces (one request's journey). Emit JSON logs from Node with pino.",
    tasks: [
      {
        id: "m17-concepts",
        title: "Metrics, logs and traces; the golden signals",
        learn: "The three pillars, monitoring vs observability, and the four golden signals: latency, traffic, errors, saturation.",
        doneWhen: "You listed the golden signals for your own API and what would show each.",
        minutes: 60,
        keywords: ["observability", "golden signals", "RED method", "USE method", "metrics logs traces"],
        search: [yt("observability explained metrics logs traces"), web("Google SRE four golden signals")],
        links: [link("SRE book: Monitoring Distributed Systems", "https://sre.google/sre-book/monitoring-distributed-systems/")],
      },
      {
        id: "m17-prom",
        title: "Prometheus and instrumenting a Node app",
        learn: "Pull-based scraping, counters, gauges and histograms, PromQL basics (rate, sum by), and exposing /metrics with prom-client.",
        doneWhen: "Prometheus scrapes your Node API and a PromQL query shows requests per second and p95 latency.",
        minutes: 150,
        keywords: ["Prometheus", "PromQL", "prom-client", "counter", "histogram", "rate()", "scrape"],
        search: [yt("Prometheus tutorial for beginners"), yt("prom-client node.js metrics express")],
        links: [link("Prometheus overview", "https://prometheus.io/docs/introduction/overview/")],
      },
      {
        id: "m17-grafana",
        title: "Grafana dashboards and alerting",
        learn: "Data sources, panels, variables, dashboards as code, and alert rules with Alertmanager that page on symptoms, not causes.",
        doneWhen: "A dashboard shows your four signals and an alert fires (to Discord or email) when the error rate passes 5%.",
        minutes: 150,
        keywords: ["Grafana", "dashboard", "Alertmanager", "alert rule", "kube-prometheus-stack", "symptom-based alerting"],
        search: [yt("Grafana dashboard tutorial Prometheus"), yt("Alertmanager alerts tutorial")],
        links: [link("Grafana tutorials", "https://grafana.com/tutorials/")],
      },
      {
        id: "m17-logs",
        title: "Centralised logging with Loki",
        learn: "Structured JSON logs, shipping with Promtail or Alloy, querying with LogQL, and linking logs to the metric spike.",
        doneWhen: "You found the exact error lines behind a spike by clicking from a Grafana panel into the logs.",
        minutes: 120,
        keywords: ["Loki", "LogQL", "Promtail", "structured logging", "pino", "log aggregation"],
        search: [yt("Grafana Loki tutorial logs"), web("pino structured logging node")],
        links: [link("Loki docs", "https://grafana.com/docs/loki/latest/")],
      },
      {
        id: "m17-otel",
        title: "Distributed tracing with OpenTelemetry",
        learn: "Spans, trace context, auto-instrumenting Node with the OpenTelemetry SDK, and viewing traces in Jaeger or Grafana Tempo.",
        doneWhen: "A trace across two services shows which one made the request slow.",
        minutes: 120,
        keywords: ["OpenTelemetry", "trace", "span", "Jaeger", "Tempo", "context propagation"],
        search: [yt("OpenTelemetry node.js tutorial tracing"), web("OpenTelemetry JavaScript getting started")],
        links: [link("OpenTelemetry docs", "https://opentelemetry.io/docs/")],
      },
    ],
    project: {
      id: "m17-proj",
      label: "Major project · Observability stack",
      kind: "major",
      title: "Install kube-prometheus-stack and Loki on your kind cluster, instrument your API with metrics, JSON logs and traces, build one dashboard, and set 2 alerts.",
      learn: "The setup most teams use, running on your laptop.",
      doneWhen: "You break the app on purpose and the alert, dashboard and logs lead you to the cause in under 5 minutes.",
      minutes: 360,
      keywords: ["kube-prometheus-stack", "Loki", "dashboard", "alert"],
      search: [web("kube-prometheus-stack helm kind install"), web("grafana loki helm install kind")],
    },
  },
  {
    id: "m18",
    stage: "s6",
    week: "Week 26",
    title: "Site reliability and incident response",
    goal: "Think about reliability as a number you choose, and handle failures calmly and learn from them.",
    tasks: [
      {
        id: "m18-slo",
        title: "SLIs, SLOs and error budgets",
        learn: "Choose a service level indicator, set an objective (99.9% means 43 minutes of downtime a month), and use the error budget to decide between shipping and fixing.",
        doneWhen: "You wrote an SLO for your API and computed its monthly error budget.",
        minutes: 75,
        keywords: ["SLI", "SLO", "SLA", "error budget", "nines of availability", "burn rate"],
        search: [yt("SLI SLO SLA error budget explained")],
        links: [link("Google SRE book (free)", "https://sre.google/sre-book/table-of-contents/")],
      },
      {
        id: "m18-incident",
        title: "On-call and incident response",
        learn: "Severity levels, incident commander role, communicating status, mitigate before you root-cause, and runbooks.",
        doneWhen: "You wrote a one-page runbook for 'API is returning 500s' that someone else could follow at 3 a.m.",
        minutes: 75,
        keywords: ["incident response", "on-call", "runbook", "severity", "incident commander", "mitigation"],
        search: [yt("incident response process SRE on call")],
        links: [link("PagerDuty incident response docs (free)", "https://response.pagerduty.com/")],
      },
      {
        id: "m18-postmortem",
        title: "Blameless postmortems",
        learn: "Timeline, impact, root causes and contributing factors, what went well, and action items with owners. Blame people and nothing improves.",
        doneWhen: "You wrote a postmortem for a failure from one of your earlier projects.",
        minutes: 60,
        keywords: ["postmortem", "blameless", "root cause analysis", "5 whys", "action items"],
        search: [web("blameless postmortem template")],
        links: [link("SRE book: Postmortem culture", "https://sre.google/sre-book/postmortem-culture/")],
      },
      {
        id: "m18-chaos",
        title: "Resilience and chaos testing",
        learn: "Timeouts, retries with backoff, circuit breakers and graceful degradation; then break things on purpose, starting small.",
        doneWhen: "You killed pods and added latency in your cluster and your app stayed within its SLO.",
        minutes: 120,
        keywords: ["chaos engineering", "circuit breaker", "retry with backoff", "Chaos Mesh", "kubectl delete pod", "graceful degradation"],
        search: [yt("chaos engineering explained"), yt("Chaos Mesh kubernetes tutorial")],
        links: [link("Principles of Chaos Engineering", "https://principlesofchaos.org/")],
      },
    ],
    project: {
      id: "m18-proj",
      label: "Mini project · Game day",
      kind: "mini",
      title: "Run a game day on your stack: define an SLO, inject 3 failures (pod kill, DB down, slow dependency), follow your runbook, and write a blameless postmortem.",
      learn: "Practising failure so real incidents feel familiar.",
      doneWhen: "A postmortem with a timeline and 3 owned action items is saved in your repo.",
      minutes: 180,
      keywords: ["game day", "runbook", "postmortem"],
      search: [web("game day chaos engineering exercise how to run")],
    },
  },
  {
    id: "m19",
    stage: "s6",
    week: "Weeks 27–28",
    title: "DevSecOps and supply-chain security",
    goal: "Build security into the pipeline: keep secrets out of Git, find vulnerabilities early, and trust what you ship.",
    tasks: [
      {
        id: "m19-secrets",
        title: "Secrets management",
        learn: "Why .env files and environment variables leak, secret scanning (gitleaks), rotating credentials, and a vault (HashiCorp Vault or a cloud secret manager).",
        doneWhen: "gitleaks runs in CI and fails the build on a planted fake key; your app reads a secret from a manager at runtime.",
        minutes: 120,
        keywords: ["gitleaks", "HashiCorp Vault", "AWS Secrets Manager", "secret rotation", "pre-commit hook"],
        search: [yt("HashiCorp Vault tutorial for beginners"), web("gitleaks github action")],
        links: [link("Vault tutorials", "https://developer.hashicorp.com/vault/tutorials")],
      },
      {
        id: "m19-scan",
        title: "Scanning code, dependencies and images",
        learn: "SAST, dependency scanning (npm audit, Dependabot), image scanning with Trivy, and config scanning for Terraform and Kubernetes. Triage by real risk.",
        doneWhen: "Your pipeline gates on critical findings, and you can explain why one 'critical' was not exploitable for you.",
        minutes: 120,
        keywords: ["SAST", "Dependabot", "npm audit", "Trivy", "CodeQL", "CVE", "false positive"],
        search: [yt("DevSecOps pipeline tutorial"), web("GitHub Dependabot CodeQL setup")],
        links: [link("OWASP Top 10", "https://owasp.org/www-project-top-ten/")],
      },
      {
        id: "m19-supply",
        title: "Software supply chain: SBOMs and signing",
        learn: "Generate an SBOM, sign images with cosign (keyless), verify before deploy, and the SLSA levels in plain words.",
        doneWhen: "CI signs your image and the cluster (or a script) refuses an unsigned one.",
        minutes: 120,
        keywords: ["SBOM", "cosign", "Sigstore", "SLSA", "image signing", "Syft"],
        search: [yt("cosign sigstore sign container image tutorial"), web("SLSA framework explained")],
        links: [
          link("Sigstore docs", "https://docs.sigstore.dev/"),
          link("SLSA", "https://slsa.dev/"),
        ],
      },
      {
        id: "m19-k8s",
        title: "Kubernetes and cloud hardening",
        learn: "RBAC, Pod Security Standards, NetworkPolicies (default deny), policy as code (Kyverno or OPA Gatekeeper), and least-privilege IAM.",
        doneWhen: "A policy blocks a pod that runs as root, and a NetworkPolicy stops one pod reaching another.",
        minutes: 150,
        keywords: ["RBAC", "NetworkPolicy", "Pod Security Standards", "Kyverno", "OPA Gatekeeper", "service account"],
        search: [yt("Kubernetes security RBAC NetworkPolicy tutorial"), yt("Kyverno policy tutorial")],
        links: [link("Kubernetes: Security", "https://kubernetes.io/docs/concepts/security/")],
      },
    ],
    project: {
      id: "m19-proj",
      label: "Major project · Secure the pipeline",
      kind: "major",
      title: "Add to your pipeline: gitleaks, dependency and image scanning, an SBOM, cosign signing, and a Kyverno policy that only admits signed images from your registry that run as non-root.",
      learn: "Shift-left security, enforced by machines instead of hope.",
      doneWhen: "A root-running or unsigned image is rejected by the cluster, and the failing check says why.",
      minutes: 360,
      keywords: ["cosign verify", "Kyverno verifyImages", "SBOM", "gitleaks"],
      search: [web("kyverno verify images cosign policy")],
    },
  },

  // ───────────────────────── Stage 7 ─────────────────────────
  {
    id: "m20",
    stage: "s7",
    week: "Weeks 29–30",
    title: "Become the DevOps engineer you want to be",
    goal: "Turn what you built into proof, and decide what to go deeper on next.",
    tasks: [
      {
        id: "m20-docs",
        title: "Document and diagram what you built",
        learn: "A README per project with an architecture diagram, how to run it, and the decisions you made and why. Write as if for a new teammate.",
        doneWhen: "Your three best projects each have a README with a diagram and a one-command quickstart.",
        minutes: 180,
        keywords: ["architecture diagram", "README", "ADR", "runbook", "Mermaid"],
        search: [web("architecture decision record template"), web("mermaid diagrams github readme")],
        links: [link("roadmap.sh DevOps roadmap (see what's next)", "https://roadmap.sh/devops")],
      },
      {
        id: "m20-certs",
        title: "Pick a certification, or skip it on purpose",
        learn: "Certs can open doors: AWS Cloud Practitioner or Solutions Architect Associate, CKA for Kubernetes, Terraform Associate. Choose by the jobs you want.",
        doneWhen: "You chose one cert (or none) with a reason and a target date in your note.",
        minutes: 45,
        keywords: ["AWS Solutions Architect Associate", "CKA", "Terraform Associate", "CKAD"],
        search: [web("DevOps certifications worth it 2026"), web("CKA exam curriculum")],
        links: [link("CKA exam (Linux Foundation)", "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/")],
      },
      {
        id: "m20-jobs",
        title: "Read 10 DevOps and platform job posts",
        learn: "List the skills that keep showing up and compare with your gaps. Common next steps: service mesh, Crossplane, platform engineering, cost optimisation (FinOps), eBPF.",
        doneWhen: "A ranked list of 3 skills to learn next is saved in your note.",
        minutes: 60,
        keywords: ["DevOps engineer", "platform engineer", "SRE", "FinOps", "service mesh", "internal developer platform"],
        search: [web("DevOps engineer job description skills"), web("platform engineering vs DevOps")],
      },
    ],
    project: {
      id: "m20-proj",
      label: "Capstone · DevOps portfolio",
      kind: "major",
      title: "One repo or page that tells the story of your platform: an app, a pipeline, Terraform, Kubernetes with GitOps, observability and security, with diagrams, links and what broke.",
      learn: "Everything above, in one link.",
      doneWhen: "You can send one link to a stranger and it shows how you ship, run and secure software.",
      minutes: 300,
      keywords: ["DevOps portfolio", "platform engineering", "case study"],
      search: [web("DevOps engineer portfolio project ideas")],
    },
  },
];

function build(m: ModuleIn, index: number): ModuleDoc {
  const tasks: Step[] = m.tasks.map((t) => ({ ...t, links: t.links ?? [] }));
  const project: Project = {
    ...m.project,
    kind: m.project.kind ?? "mini",
    links: m.project.links ?? [],
  };
  return {
    _id: m.id,
    order: index + 1,
    stage: m.stage,
    week: m.week,
    title: m.title,
    goal: m.goal,
    ...(m.nodeTip && { nodeTip: m.nodeTip }),
    tasks,
    project,
    itemIds: [...tasks.map((t) => t.id), project.id],
  };
}

export const MODULES: ModuleDoc[] = MODULES_IN.map(build);
