// The roadmap content. This file is only the SOURCE for the database:
// `pnpm seed` copies it into MongoDB, and the app reads it from there.
//
// Keep each `id` the same when you reword a step. Progress and notes are saved
// by id. Edit this file, then run `pnpm seed` again to update the database.
//
// This file must not import anything except types: the seed script runs it
// directly with Node.
import type { Link, ModuleDoc, Project, Search, StageDoc, Step } from "./roadmap-types";

const yt = (q: string): Search => ({ q, on: "yt" });
const web = (q: string): Search => ({ q, on: "web" });
const link = (label: string, url: string): Link => ({ label, url });

type StepIn = Omit<Step, "links"> & { links?: Link[] };
type ProjectIn = StepIn & { label: string; kind?: "mini" | "major" };
type ModuleIn = {
  id: string;
  stage: string;
  week: string;
  title: string;
  goal: string;
  nodeTip?: string;
  tasks: StepIn[];
  project: ProjectIn;
};

export const ROADMAP_VERSION = 1;

export const STAGES: StageDoc[] = [
  { _id: "s1", order: 1, title: "Reposition", blurb: "Rewrite the resume, profiles and portfolio, then apply locally this week. Week 1." },
  { _id: "s2", order: 2, title: "Backend depth", blurb: "TypeScript/Node internals, NestJS, PostgreSQL, testing, security and Redis. Weeks 2–5." },
  { _id: "s3", order: 3, title: "Flagship project", blurb: "Design, build and ship the knowledge-sharing platform with AI summarisation. Weeks 6–10." },
  { _id: "s4", order: 4, title: "Ship like a professional", blurb: "Docker, CI/CD, cloud deploy, observability and clean git habits. Weeks 9–12." },
  { _id: "s5", order: 5, title: "Interview readiness", blurb: "DSA by pattern, system design, take-homes, behavioural stories, mock interviews. Weeks 11–14." },
  { _id: "s6", order: 6, title: "Public proof and English", blurb: "Open source PRs, technical writing, LinkedIn and daily spoken English. Weeks 3–16, ongoing." },
  { _id: "s7", order: 7, title: "International applications", blurb: "Platforms, volume, outreach, market routing and the practical setup for foreign income. Weeks 6–16+." },
];

const MODULES_IN: ModuleIn[] = [
  // ───────────────────────── Stage 1 ─────────────────────────
  {
    id: "c01",
    stage: "s1",
    week: "Week 1",
    title: "Rewrite the resume, GitHub and LinkedIn",
    goal: "Make the existing 2 years of work legible to an international recruiter in under 10 seconds.",
    nodeTip: "You already have the material (JWT/RBAC, WebSocket/STOMP, i18n, maker-checker, Next.js/Express/Prisma). This week is about presentation, not new skills.",
    tasks: [
      {
        id: "c01-resume",
        title: "Rewrite the resume headline and bullets",
        learn: "New headline: \"Full-Stack Engineer (TypeScript · Node.js/NestJS · React/Next.js · PostgreSQL)\". One page. Move the E-China, payment-gateway and LLM work above education. Every bullet: action + technology + result with a number.",
        doneWhen: "The resume is one page, has the new headline, every bullet has a number, the \"COURCES\" typo is fixed, and SSC/HSC and home address are removed.",
        minutes: 120,
        keywords: ["resume headline", "action technology result", "one-page resume", "ATS resume"],
        search: [web("full stack developer resume bullet points with metrics examples"), web("one page tech resume template")],
      },
      {
        id: "c01-github",
        title: "Clean up GitHub: pin 3–4 repos with real READMEs",
        learn: "Pin only your best 3–4 repos. Each README needs: what it does, a screenshot, a live link, the stack, how to run it, and what you'd improve. Archive or delete tutorial clones.",
        doneWhen: "3–4 pinned repos each have a README with a screenshot and a live link; everything else is archived or deleted.",
        minutes: 120,
        keywords: ["GitHub pinned repositories", "README screenshot", "archive repository"],
        search: [web("how to write a great GitHub README for a portfolio project"), web("GitHub pin repositories profile")],
        links: [link("GitHub Docs: pinning repositories", "https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile")],
      },
      {
        id: "c01-linkedin",
        title: "Rewrite LinkedIn and turn on Open to Work",
        learn: "Same headline as the resume. About section in 4 lines: what you build, your stack, what you're looking for, your time zone and availability. Turn on \"Open to work\" for remote roles.",
        doneWhen: "LinkedIn headline matches the resume, the About section is 4 lines, and Open to Work is on for remote.",
        minutes: 60,
        keywords: ["LinkedIn About section", "LinkedIn Open to Work", "LinkedIn headline"],
        search: [web("how to write a LinkedIn about section for developers"), web("LinkedIn open to work remote roles")],
      },
    ],
    project: {
      id: "c01-proj",
      label: "Mini project · Deploy your portfolio site",
      kind: "mini",
      title: "Build and deploy a one-page Next.js portfolio: pinned projects, resume PDF, contact. Keep the design plain; correctness matters more than visuals.",
      learn: "A live link you can put on the resume and LinkedIn today.",
      doneWhen: "The portfolio site is live at a real URL and linked from both the resume and LinkedIn.",
      minutes: 180,
      keywords: ["Next.js portfolio site", "deploy Vercel", "resume PDF link"],
      search: [web("developer portfolio website Next.js example"), web("deploy Next.js app to Vercel")],
      links: [link("Vercel: deploying Next.js", "https://vercel.com/docs/frameworks/nextjs")],
    },
  },
  {
    id: "c02",
    stage: "s1",
    week: "Week 1",
    title: "Apply locally, now",
    goal: "Do not wait to feel ready. Start adding to your years of experience this week while the rest of the roadmap runs alongside it.",
    tasks: [
      {
        id: "c02-tracker",
        title: "Set up one application tracker",
        learn: "One sheet: company, role, date applied, contact, status, follow-up date. You will reuse this for international applications later.",
        doneWhen: "The tracker sheet exists with those 6 columns and at least one row.",
        minutes: 30,
        keywords: ["job application tracker spreadsheet"],
        search: [web("job application tracker spreadsheet template")],
      },
    ],
    project: {
      id: "c02-proj",
      label: "Mini project · First 10 local applications",
      kind: "mini",
      title: "Send the 10 best-fit rows from your Bangladesh / remote-BD job list this week. Log each one in the tracker.",
      learn: "Years of experience only close by working. This can't wait for the rest of the plan.",
      doneWhen: "10 applications are sent and logged, each with a one-line note on why it's a fit.",
      minutes: 180,
      keywords: ["job application tracking", "local tech jobs Bangladesh"],
      search: [web("remote jobs Bangladesh developer")],
    },
  },

  // ───────────────────────── Stage 2 ─────────────────────────
  {
    id: "c03",
    stage: "s2",
    week: "Week 2",
    title: "JavaScript/Node internals and TypeScript",
    goal: "Know what's actually happening under async code and under the type system, not just how to write it.",
    nodeTip: "You already use Node daily. This week is about the parts that only show up as bugs: backpressure, blocking the event loop, and types that lie.",
    tasks: [
      {
        id: "c03-eventloop",
        title: "Event loop phases, microtasks vs macrotasks",
        learn: "Timers, pending callbacks, poll, check, close callbacks; where Promises/microtasks run relative to setTimeout/setImmediate.",
        doneWhen: "You can predict the console.log order of a script mixing setTimeout, setImmediate, process.nextTick and a Promise.",
        minutes: 90,
        keywords: ["event loop", "microtask queue", "macrotask", "process.nextTick", "setImmediate"],
        search: [yt("Node.js event loop explained in depth"), web("Node.js event loop phases documentation")],
        links: [link("Node.js: The Event Loop", "https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick")],
      },
      {
        id: "c03-streams",
        title: "Streams and backpressure",
        learn: "Readable/Writable/Transform streams, piping, and why backpressure matters when processing large files or responses.",
        doneWhen: "You can explain why `.pipe()` handles backpressure and a naive read-all-then-write loop doesn't.",
        minutes: 90,
        keywords: ["Node.js streams", "backpressure", "Readable Writable Transform", "pipeline"],
        search: [web("Node.js streams backpressure explained"), yt("Node.js streams crash course")],
        links: [link("Node.js: Stream docs", "https://nodejs.org/api/stream.html")],
      },
      {
        id: "c03-workers",
        title: "Why Node is bad at CPU work, and worker_threads",
        learn: "Single-threaded JS execution, blocking the event loop with CPU-heavy code, and when worker_threads (vs child_process, vs a queue) actually fixes it.",
        doneWhen: "You can name one CPU-bound task you'd move to a worker thread and why.",
        minutes: 60,
        keywords: ["worker_threads", "blocking the event loop", "CPU-bound", "child_process"],
        search: [web("Node.js worker threads vs child process vs cluster")],
        links: [link("Node.js: Worker threads", "https://nodejs.org/api/worker_threads.html")],
      },
      {
        id: "c03-ts",
        title: "TypeScript: generics, utility types, narrowing, strict mode",
        learn: "Generics, Partial/Pick/Omit/Record, discriminated unions and narrowing, and why strict mode catches real bugs.",
        doneWhen: "You wrote a generic function and used at least two utility types without looking up their shape.",
        minutes: 150,
        keywords: ["TypeScript generics", "utility types", "discriminated union", "type narrowing", "strict mode"],
        search: [web("TypeScript handbook generics"), yt("TypeScript utility types explained")],
        links: [link("TypeScript Handbook", "https://www.typescriptlang.org/docs/handbook/intro.html")],
      },
    ],
    project: {
      id: "c03-proj",
      label: "Mini project · Stream-process a large file",
      kind: "mini",
      title: "Build a small CLI or service, fully typed, that reads a large file (CSV/log) with streams and transforms it without loading it all into memory.",
      learn: "Proves you can reason about memory and backpressure, not just about syntax.",
      doneWhen: "The tool processes a file larger than available comfortable memory without ballooning RSS, and TypeScript is strict with no `any`.",
      minutes: 180,
      keywords: ["stream processing CLI", "large file parsing Node.js", "strict TypeScript"],
      search: [web("Node.js stream large CSV file processing example")],
    },
  },
  {
    id: "c04",
    stage: "s2",
    week: "Week 3",
    title: "NestJS and API design",
    goal: "Own the server side the way you already own the client side: real architecture, not just route handlers.",
    nodeTip: "NestJS is Angular's DI and module system, server-side. Your Angular background (providers, guards-as-you-know-them) transfers directly.",
    tasks: [
      {
        id: "c04-core",
        title: "Modules, providers, dependency injection",
        learn: "How Nest wires modules, providers and controllers together, and why DI makes testing easier.",
        doneWhen: "You can explain what `@Injectable()` and a module's `providers` array do without looking it up.",
        minutes: 90,
        keywords: ["NestJS modules", "NestJS providers", "dependency injection", "@Injectable"],
        search: [web("NestJS fundamentals modules providers"), yt("NestJS crash course")],
        links: [link("NestJS Docs: Modules", "https://docs.nestjs.com/modules"), link("NestJS Docs: Providers", "https://docs.nestjs.com/providers")],
      },
      {
        id: "c04-pipeline",
        title: "Guards, pipes, interceptors",
        learn: "Request lifecycle: guards for auth, pipes for validation/transformation, interceptors for cross-cutting logic (logging, response shaping).",
        doneWhen: "You built a custom guard and a validation pipe and can say where each runs in the request lifecycle.",
        minutes: 120,
        keywords: ["NestJS guards", "NestJS pipes", "NestJS interceptors", "class-validator"],
        search: [web("NestJS guards pipes interceptors explained"), yt("NestJS validation pipe class-validator tutorial")],
        links: [link("NestJS Docs: Guards", "https://docs.nestjs.com/guards"), link("NestJS Docs: Pipes", "https://docs.nestjs.com/pipes")],
      },
      {
        id: "c04-rest",
        title: "REST conventions: pagination, idempotency, versioning, error format",
        learn: "Consistent pagination, idempotency keys for unsafe retries, URL/header versioning, and one error response shape across the whole API.",
        doneWhen: "You can describe your API's pagination shape and error shape in one sentence each.",
        minutes: 90,
        keywords: ["REST API pagination", "idempotency key", "API versioning", "error response format"],
        search: [web("REST API design best practices pagination idempotency versioning")],
      },
      {
        id: "c04-openapi",
        title: "OpenAPI/Swagger docs",
        learn: "Generate interactive API docs straight from your NestJS decorators.",
        doneWhen: "A `/api` Swagger page shows every route with request/response shapes.",
        minutes: 60,
        keywords: ["OpenAPI", "Swagger", "@nestjs/swagger"],
        search: [web("NestJS OpenAPI Swagger setup")],
        links: [link("NestJS Docs: OpenAPI (Swagger)", "https://docs.nestjs.com/openapi/introduction")],
      },
    ],
    project: {
      id: "c04-proj",
      label: "Major project · NestJS REST API with auth and RBAC",
      kind: "major",
      title: "Build a NestJS REST API with request validation, Swagger docs, JWT auth with refresh tokens, and RBAC. You already built RBAC on the Angular front end at Celloscope — now own the server side.",
      learn: "This becomes the base you extend in weeks 4 and 5.",
      doneWhen: "A fresh clone, with its README steps, runs the API, and Swagger shows auth, refresh and role-gated routes working.",
      minutes: 300,
      keywords: ["NestJS JWT refresh tokens", "RBAC NestJS", "NestJS Swagger"],
      search: [yt("NestJS JWT authentication refresh token tutorial"), web("NestJS role based access control guard")],
    },
  },
  {
    id: "c05",
    stage: "s2",
    week: "Week 4",
    title: "PostgreSQL",
    goal: "Go from \"it works\" to \"I know why it's fast or slow.\"",
    nodeTip: "Prisma (which you've used) hides a lot of this. This week is about seeing what's underneath it.",
    tasks: [
      {
        id: "c05-indexes",
        title: "Indexes and when they are not used",
        learn: "B-tree indexes, composite indexes, and the common reasons Postgres skips an index (function calls on the column, wrong leading column, low selectivity).",
        doneWhen: "You can give two reasons a query might ignore an existing index.",
        minutes: 90,
        keywords: ["PostgreSQL indexes", "composite index", "index selectivity"],
        search: [web("PostgreSQL why is my index not being used"), yt("PostgreSQL indexing explained")],
        links: [link("PostgreSQL Docs: Indexes", "https://www.postgresql.org/docs/current/indexes.html")],
      },
      {
        id: "c05-explain",
        title: "Reading EXPLAIN ANALYZE",
        learn: "Seq scan vs index scan, estimated vs actual rows, where the time actually goes in a query plan.",
        doneWhen: "You read an EXPLAIN ANALYZE output and correctly named the slowest node.",
        minutes: 90,
        keywords: ["EXPLAIN ANALYZE", "query plan", "seq scan vs index scan"],
        search: [web("how to read PostgreSQL EXPLAIN ANALYZE output"), yt("PostgreSQL EXPLAIN ANALYZE tutorial")],
        links: [link("PostgreSQL Docs: Using EXPLAIN", "https://www.postgresql.org/docs/current/using-explain.html")],
      },
      {
        id: "c05-tx",
        title: "Transactions and isolation levels",
        learn: "ACID, the default Read Committed level, and what changes under Repeatable Read/Serializable (and why that matters for double-booking style bugs).",
        doneWhen: "You can describe a race condition that Read Committed allows but Serializable prevents.",
        minutes: 90,
        keywords: ["transaction isolation levels", "read committed", "serializable", "ACID"],
        search: [web("PostgreSQL transaction isolation levels explained")],
        links: [link("PostgreSQL Docs: Transaction Isolation", "https://www.postgresql.org/docs/current/transaction-iso.html")],
      },
      {
        id: "c05-n1",
        title: "N+1 queries and migrations",
        learn: "Spot an N+1 in an ORM, fix it with a join/include, and write a reversible migration.",
        doneWhen: "You fixed one N+1 in your own code and can show the before/after query count.",
        minutes: 90,
        keywords: ["N+1 query problem", "database migrations", "ORM eager loading"],
        search: [web("N+1 query problem explained with fix")],
      },
      {
        id: "c05-mongo",
        title: "When to choose MongoDB instead",
        learn: "Document vs relational trade-offs: flexible schema, nested data, horizontal scale vs joins, transactions and strong consistency.",
        doneWhen: "You can give one scenario where you'd pick MongoDB over Postgres and one where you wouldn't.",
        minutes: 45,
        keywords: ["SQL vs NoSQL", "MongoDB vs PostgreSQL"],
        search: [web("when to use PostgreSQL vs MongoDB")],
      },
    ],
    project: {
      id: "c05-proj",
      label: "Mini project · Find and fix a slow query",
      kind: "mini",
      title: "Add a realistic schema and seed data to the week-3 API. Find one genuinely slow query, fix it (index, rewrite, or both), and write down the before/after EXPLAIN ANALYZE numbers.",
      learn: "Real performance work, with evidence you can show in an interview.",
      doneWhen: "A short note has the before/after query time and the EXPLAIN plan for both.",
      minutes: 180,
      keywords: ["slow query optimization", "EXPLAIN ANALYZE before after"],
      search: [web("optimize slow PostgreSQL query real example")],
    },
  },
  {
    id: "c06",
    stage: "s2",
    week: "Week 5",
    title: "Testing, security, Redis",
    goal: "Ship code you can trust and that isn't trivially exploitable, with caching that doesn't go stale silently.",
    tasks: [
      {
        id: "c06-testing",
        title: "Unit vs integration vs e2e, what to mock",
        learn: "What each test level actually proves, and the rule of thumb for mocking: mock what you don't own, test what you do.",
        doneWhen: "You can say, for one function, which test level you'd write for it and why.",
        minutes: 60,
        keywords: ["unit test", "integration test", "e2e test", "mocking strategy"],
        search: [web("unit vs integration vs e2e testing what to mock")],
        links: [link("Jest Docs: Getting Started", "https://jestjs.io/docs/getting-started")],
      },
      {
        id: "c06-owasp",
        title: "OWASP top risks for APIs, rate limiting, secrets",
        learn: "Broken auth, broken object-level authorization, excessive data exposure, mass assignment; rate limiting and secrets handling.",
        doneWhen: "You can name 3 OWASP API risks and point to where your week-3 API is or isn't protected against each.",
        minutes: 90,
        keywords: ["OWASP API Security Top 10", "broken object level authorization", "rate limiting", "secrets management"],
        search: [web("OWASP API Security Top 10 explained")],
        links: [link("OWASP API Security Top 10", "https://owasp.org/www-project-api-security/")],
      },
      {
        id: "c06-redis",
        title: "Redis caching patterns and invalidation",
        learn: "Cache-aside, TTLs, and the hard part: invalidating a cache correctly when the underlying data changes.",
        doneWhen: "You can explain cache-aside in one sentence and name one invalidation bug it's easy to introduce.",
        minutes: 90,
        keywords: ["Redis caching", "cache-aside pattern", "cache invalidation", "TTL"],
        search: [web("Redis caching patterns cache aside invalidation")],
        links: [link("Redis Docs", "https://redis.io/docs/latest/")],
      },
    ],
    project: {
      id: "c06-proj",
      label: "Major project · Tests, caching, rate limiting, deployed",
      kind: "major",
      title: "Add Jest unit tests and Supertest e2e tests to the week-3/4 API, to around 70% coverage. Add Redis caching and rate limiting. Deploy it somewhere reachable by a URL.",
      learn: "Closes Phase B: a backend you can defend line by line in an interview.",
      doneWhen: "Coverage report shows ~70%, a cached route and a rate-limited route both demonstrably work, and the API is live.",
      minutes: 300,
      keywords: ["Jest Supertest e2e", "test coverage", "Redis rate limiting NestJS"],
      search: [web("NestJS Jest Supertest e2e testing tutorial"), web("NestJS Redis rate limiting")],
      links: [link("Supertest", "https://github.com/ladjs/supertest")],
    },
  },

  // ───────────────────────── Stage 3 ─────────────────────────
  {
    id: "c07",
    stage: "s3",
    week: "Week 6",
    title: "Design the flagship before writing code",
    goal: "A one-page design doc for the knowledge-sharing platform with AI summarisation, written before any code. The doc itself is interview material.",
    tasks: [
      {
        id: "c07-doc",
        title: "Write the one-page design doc",
        learn: "Problem, users, data model, API, architecture diagram, and explicitly what is out of scope.",
        doneWhen: "The doc fits one page and has all six sections, including an explicit out-of-scope list.",
        minutes: 150,
        keywords: ["system design document", "architecture diagram", "scope definition"],
        search: [web("one page software design document template"), web("system design document example")],
      },
      {
        id: "c07-stack",
        title: "Lock the stack: GraphQL, Redis, BullMQ, PostgreSQL, Elasticsearch, LLM API",
        learn: "Decide where each piece sits: GraphQL for the API, BullMQ for background summarisation jobs, Elasticsearch for search, Redis for cache and queue backing.",
        doneWhen: "A short architecture diagram shows all 6 pieces and how data flows between them.",
        minutes: 90,
        keywords: ["GraphQL API", "BullMQ job queue", "Elasticsearch search", "architecture diagram"],
        search: [web("GraphQL BullMQ Elasticsearch architecture example")],
        links: [link("GraphQL: Learn", "https://graphql.org/learn/"), link("BullMQ Docs", "https://docs.bullmq.io/"), link("Elasticsearch Guide", "https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html")],
      },
    ],
    project: {
      id: "c07-proj",
      label: "Mini project · Publish the design doc",
      kind: "mini",
      title: "Put the design doc in the repo's README or docs folder before writing the first line of application code.",
      learn: "Future-you (and an interviewer) can read the plan before the implementation.",
      doneWhen: "The doc is committed to the flagship repo.",
      minutes: 30,
      keywords: ["design doc in repo"],
      search: [web("where to put architecture docs in a repo")],
    },
  },
  {
    id: "c08",
    stage: "s3",
    week: "Weeks 7–8",
    title: "Core flows",
    goal: "Auth, posting, search and background summarisation jobs, working end to end.",
    nodeTip: "A background job queue is the same mental model as a maker-checker workflow: submit, process async, report back. You've built the equivalent before.",
    tasks: [
      {
        id: "c08-auth",
        title: "Auth, posting, search",
        learn: "User auth, creating/editing posts, and wiring search queries into Elasticsearch.",
        doneWhen: "A logged-in user can create a post and find it through search within a few seconds.",
        minutes: 240,
        keywords: ["auth flow", "full text search", "Elasticsearch indexing"],
        search: [web("Elasticsearch full text search Node.js tutorial")],
      },
      {
        id: "c08-jobs",
        title: "Background summarisation jobs: retries and a dead-letter queue",
        learn: "A BullMQ job calls an LLM API to summarise a post, with retry/backoff on failure and a dead-letter queue for jobs that keep failing.",
        doneWhen: "A deliberately-failing job retries the expected number of times and then lands in the dead-letter queue.",
        minutes: 180,
        keywords: ["BullMQ retries", "dead letter queue", "exponential backoff", "LLM API summarisation"],
        search: [web("BullMQ retry failed jobs dead letter queue")],
        links: [link("BullMQ Docs: Retrying failing jobs", "https://docs.bullmq.io/guide/retrying-failing-jobs")],
      },
    ],
    project: {
      id: "c08-proj",
      label: "Major project · Core flows working end to end",
      kind: "major",
      title: "Auth, posting, search and background AI summarisation all work together locally.",
      learn: "The hard middle of the project, done.",
      doneWhen: "A new post gets summarised asynchronously and the summary appears without a page refresh workaround.",
      minutes: 300,
      keywords: ["end to end feature flow"],
      search: [web("background job processing architecture Node.js")],
    },
  },
  {
    id: "c09",
    stage: "s3",
    week: "Week 9",
    title: "Real-time updates, caching, cost control",
    goal: "Make it feel alive, make it fast, and don't let LLM calls run up an unbounded bill.",
    nodeTip: "You already know WebSockets/STOMP from Celloscope — this is the same idea with your own backend on the other end.",
    tasks: [
      {
        id: "c09-realtime",
        title: "Real-time updates",
        learn: "Push summarisation results and new posts to connected clients over WebSockets instead of polling.",
        doneWhen: "A second browser tab sees a new post or finished summary appear without a manual refresh.",
        minutes: 150,
        keywords: ["WebSocket real-time updates", "Socket.IO", "pub/sub"],
        search: [web("real-time updates WebSocket Node.js tutorial")],
        links: [link("MDN: The WebSocket API", "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API")],
      },
      {
        id: "c09-cache",
        title: "Caching and rate limits",
        learn: "Cache expensive reads (search results, summaries); rate-limit the summarisation endpoint so one user can't exhaust the queue.",
        doneWhen: "A repeated identical search is visibly faster on the second call, and a rate limit test returns 429 as expected.",
        minutes: 90,
        keywords: ["API rate limiting", "Redis cache hit"],
        search: [web("rate limiting Node.js API Redis")],
      },
      {
        id: "c09-cost",
        title: "LLM cost control",
        learn: "Cap input size sent to the model, cache identical summarisation requests, and log token usage per request.",
        doneWhen: "A log line shows token count and estimated cost per summarisation call.",
        minutes: 90,
        keywords: ["LLM API cost control", "token usage logging"],
        search: [web("control LLM API costs production application")],
      },
    ],
    project: {
      id: "c09-proj",
      label: "Mini project · Live demo of real-time updates",
      kind: "mini",
      title: "Record a short clip showing a summary appearing live in a second tab while staying within a cost budget you defined.",
      learn: "Proof the real-time path actually works, not just the code.",
      doneWhen: "A clip or GIF exists showing the live update.",
      minutes: 60,
      keywords: ["demo recording real-time feature"],
      search: [web("record screen demo GIF for GitHub README")],
    },
  },
  {
    id: "c10",
    stage: "s3",
    week: "Week 10",
    title: "Tests, seed data, demo, README",
    goal: "A stranger can open the live link, log in with a demo account, and understand the architecture from the README in 3 minutes.",
    tasks: [
      {
        id: "c10-seed",
        title: "Tests, seed data, demo account",
        learn: "Enough tests to trust the core flows, realistic seed data, and a working demo login that doesn't require a real signup.",
        doneWhen: "A stranger can log in with the demo account and see populated content immediately.",
        minutes: 150,
        keywords: ["seed data script", "demo account", "test coverage"],
        search: [web("seed demo data for a portfolio project")],
      },
      {
        id: "c10-video",
        title: "Record a 2-minute demo video",
        learn: "Walk through the core flow: post, search, summarise, real-time update.",
        doneWhen: "A 2-minute video exists and is linked from the README.",
        minutes: 60,
        keywords: ["project demo video", "screen recording"],
        search: [web("how to record a good software demo video")],
      },
      {
        id: "c10-readme",
        title: "Write the README a stranger can trust",
        learn: "What it does, a screenshot, the live link, the stack, how to run it locally, and the architecture doc from week 6 linked in.",
        doneWhen: "Someone unfamiliar with the project understands the architecture from the README alone within 3 minutes.",
        minutes: 90,
        keywords: ["project README structure", "architecture diagram README"],
        search: [web("best README examples for software projects")],
      },
    ],
    project: {
      id: "c10-proj",
      label: "Major project · Flagship live with a complete README",
      kind: "major",
      title: "The knowledge-sharing platform is live, with a demo account, a 2-minute video, and a README a stranger can read in 3 minutes.",
      learn: "The headline project of the whole roadmap, finished.",
      doneWhen: "A stranger (ask a friend) opens the live link, logs in, and can explain back what the project does.",
      minutes: 180,
      keywords: ["flagship project launch"],
      search: [web("portfolio project launch checklist")],
    },
  },

  // ───────────────────────── Stage 4 ─────────────────────────
  {
    id: "c11",
    stage: "s4",
    week: "Weeks 9–12",
    title: "Docker",
    goal: "Package the whole stack so anyone (including a reviewer) can run it with one command.",
    tasks: [
      {
        id: "c11-dockerfile",
        title: "Dockerfile and docker-compose for the whole stack",
        learn: "Containerize the app plus its PostgreSQL, Redis and Elasticsearch dependencies with docker-compose.",
        doneWhen: "`docker compose up` brings up the entire stack from a clean machine.",
        minutes: 150,
        keywords: ["Dockerfile", "docker-compose", "containerize Node.js app"],
        search: [web("docker compose Node.js PostgreSQL Redis Elasticsearch example")],
        links: [link("Docker Docs: Compose", "https://docs.docker.com/compose/")],
      },
      {
        id: "c11-multistage",
        title: "Multi-stage builds",
        learn: "Separate build and runtime stages to keep the final image small and free of dev dependencies.",
        doneWhen: "The production image is noticeably smaller than a naive single-stage build and has no devDependencies.",
        minutes: 90,
        keywords: ["multi-stage Docker build", "image size optimization"],
        search: [web("Docker multi-stage build Node.js TypeScript")],
        links: [link("Docker Docs: Multi-stage builds", "https://docs.docker.com/build/building/multi-stage/")],
      },
    ],
    project: {
      id: "c11-proj",
      label: "Mini project · Dockerize the flagship",
      kind: "mini",
      title: "The flagship project runs fully in Docker with one command, with a multi-stage production image.",
      learn: "A reviewer never has to install your dependencies by hand.",
      doneWhen: "A clean clone plus `docker compose up` is all it takes to run the full stack.",
      minutes: 120,
      keywords: ["dockerize full stack project"],
      search: [web("dockerize full stack app checklist")],
    },
  },
  {
    id: "c12",
    stage: "s4",
    week: "Weeks 9–12",
    title: "CI/CD",
    goal: "Every pull request proves itself before a human has to look at it.",
    tasks: [
      {
        id: "c12-ci",
        title: "GitHub Actions: lint, test, build on every PR",
        learn: "A workflow that runs on pull_request, fails fast, and blocks merge on failure.",
        doneWhen: "A deliberately broken PR shows a red check before you fix it.",
        minutes: 120,
        keywords: ["GitHub Actions CI", "workflow lint test build"],
        search: [web("GitHub Actions CI pipeline lint test build Node.js")],
        links: [link("GitHub Docs: Actions", "https://docs.github.com/en/actions"), link("GitHub Docs: About workflows", "https://docs.github.com/en/actions/using-workflows/about-workflows")],
      },
      {
        id: "c12-cd",
        title: "Automatic deploy on merge",
        learn: "A workflow (or the host's native git integration) that deploys automatically once a PR merges to main.",
        doneWhen: "A merge to main results in a new live deployment without a manual step.",
        minutes: 90,
        keywords: ["continuous deployment GitHub Actions", "auto deploy on merge"],
        search: [web("GitHub Actions deploy on merge to main")],
      },
    ],
    project: {
      id: "c12-proj",
      label: "Mini project · Green CI on the flagship",
      kind: "mini",
      title: "The flagship repo has a GitHub Actions pipeline that lints, tests and builds on every PR, and deploys automatically on merge.",
      learn: "Reviewers look at this before they look at your code.",
      doneWhen: "The Actions tab shows a passing pipeline and at least one PR that went through it.",
      minutes: 90,
      keywords: ["CI pipeline badge"],
      search: [web("add CI status badge to README")],
    },
  },
  {
    id: "c13",
    stage: "s4",
    week: "Weeks 9–12",
    title: "Cloud and observability",
    goal: "Know what you deployed, not just that it's \"on the cloud.\"",
    tasks: [
      {
        id: "c13-cloud",
        title: "Deploy on one provider and understand every piece",
        learn: "Compute, a managed database, object storage, environment secrets, and a domain with HTTPS. Name each one you used.",
        doneWhen: "You can list which cloud service plays each of those 5 roles for your flagship.",
        minutes: 150,
        keywords: ["cloud deployment compute database storage secrets HTTPS"],
        search: [web("deploy full stack Node.js app to the cloud guide")],
      },
      {
        id: "c13-observability",
        title: "Structured logs, health check, error tracking, one dashboard",
        learn: "JSON structured logs, a `/health` endpoint, an error-tracking tool, and one basic dashboard (even a simple one) for request rate or errors.",
        doneWhen: "Hitting `/health` returns 200 with useful status, and one real error got captured by the tracker.",
        minutes: 150,
        keywords: ["structured logging", "health check endpoint", "error tracking", "observability dashboard"],
        search: [web("structured logging health check error tracking Node.js API")],
      },
    ],
    project: {
      id: "c13-proj",
      label: "Mini project · Flagship deployed with logs and a health check",
      kind: "mini",
      title: "The live flagship has a working health check, structured logs, and error tracking wired up.",
      learn: "This is what separates a deployed toy from an operable service.",
      doneWhen: "`/health` is live and at least one logged error shows up in the error tracker.",
      minutes: 120,
      keywords: ["production readiness checklist"],
      search: [web("production readiness checklist web app")],
    },
  },
  {
    id: "c14",
    stage: "s4",
    week: "Weeks 9–12",
    title: "Git habits reviewers look for",
    goal: "Small, well-described pull requests and a readable history, from here on.",
    tasks: [
      {
        id: "c14-prs",
        title: "Small PRs with descriptions",
        learn: "One concern per PR, a description that explains why (not just what), and issues opened for planned work before starting it.",
        doneWhen: "Your last 3 PRs on the flagship are each focused on one concern with a clear description.",
        minutes: 60,
        keywords: ["pull request best practices", "small focused PRs"],
        search: [web("how to write a good pull request description")],
      },
      {
        id: "c14-commits",
        title: "Conventional commit messages",
        learn: "feat/fix/chore/docs prefixes and why they make history and changelogs useful.",
        doneWhen: "Your last 10 commits follow the convention.",
        minutes: 45,
        keywords: ["conventional commits"],
        search: [web("conventional commits specification")],
        links: [link("Conventional Commits", "https://www.conventionalcommits.org/")],
      },
    ],
    project: {
      id: "c14-proj",
      label: "Mini project · Clean git workflow going forward",
      kind: "mini",
      title: "From today, every change to the flagship goes through an issue, a small PR, and conventional commits.",
      learn: "Reviewers judge your git history as much as your code.",
      doneWhen: "You can point to one issue → PR → merge cycle done this way.",
      minutes: 60,
      keywords: ["git workflow issues PRs"],
      search: [web("GitHub issue to PR workflow for solo projects")],
    },
  },

  // ───────────────────────── Stage 5 ─────────────────────────
  {
    id: "c15",
    stage: "s5",
    week: "Weeks 11–14",
    title: "Data structures and algorithms, by pattern",
    goal: "80–100 problems, grouped by pattern, in TypeScript, explained out loud in English.",
    nodeTip: "Two a day. Explaining aloud in English does double duty: it's interview practice and speaking practice at once.",
    tasks: [
      {
        id: "c15-p1",
        title: "Arrays/hashing, two pointers, sliding window",
        learn: "The three patterns behind most \"easy/medium\" array and string problems.",
        doneWhen: "You solved at least 15 problems across these three patterns without hints.",
        minutes: 450,
        keywords: ["two pointers", "sliding window", "hashmap pattern"],
        search: [web("NeetCode two pointers sliding window problem list"), yt("sliding window technique explained")],
        links: [link("NeetCode", "https://neetcode.io/")],
      },
      {
        id: "c15-p2",
        title: "Stack, binary search, linked list",
        learn: "Monotonic stacks, binary search on answers (not just sorted arrays), and linked-list pointer manipulation.",
        doneWhen: "You solved at least 15 problems across these three patterns without hints.",
        minutes: 450,
        keywords: ["monotonic stack", "binary search on answer", "linked list reversal"],
        search: [web("NeetCode stack binary search linked list problem list")],
      },
      {
        id: "c15-p3",
        title: "Trees, graphs (BFS/DFS), heaps",
        learn: "Tree traversals, graph BFS/DFS including on implicit graphs, and heaps for top-k / scheduling problems.",
        doneWhen: "You solved at least 20 problems across these three patterns without hints.",
        minutes: 600,
        keywords: ["BFS DFS graph traversal", "binary tree traversal", "heap top k"],
        search: [web("NeetCode trees graphs heaps problem list")],
      },
      {
        id: "c15-p4",
        title: "Basic dynamic programming",
        learn: "1D and 2D DP: recognizing overlapping subproblems and writing the recurrence before the code.",
        doneWhen: "You solved at least 10 DP problems and can write the recurrence relation before coding, for a new one.",
        minutes: 450,
        keywords: ["dynamic programming patterns", "memoization", "tabulation"],
        search: [web("NeetCode dynamic programming problem list"), yt("dynamic programming patterns explained")],
      },
    ],
    project: {
      id: "c15-proj",
      label: "Major project · 80–100 problems solved and logged",
      kind: "major",
      title: "Keep a running log (sheet or repo) of every problem: pattern, time taken, and whether you needed a hint.",
      learn: "The log itself is evidence of consistent practice, and it shows you where you're still weak.",
      doneWhen: "The log has 80+ entries across all four pattern groups above.",
      minutes: 120,
      keywords: ["algorithm practice log"],
      search: [web("algorithm problem practice tracker spreadsheet")],
    },
  },
  {
    id: "c16",
    stage: "s5",
    week: "Weeks 11–14",
    title: "System design, mid-level",
    goal: "Practise 6 designs you can walk through from requirements to failure modes.",
    nodeTip: "Reuse what you actually built: your flagship's queue, cache and search are real system-design material.",
    tasks: [
      {
        id: "c16-basics",
        title: "The framework: requirements, API, data model, scaling, failure cases",
        learn: "A repeatable structure to walk through any design question in an interview.",
        doneWhen: "You can list the 5 steps of the framework from memory.",
        minutes: 60,
        keywords: ["system design interview framework"],
        search: [web("system design interview framework steps")],
        links: [link("System Design Primer", "https://github.com/donnemartin/system-design-primer")],
      },
      {
        id: "c16-6designs",
        title: "Practise all 6: URL shortener, rate limiter, chat, notifications, news feed, job queue",
        learn: "Work through each with the framework above; use your flagship's BullMQ/Redis work as real material for the job-queue and rate-limiter designs.",
        doneWhen: "You can whiteboard (or talk through) all 6 designs without notes, in under 20 minutes each.",
        minutes: 600,
        keywords: ["URL shortener design", "rate limiter design", "chat system design", "notification service design", "news feed design", "job queue design"],
        search: [web("system design URL shortener rate limiter chat notification news feed job queue")],
      },
    ],
    project: {
      id: "c16-proj",
      label: "Major project · Write up all 6 system designs",
      kind: "major",
      title: "One page per design: requirements, API, data model, scaling plan, failure cases.",
      learn: "Written designs double as interview prep and as blog-post material for Phase F.",
      doneWhen: "6 one-page write-ups exist, each covering all 5 framework steps.",
      minutes: 180,
      keywords: ["system design write-up"],
      search: [web("system design interview write up example")],
    },
  },
  {
    id: "c17",
    stage: "s5",
    week: "Weeks 11–14",
    title: "Question bank and take-home tasks",
    goal: "Know the common questions cold, and prove you can deliver a scoped task under a real deadline.",
    tasks: [
      {
        id: "c17-bank",
        title: "50 JavaScript/Node/SQL questions, in your own words",
        learn: "Pull from your Phase B notes and write your own answer to 50 common interview questions, not someone else's.",
        doneWhen: "50 answers exist in your own words, each a few sentences.",
        minutes: 240,
        keywords: ["JavaScript interview questions", "Node.js interview questions", "SQL interview questions"],
        search: [web("common JavaScript Node.js SQL interview questions and answers")],
      },
      {
        id: "c17-takehome",
        title: "Two take-home tasks, 4-hour limit",
        learn: "The most common filter for remote roles. Always include tests, a README, and a short list of trade-offs you made under time pressure.",
        doneWhen: "Two completed take-homes exist, each with tests, a README and a trade-offs section, each done within 4 hours.",
        minutes: 480,
        keywords: ["take-home coding challenge", "trade-offs documentation"],
        search: [web("example take home coding assignment full stack")],
      },
    ],
    project: {
      id: "c17-proj",
      label: "Mini project · Publish one take-home as a portfolio piece",
      kind: "mini",
      title: "Pick your stronger take-home, clean it up slightly, and add it as a pinned repo.",
      learn: "A timed, scoped deliverable is strong proof of working speed and judgement.",
      doneWhen: "The take-home is a pinned repo with its own README.",
      minutes: 60,
      keywords: ["take home as portfolio project"],
      search: [web("turn take home assignment into portfolio project")],
    },
  },
  {
    id: "c18",
    stage: "s5",
    week: "Weeks 11–14",
    title: "Behavioural stories and mock interviews",
    goal: "6 ready stories, and real practice talking through your work out loud, in English, under pressure.",
    tasks: [
      {
        id: "c18-star",
        title: "6 stories in situation-action-result form",
        learn: "A hard bug, a disagreement, a deadline, a mistake, something you led, something you learned fast. Your maker-checker and audit-trail work at Celloscope are good raw material.",
        doneWhen: "6 STAR stories are written down, each under a minute to tell.",
        minutes: 120,
        keywords: ["STAR method behavioural interview", "situation action result"],
        search: [web("STAR method behavioural interview examples")],
      },
      {
        id: "c18-mocks",
        title: "5 mock interviews in English",
        learn: "With a peer or a mock-interview platform. Record and rewatch at least one to see your own habits.",
        doneWhen: "5 mock interviews are done, and you've rewatched a recording of at least one.",
        minutes: 300,
        keywords: ["mock interview practice", "technical interview practice English"],
        search: [web("free mock interview practice platforms for developers")],
      },
    ],
    project: {
      id: "c18-proj",
      label: "Mini project · Mock interview reflection notes",
      kind: "mini",
      title: "After each mock interview, write 3 sentences: what went well, what you'd change, one phrase in English you want to use more naturally.",
      learn: "Turns practice into compounding improvement instead of just repetition.",
      doneWhen: "Notes exist for all 5 mock interviews.",
      minutes: 60,
      keywords: ["interview practice reflection notes"],
      search: [web("how to self-review a mock interview")],
    },
  },

  // ───────────────────────── Stage 6 ─────────────────────────
  {
    id: "c19",
    stage: "s6",
    week: "Weeks 3–16",
    title: "Open source: two merged pull requests",
    goal: "The strongest trust signal available to someone with 2 years of experience: a merged PR in a project people actually use.",
    tasks: [
      {
        id: "c19-pick",
        title: "Pick 2 projects you actually use",
        learn: "NestJS ecosystem, Prisma, or a UI library you already rely on. Familiarity beats a random popular repo.",
        doneWhen: "2 specific repos are chosen, and you've read their CONTRIBUTING guide.",
        minutes: 60,
        keywords: ["choosing open source project to contribute to", "CONTRIBUTING.md"],
        search: [web("how to pick an open source project to contribute to")],
      },
      {
        id: "c19-start",
        title: "Start with docs fixes and good-first-issue tickets",
        learn: "Documentation fixes and labeled starter tickets are the lowest-friction way in; they teach you the repo's review process.",
        doneWhen: "You opened your first PR, even a small docs fix.",
        minutes: 120,
        keywords: ["good first issue", "open source first contribution"],
        search: [web("good first issue open source for beginners")],
        links: [link("GitHub: good-first-issue topic", "https://github.com/topics/good-first-issue")],
      },
    ],
    project: {
      id: "c19-proj",
      label: "Major project · 2 merged open-source pull requests",
      kind: "major",
      title: "Get 2 pull requests merged into real, used-by-others repositories.",
      learn: "This is the single strongest credibility signal for someone without 3+ years of experience.",
      doneWhen: "2 PRs show as merged on your GitHub profile.",
      minutes: 600,
      keywords: ["merged pull request portfolio"],
      search: [web("open source contributions that help you get hired")],
    },
  },
  {
    id: "c20",
    stage: "s6",
    week: "Weeks 3–16",
    title: "Writing and build-in-public",
    goal: "Turn the weekly notes you're already taking into public proof of your thinking.",
    tasks: [
      {
        id: "c20-posts",
        title: "4 short technical posts from your own notes",
        learn: "Pull straight from Phase B/C notes: how you found and fixed the slow query, how you built BullMQ retries, etc.",
        doneWhen: "4 posts are published somewhere public (blog, dev.to, LinkedIn article).",
        minutes: 300,
        keywords: ["technical blog post from project notes"],
        search: [web("how to write a technical blog post from your own project")],
      },
      {
        id: "c20-linkedin",
        title: "One LinkedIn post a week: what you built, what broke",
        learn: "This fits the build-in-public story you're already telling with this roadmap.",
        doneWhen: "At least 4 consecutive weekly posts are published.",
        minutes: 30,
        keywords: ["build in public LinkedIn posts"],
        search: [web("build in public developer LinkedIn post examples")],
      },
    ],
    project: {
      id: "c20-proj",
      label: "Mini project · 4 published technical posts",
      kind: "mini",
      title: "Collect the 4 posts in one place and link them from your portfolio site.",
      learn: "Interviewers and recruiters read these before they read your code.",
      doneWhen: "4 posts are live and linked from the portfolio.",
      minutes: 60,
      keywords: ["portfolio blog section"],
      search: [web("add blog posts section to portfolio site")],
    },
  },
  {
    id: "c21",
    stage: "s6",
    week: "Weeks 1–16, daily",
    title: "English and async communication",
    goal: "Most of this work is asynchronous. Clear written and spoken English is a requirement, not a nice-to-have.",
    tasks: [
      {
        id: "c21-speaking",
        title: "30 minutes a day of spoken technical English",
        learn: "Explain what you built today out loud, as if giving a stand-up. This doubles as IELTS speaking practice.",
        doneWhen: "You've done this for 5 days in a row at least once.",
        minutes: 30,
        keywords: ["spoken English practice technical", "daily stand-up practice"],
        search: [web("daily spoken English practice for developers")],
      },
      {
        id: "c21-async",
        title: "Learn the async formats",
        learn: "A daily written update (done/next/blocked), a clear bug report, and a short design proposal — the actual documents remote teams run on.",
        doneWhen: "You wrote one of each: a done/next/blocked update, a bug report, and a one-page proposal.",
        minutes: 90,
        keywords: ["async communication remote work", "bug report template", "design proposal template"],
        search: [web("writing async updates for remote teams template")],
      },
      {
        id: "c21-ielts",
        title: "Set an IELTS date",
        learn: "A band of 7+ also supports an MSc route to Canada or Australia if you want that door open later.",
        doneWhen: "An IELTS test date is booked.",
        minutes: 30,
        keywords: ["IELTS test booking", "IELTS band 7"],
        search: [web("how to register for IELTS")],
        links: [link("IELTS official site", "https://www.ielts.org/")],
      },
    ],
    project: {
      id: "c21-proj",
      label: "Mini project · First recorded mock speaking test",
      kind: "mini",
      title: "Record yourself answering an IELTS speaking Part 2 style prompt for 2 minutes, unscripted.",
      learn: "A baseline to measure improvement against before test day.",
      doneWhen: "A recording exists and you've listened back to it once.",
      minutes: 30,
      keywords: ["IELTS speaking part 2 practice"],
      search: [web("IELTS speaking part 2 practice questions")],
    },
  },

  // ───────────────────────── Stage 7 ─────────────────────────
  {
    id: "c22",
    stage: "s7",
    week: "From week 6",
    title: "Platforms and sourcing",
    goal: "Be visible on the places international remote employers actually look, and check fixed sources on a schedule instead of scrolling randomly.",
    tasks: [
      {
        id: "c22-profiles",
        title: "Complete profiles on Arc, Turing, Wellfound, LinkedIn",
        learn: "Both Arc and Turing explicitly list Bangladesh. Take their vetting tests only after Phase B is done — a failed test can lock you out for months.",
        doneWhen: "All 4 profiles are fully filled out, with the flagship project linked on each.",
        minutes: 150,
        keywords: ["Arc.dev profile", "Turing vetting", "Wellfound profile"],
        search: [web("Arc.dev developer profile setup"), web("Turing vetting test preparation")],
        links: [link("Arc.dev", "https://arc.dev/"), link("Turing", "https://www.turing.com/"), link("Wellfound", "https://wellfound.com/")],
      },
      {
        id: "c22-sources",
        title: "Check fixed sources on fixed days",
        learn: "The monthly Hacker News \"Who is hiring\" thread, We Work Remotely, Himalayas, and LinkedIn filtered to Remote.",
        doneWhen: "A recurring calendar reminder exists for checking each source.",
        minutes: 60,
        keywords: ["Hacker News who is hiring", "We Work Remotely", "Himalayas jobs"],
        search: [web("Hacker News who is hiring thread")],
        links: [link("We Work Remotely", "https://weworkremotely.com/"), link("Himalayas", "https://himalayas.app/"), link("HN Hiring aggregator", "https://hnhiring.com/")],
      },
      {
        id: "c22-filter",
        title: "Filter hard: worldwide, anywhere, or your region only",
        learn: "Skip \"Remote (US)\". Apply only where the post explicitly includes your location.",
        doneWhen: "You can point to 3 posts you deliberately skipped because of location, and why.",
        minutes: 30,
        keywords: ["remote job location filter worldwide"],
        search: [web("remote jobs worldwide vs US only")],
      },
    ],
    project: {
      id: "c22-proj",
      label: "Mini project · All platform profiles live",
      kind: "mini",
      title: "Arc, Turing, Wellfound and LinkedIn profiles are all complete and consistent with the resume headline.",
      learn: "Passive inbound starts here, once profiles are live.",
      doneWhen: "All 4 profiles are live and linked to the same portfolio site.",
      minutes: 60,
      keywords: ["consistent profiles across platforms"],
      search: [web("keep job platform profiles consistent")],
    },
  },
  {
    id: "c23",
    stage: "s7",
    week: "From week 6, weekly",
    title: "Volume, outreach, tracker",
    goal: "A sustainable weekly system: enough volume to matter, personal enough to get replies.",
    tasks: [
      {
        id: "c23-applications",
        title: "10 targeted applications a week",
        learn: "For each: a 5-line note on what the company builds, the two things in your background that match, and one link to proof.",
        doneWhen: "One full week of 10 applications, each with its 5-line note, is logged.",
        minutes: 300,
        keywords: ["targeted job application process"],
        search: [web("how to write a tailored job application note")],
      },
      {
        id: "c23-outreach",
        title: "5 direct outreach messages a week",
        learn: "Short, specific messages to founders or engineering leads at small companies that hire worldwide, with one link.",
        doneWhen: "5 outreach messages are sent in one week, each under 5 sentences.",
        minutes: 90,
        keywords: ["cold outreach to founders", "direct message engineering lead"],
        search: [web("cold outreach message template for developers")],
      },
      {
        id: "c23-tracker",
        title: "Keep the tracker current, follow up once after 7 days",
        learn: "Company, role, date, contact, status, follow-up date — all in one place, checked weekly.",
        doneWhen: "The tracker is up to date and at least one 7-day follow-up has been sent.",
        minutes: 60,
        keywords: ["job application follow up email"],
        search: [web("job application follow up email template")],
      },
    ],
    project: {
      id: "c23-proj",
      label: "Mini project · First full week of the application system",
      kind: "mini",
      title: "Run one complete week: 10 applications, 5 outreach messages, tracker kept current, one follow-up sent.",
      learn: "Proves the system is sustainable before you commit to running it for months.",
      doneWhen: "One full week is logged in the tracker exactly as planned.",
      minutes: 60,
      keywords: ["weekly job search system"],
      search: [web("systematic weekly job search routine")],
    },
  },
  {
    id: "c24",
    stage: "s7",
    week: "Weeks 10–16+",
    title: "Route by market, freelance bridge, practical setup",
    goal: "Pick where to actually point this effort, and have the boring logistics sorted before an offer shows up.",
    tasks: [
      {
        id: "c24-route",
        title: "Pick a market route and its timing",
        learn: "Worldwide remote (from week 6) via platforms and direct \"anywhere\" applications; Europe (week 10+) via small product companies, offering Dhaka afternoon/evening overlap; Middle East (week 10+) via on-site employer-visa roles, keeping Angular visible on that resume version; Australia/US/Canada mostly after 3 years or via an MSc.",
        doneWhen: "One primary market and one backup are chosen, with the resume version each one needs noted.",
        minutes: 60,
        keywords: ["remote job market by region", "visa sponsorship route"],
        search: [web("best countries for remote developer jobs by region")],
      },
      {
        id: "c24-freelance",
        title: "Two or three small freelance contracts as a bridge",
        learn: "Paid work for foreign clients gives you \"worked with international clients\" on the resume, which many remote employers explicitly ask for.",
        doneWhen: "At least one freelance contract with a foreign client is signed or completed.",
        minutes: 120,
        keywords: ["freelance for international clients", "bridge contract experience"],
        search: [web("how to find freelance clients abroad as a developer")],
      },
      {
        id: "c24-setup",
        title: "Confirm the practical setup before the first offer",
        learn: "A legal way to receive foreign income into a Bangladeshi bank account (check current rules with your bank), reliable power/internet backup, and reading any contract for payment terms, notice period, code ownership and working hours before signing.",
        doneWhen: "You've confirmed the foreign-income process with your bank and have a short checklist for reading any contract.",
        minutes: 90,
        keywords: ["receive foreign income Bangladesh bank", "freelance contract red flags"],
        search: [web("receiving foreign currency income Bangladesh bank rules")],
      },
    ],
    project: {
      id: "c24-proj",
      label: "Mini project · Market route decided and written down",
      kind: "mini",
      title: "A one-paragraph decision: primary market, backup market, and the resume/profile version each needs.",
      learn: "Stops effort from being spread thin across every market at once.",
      doneWhen: "The decision is written down and the right resume version exists for each market.",
      minutes: 45,
      keywords: ["job search market strategy"],
      search: [web("focus job search on specific markets strategy")],
    },
  },
];

function build(m: ModuleIn, index: number): ModuleDoc {
  const tasks: Step[] = m.tasks.map((t) => ({ ...t, links: t.links ?? [] }));
  const project: Project = {
    ...m.project,
    kind: m.project.kind ?? "mini",
    links: m.project.links ?? [],
  };
  return {
    _id: m.id,
    order: index + 1,
    stage: m.stage,
    week: m.week,
    title: m.title,
    goal: m.goal,
    ...(m.nodeTip && { nodeTip: m.nodeTip }),
    tasks,
    project,
    itemIds: [...tasks.map((t) => t.id), project.id],
  };
}

export const MODULES: ModuleDoc[] = MODULES_IN.map(build);
