// The roadmap content. This file is only the SOURCE for the database:
// `pnpm seed` copies it into MongoDB, and the app reads it from there.
//
// Keep each `id` the same when you reword a step. Progress and notes are saved
// by id. Edit this file, then run `pnpm seed` again to update the database.
//
// This file must not import anything except types: the seed script runs it
// directly with Node.
import type { Link, ModuleDoc, Project, Search, StageDoc, Step } from "./roadmap-types";

const yt = (q: string): Search => ({ q, on: "yt" });
const web = (q: string): Search => ({ q, on: "web" });
const link = (label: string, url: string): Link => ({ label, url });

type StepIn = Omit<Step, "links"> & { links?: Link[] };
type ProjectIn = StepIn & { label: string; kind?: "mini" | "major" };
type ModuleIn = {
  id: string;
  stage: string;
  week: string;
  title: string;
  goal: string;
  nodeTip?: string;
  tasks: StepIn[];
  project: ProjectIn;
};

export const ROADMAP_VERSION = 2;

export const STAGES: StageDoc[] = [
  { _id: "s1", order: 1, title: "Python and data basics", blurb: "Get comfortable with Python and the notebook workflow. About 4 weeks." },
  { _id: "s2", order: 2, title: "Deep learning core", blurb: "How neural networks learn, then PyTorch. About 3 weeks." },
  { _id: "s3", order: 3, title: "Images: classify and detect objects", blurb: "Your first fine-tunes: image classifiers and YOLO object detection. About 6 weeks." },
  { _id: "s4", order: 4, title: "LLMs: how they work", blurb: "Tokens, attention, Hugging Face, running open models locally. About 3 weeks." },
  { _id: "s5", order: 5, title: "Fine-tune LLMs and vision-language models", blurb: "The main event: LoRA/QLoRA, evaluating, quantizing, serving. About 6 weeks." },
  { _id: "s6", order: 6, title: "Level up and portfolio", blurb: "Image generation fine-tuning, then package everything you built. About 3 weeks." },
];

const MODULES_IN: ModuleIn[] = [
  // ───────────────────────── Stage 1 ─────────────────────────
  {
    id: "m01",
    stage: "s1",
    week: "Week 1",
    title: "Python for a JavaScript developer",
    goal: "Be productive in Python and in the notebook workflow every ML tutorial uses.",
    nodeTip:
      "npm → pip/uv, package.json → pyproject.toml, node_modules → .venv, arrays/objects → lists/dicts. Indentation is syntax.",
    tasks: [
      {
        id: "p1-python",
        title: "Python syntax through JS eyes",
        learn: "Lists, dicts, comprehensions, f-strings, functions, classes, imports. Skip anything you'd skip in a JS beginner course.",
        doneWhen: "You can write a function that loops over a list of dicts and returns a filtered list, without looking anything up.",
        minutes: 180,
        keywords: ["list comprehension", "dict", "f-string", "*args **kwargs", "type hints", "dataclass"],
        search: [yt("Python for JavaScript developers"), yt("Corey Schafer Python list comprehensions"), web("Kaggle Learn Python")],
        links: [link("Kaggle Learn: Python (free, interactive)", "https://www.kaggle.com/learn/python")],
      },
      {
        id: "m01-env",
        title: "Environments and packages",
        learn: "Virtual environments, pip vs uv, requirements.txt and pyproject.toml. This is Python's npm install.",
        doneWhen: "You made a fresh folder, a virtual environment, installed `requests` into it, and ran a script that uses it.",
        minutes: 60,
        keywords: ["venv", "pip", "uv", "pyproject.toml", "requirements.txt"],
        search: [yt("uv python package manager tutorial"), yt("Corey Schafer python venv virtual environment")],
        links: [link("uv docs", "https://docs.astral.sh/uv/")],
      },
      {
        id: "m01-colab",
        title: "Notebooks and a free GPU",
        learn: "Jupyter-style cells, `!pip install`, switching Google Colab to a free T4 GPU, and Kaggle Notebooks as a second free GPU source.",
        doneWhen: "A Colab notebook with the GPU runtime on prints your GPU name using `!nvidia-smi`.",
        minutes: 45,
        keywords: ["Google Colab", "Colab GPU runtime", "!pip install", "mount Google Drive", "Kaggle notebooks GPU"],
        search: [yt("Google Colab tutorial for beginners"), web("Colab change runtime type GPU T4")],
        links: [
          link("Google Colab", "https://colab.research.google.com/"),
          link("Kaggle Notebooks docs", "https://www.kaggle.com/docs/notebooks"),
        ],
      },
    ],
    project: {
      id: "m01-proj",
      label: "Mini project · Port a Node script",
      kind: "mini",
      title: "Rewrite a small Node script you've written before (a CLI, a file parser, an API call) in Python, with a venv.",
      learn: "Proves you can ship working Python, not just read it.",
      doneWhen: "The Python version runs and gives the same output as your Node version.",
      minutes: 120,
      keywords: ["requests", "argparse", "pathlib", "json module"],
      search: [web("python requests library quickstart"), web("python argparse tutorial")],
    },
  },
  {
    id: "m02",
    stage: "s1",
    week: "Week 2",
    title: "NumPy, Pandas and plots",
    goal: "Handle data the way ML code does: whole arrays and tables at once, not loops.",
    nodeTip: "A DataFrame is an array of objects with SQL superpowers. The mindset shift is vectorization: no for-loops over data.",
    tasks: [
      {
        id: "p1-numpy",
        title: "NumPy arrays and shapes",
        learn: "Shapes, indexing, slicing, broadcasting. Shape errors are the number one PyTorch bug later, so get comfortable here.",
        doneWhen: "You can explain why a (3,1) array plus a (1,4) array gives a (3,4) array.",
        minutes: 120,
        keywords: ["ndarray", "shape", "broadcasting", "axis", "reshape", "dot product"],
        search: [yt("NumPy tutorial freeCodeCamp"), yt("numpy broadcasting explained")],
        links: [link("NumPy: absolute beginners", "https://numpy.org/doc/stable/user/absolute_beginners.html")],
      },
      {
        id: "m02-pandas",
        title: "Pandas DataFrames",
        learn: "Load a CSV, select and filter rows, groupby, handle missing values.",
        doneWhen: "You loaded a CSV and answered a question with groupby.",
        minutes: 150,
        keywords: ["DataFrame", "groupby", "merge", "fillna", "value_counts"],
        search: [yt("Corey Schafer pandas tutorial"), web("Kaggle Learn Pandas")],
        links: [link("Kaggle Learn: Pandas", "https://www.kaggle.com/learn/pandas")],
      },
      {
        id: "m02-plot",
        title: "Plotting with Matplotlib",
        learn: "Line, bar, histogram, scatter. You'll plot loss curves for the rest of this roadmap.",
        doneWhen: "You plotted a line chart with a title and axis labels from a DataFrame column.",
        minutes: 60,
        keywords: ["matplotlib pyplot", "histogram", "scatter plot", "seaborn"],
        search: [yt("Corey Schafer matplotlib tutorial"), web("Kaggle Learn Data Visualization")],
        links: [link("Kaggle Learn: Data Visualization", "https://www.kaggle.com/learn/data-visualization")],
      },
    ],
    project: {
      id: "p1-proj",
      label: "Mini project · Data playground",
      kind: "mini",
      title: "Pick a Kaggle dataset you find interesting, clean it in Pandas, and answer 3 questions about it with charts in a Colab notebook.",
      learn: "Your first end-to-end data workflow.",
      doneWhen: "Your notebook has 3 questions, 3 charts and one sentence of answer under each.",
      minutes: 150,
      keywords: ["Kaggle datasets", "exploratory data analysis", "data cleaning"],
      search: [yt("exploratory data analysis pandas project"), web("Kaggle datasets")],
      links: [link("Kaggle Datasets", "https://www.kaggle.com/datasets")],
    },
  },
  {
    id: "m03",
    stage: "s1",
    week: "Week 3",
    title: "The math you actually need",
    goal: "Intuition, not proofs. Watch for the picture, then write it in NumPy.",
    nodeTip: "Watch once for intuition, then code it. If you can write it in NumPy, it counts as understood.",
    tasks: [
      {
        id: "p1-linalg",
        title: "Vectors and matrices",
        learn: "A vector is a list of numbers; a matrix multiply is a transformation. Nearly everything in ML is a matrix multiply.",
        doneWhen: "You can say what `A @ B` does and what shape comes out.",
        minutes: 90,
        keywords: ["vector", "matrix multiplication", "dot product", "linear transformation"],
        search: [yt("3Blue1Brown Essence of linear algebra"), yt("3Blue1Brown matrix multiplication as composition")],
        links: [link("3Blue1Brown: Linear algebra", "https://www.3blue1brown.com/topics/linear-algebra")],
      },
      {
        id: "p1-calc",
        title: "Derivatives and the gradient",
        learn: "A derivative is a slope. The chain rule is backpropagation. The gradient points uphill.",
        doneWhen: "You can explain in one sentence why we move opposite to the gradient to reduce a loss.",
        minutes: 90,
        keywords: ["derivative", "chain rule", "partial derivative", "gradient"],
        search: [yt("3Blue1Brown Essence of calculus"), yt("StatQuest the chain rule")],
        links: [link("3Blue1Brown: Calculus", "https://www.3blue1brown.com/topics/calculus")],
      },
      {
        id: "p1-stats",
        title: "Probability, just enough",
        learn: "Mean, variance, normal distribution, and what softmax and cross-entropy mean.",
        doneWhen: "You know what softmax outputs and why cross-entropy loss is small when the right class gets a high probability.",
        minutes: 90,
        keywords: ["normal distribution", "likelihood", "softmax", "cross entropy"],
        search: [yt("StatQuest statistics fundamentals"), yt("StatQuest cross entropy")],
        links: [link("StatQuest video index", "https://statquest.org/video-index/")],
      },
      {
        id: "m03-gd",
        title: "Gradient descent",
        learn: "How a model learns: compute the loss, take its gradient, step a little downhill, repeat.",
        doneWhen: "You can describe the loop and what the learning rate controls.",
        minutes: 45,
        keywords: ["loss function", "learning rate", "gradient descent", "mean squared error"],
        search: [yt("StatQuest gradient descent step by step")],
      },
    ],
    project: {
      id: "m03-proj",
      label: "Mini project · Gradient descent from scratch",
      kind: "mini",
      title: "Fit a line to noisy data using only NumPy and your own gradient descent loop. Plot the loss going down.",
      learn: "The same loop powers every model you will train later.",
      doneWhen: "A plot shows the loss decreasing and the fitted line going through the data.",
      minutes: 120,
      keywords: ["linear regression", "MSE", "learning rate"],
      search: [yt("linear regression from scratch python numpy gradient descent")],
    },
  },
  {
    id: "m04",
    stage: "s1",
    week: "Week 4",
    title: "Machine learning vocabulary",
    goal: "Learn the words and workflow every ML job assumes: features, train/test split, overfitting, metrics.",
    nodeTip: "scikit-learn feels like a well-designed npm library: every model has the same fit() and predict().",
    tasks: [
      {
        id: "m04-sklearn",
        title: "Your first models with scikit-learn",
        learn: "Train/test split, fit, predict, decision trees and random forests. Keep it light; deep learning is next.",
        doneWhen: "You trained a random forest and printed its accuracy on data it never saw.",
        minutes: 150,
        keywords: ["train_test_split", "fit predict", "random forest", "cross validation", "pipeline"],
        search: [yt("scikit-learn full course freeCodeCamp"), web("Kaggle Learn Intro to Machine Learning")],
        links: [link("Kaggle Learn: Intro to Machine Learning", "https://www.kaggle.com/learn/intro-to-machine-learning")],
      },
      {
        id: "m04-metrics",
        title: "Overfitting and metrics",
        learn: "Overfitting, bias vs variance, accuracy vs precision/recall/F1, the confusion matrix. You will use all of these on images and text.",
        doneWhen: "You can say why 99% accuracy can still be a bad model, and what precision and recall each measure.",
        minutes: 90,
        keywords: ["overfitting", "bias variance tradeoff", "precision recall", "F1 score", "confusion matrix"],
        search: [yt("StatQuest machine learning fundamentals bias and variance"), yt("StatQuest confusion matrix")],
      },
    ],
    project: {
      id: "m04-proj",
      label: "Mini project · Kaggle submission",
      kind: "mini",
      title: "Enter the Kaggle Titanic competition with a scikit-learn model and submit. Improve your score once.",
      learn: "Real leaderboard feedback on your own model.",
      doneWhen: "You have a score on the leaderboard, and a second, higher score after one change.",
      minutes: 180,
      keywords: ["Kaggle competition", "feature engineering", "submission"],
      search: [yt("Kaggle Titanic tutorial scikit-learn"), web("Kaggle Titanic competition")],
      links: [link("Kaggle: Titanic", "https://www.kaggle.com/competitions/titanic")],
    },
  },

  // ───────────────────────── Stage 2 ─────────────────────────
  {
    id: "m05",
    stage: "s2",
    week: "Week 5",
    title: "Neural networks from scratch",
    goal: "See inside a neural network by building a tiny one without a framework.",
    nodeTip: "Watch Karpathy in short sittings with the code open next to the video. Pause and type it yourself.",
    tasks: [
      {
        id: "p2-nn",
        title: "Neural network intuition",
        learn: "Neurons, layers, activations, the forward pass, and what backpropagation does.",
        doneWhen: "You can draw a 2-layer network and say what flows forward and what flows backward.",
        minutes: 90,
        keywords: ["neuron", "activation function", "ReLU", "backpropagation", "hidden layer"],
        search: [yt("3Blue1Brown neural networks"), yt("StatQuest neural networks")],
        links: [link("3Blue1Brown: Neural networks", "https://www.3blue1brown.com/topics/neural-networks")],
      },
      {
        id: "p3-karpathy",
        title: "Build micrograd (code along)",
        learn: "Karpathy's tiny autograd engine: backprop by hand, then a small neural net. Do it in 2–3 sittings.",
        doneWhen: "Your own micrograd runs and a small network's loss goes down.",
        minutes: 240,
        keywords: ["autograd", "computational graph", "backpropagation", "micrograd"],
        search: [yt("Karpathy spelled-out intro to neural networks and backpropagation micrograd")],
        links: [
          link("Karpathy: Neural Networks Zero to Hero", "https://karpathy.ai/zero-to-hero.html"),
          link("micrograd on GitHub", "https://github.com/karpathy/micrograd"),
        ],
      },
    ],
    project: {
      id: "m05-proj",
      label: "Mini project · Write backprop in your own words",
      kind: "mini",
      title: "Train your micrograd network on a toy dataset (two moons), plot the decision boundary, and write a 5-sentence note on what backprop does. Bonus for Node fans: port it to TypeScript.",
      learn: "If you can explain it plainly, it's yours.",
      doneWhen: "A decision-boundary picture exists, and the 5-sentence note is saved in the note box here.",
      minutes: 150,
      keywords: ["two moons dataset", "decision boundary", "backprop"],
      search: [web("micrograd decision boundary two moons demo")],
    },
  },
  {
    id: "m06",
    stage: "s2",
    week: "Weeks 6–7",
    title: "PyTorch",
    goal: "Train real models with the framework almost every fine-tuning tool is built on.",
    nodeTip: "A training loop is the same five calls in every project: forward, loss, zero_grad, backward, step.",
    tasks: [
      {
        id: "p2-torch",
        title: "Tensors, autograd and the training loop",
        learn: "Tensors on the GPU, nn.Module, optimizers, loss functions, writing the training loop yourself.",
        doneWhen: "You wrote a training loop from memory (with a peek at notes) that trains a small model.",
        minutes: 240,
        keywords: ["tensor", "nn.Module", "optimizer", "loss.backward()", "training loop", "CUDA"],
        search: [yt("PyTorch for Deep Learning full course freeCodeCamp"), web("PyTorch Learn the Basics tutorial")],
        links: [
          link("PyTorch: Learn the Basics", "https://docs.pytorch.org/tutorials/beginner/basics/intro.html"),
          link("Learn PyTorch (free book)", "https://www.learnpytorch.io/"),
        ],
      },
      {
        id: "m06-data",
        title: "Datasets, DataLoaders and saving models",
        learn: "Dataset and DataLoader, batches and epochs, train/validation split, saving and loading weights.",
        doneWhen: "You wrote a custom Dataset, loaded it with a DataLoader, and saved and re-loaded a model's weights.",
        minutes: 150,
        keywords: ["Dataset", "DataLoader", "batch size", "epoch", "state_dict"],
        search: [yt("PyTorch Dataset DataLoader explained"), web("PyTorch datasets and dataloaders tutorial")],
      },
      {
        id: "m06-curves",
        title: "Read loss curves",
        learn: "Training loss vs validation loss: how to see overfitting, underfitting, and a learning rate that's too high.",
        doneWhen: "Given a train/validation loss plot, you can say whether the model is overfitting.",
        minutes: 45,
        keywords: ["training loss", "validation loss", "overfitting", "learning rate"],
        search: [yt("how to read training and validation loss curves")],
      },
    ],
    project: {
      id: "p2-proj",
      label: "Mini project · Your first classifier",
      kind: "mini",
      title: "Train a FashionMNIST classifier in PyTorch on the free GPU. Plot train vs validation loss and get above 88% test accuracy.",
      learn: "Your first full PyTorch training run, start to finish.",
      doneWhen: "A notebook shows the loss plot and a final test accuracy above 88%.",
      minutes: 180,
      keywords: ["FashionMNIST", "image classification", "validation loss"],
      search: [yt("PyTorch FashionMNIST classifier tutorial")],
    },
  },

  // ───────────────────────── Stage 3 ─────────────────────────
  {
    id: "m07",
    stage: "s3",
    week: "Week 8",
    title: "Your first fine-tune: image classifier",
    goal: "Take a pretrained image model and adapt it to your own pictures. This is fine-tuning in its simplest form.",
    nodeTip: "Hugging Face Spaces is Vercel for model demos: push a repo, get a public URL, free.",
    tasks: [
      {
        id: "m07-cnn",
        title: "How CNNs see images",
        learn: "Convolutions, pooling, feature maps, and why pretrained image models transfer so well.",
        doneWhen: "You can explain why early layers learn edges and later layers learn objects.",
        minutes: 75,
        keywords: ["convolution", "pooling", "CNN", "feature map", "ResNet"],
        search: [yt("StatQuest convolutional neural networks"), yt("CNN explained visually")],
        links: [link("Kaggle Learn: Computer Vision", "https://www.kaggle.com/learn/computer-vision")],
      },
      {
        id: "m07-transfer",
        title: "Transfer learning: freeze, replace the head, train",
        learn: "Load a pretrained ResNet/ConvNeXt, freeze the backbone, swap the last layer, train on a small dataset.",
        doneWhen: "A pretrained model that never saw your classes now predicts them above 85% on a held-out set.",
        minutes: 180,
        keywords: ["transfer learning", "pretrained model", "freezing layers", "fine-tuning", "torchvision", "timm"],
        search: [yt("fastai lesson 1 is it a bird"), yt("PyTorch transfer learning tutorial ResNet")],
        links: [
          link("fast.ai: Practical Deep Learning (free)", "https://course.fast.ai/"),
          link("PyTorch: Transfer learning tutorial", "https://docs.pytorch.org/tutorials/beginner/transfer_learning_tutorial.html"),
        ],
      },
      {
        id: "m07-gradio",
        title: "Make a demo with Gradio and Hugging Face Spaces",
        learn: "Wrap a model in a web UI in a few lines and host it for free.",
        doneWhen: "You have a public Hugging Face Space URL where someone can upload an image and get a prediction.",
        minutes: 90,
        keywords: ["Gradio", "Hugging Face Spaces", "model demo"],
        search: [yt("deploy gradio app on hugging face spaces"), web("Gradio quickstart")],
        links: [
          link("Gradio quickstart", "https://www.gradio.app/guides/quickstart"),
          link("Hugging Face Spaces docs", "https://huggingface.co/docs/hub/spaces-overview"),
        ],
      },
    ],
    project: {
      id: "m07-proj",
      label: "Mini project · Custom image classifier",
      kind: "mini",
      title: "Collect ~100 images per class of something you care about (3–5 classes), fine-tune a pretrained model, and deploy it as a Gradio app on Hugging Face Spaces.",
      learn: "A live, shareable fine-tuned model you made.",
      doneWhen: "Your Space is public and you sent the link to one person.",
      minutes: 240,
      keywords: ["image dataset", "fine-tune ResNet", "Gradio"],
      search: [yt("fine tune image classifier on custom dataset pytorch")],
    },
  },
  {
    id: "m08",
    stage: "s3",
    week: "Week 9",
    title: "Object detection: the ideas, and running YOLO",
    goal: "Learn what object detection is and run a pretrained detector on your own images and video.",
    nodeTip: "A detector's output is plain JSON-like data: a list of {box, class, confidence}. Easy to wire into a Node backend later.",
    tasks: [
      {
        id: "m08-concepts",
        title: "Detection vocabulary",
        learn: "Bounding boxes, classification vs detection vs segmentation, IoU, confidence threshold, non-max suppression, mAP.",
        doneWhen: "You can explain IoU and why mAP is the standard score for detectors.",
        minutes: 75,
        keywords: ["object detection", "bounding box", "IoU", "non-max suppression", "mAP", "anchor boxes"],
        search: [yt("object detection explained IoU NMS mAP"), yt("how YOLO object detection works")],
        links: [link("Ultralytics: YOLO performance metrics", "https://docs.ultralytics.com/guides/yolo-performance-metrics/")],
      },
      {
        id: "m08-install",
        title: "Install Ultralytics and run YOLO on an image",
        learn: "pip install ultralytics, load a pretrained small model, predict, and look at the boxes it draws.",
        doneWhen: "You ran a pretrained YOLO on one of your own photos and opened the annotated result.",
        minutes: 60,
        keywords: ["ultralytics", "YOLO11", "yolo predict", "pretrained weights", "COCO dataset"],
        search: [yt("Ultralytics YOLO quickstart tutorial"), web("ultralytics yolo predict python")],
        links: [
          link("Ultralytics docs", "https://docs.ultralytics.com/"),
          link("Ultralytics quickstart", "https://docs.ultralytics.com/quickstart/"),
        ],
      },
      {
        id: "m08-video",
        title: "Run detection on video and read the results",
        learn: "Loop over frames, read boxes/classes/confidence from the results object, count objects, save the output video.",
        doneWhen: "A video with boxes drawn on it, plus a printed count of one class per frame.",
        minutes: 90,
        keywords: ["yolo video", "results.boxes", "OpenCV", "object counting", "tracking"],
        search: [yt("YOLO object detection on video Python OpenCV"), web("ultralytics results boxes xyxy conf cls")],
        links: [link("Ultralytics: Predict mode", "https://docs.ultralytics.com/modes/predict/")],
      },
    ],
    project: {
      id: "m08-proj",
      label: "Mini project · Detect things in your own video",
      kind: "mini",
      title: "Record or find a 30-second video and count a COCO class in it (cars, people, cups) with a pretrained YOLO. Save the annotated video.",
      learn: "You've used a detector for a real question before you train one.",
      doneWhen: "An output video exists with boxes, and you know how many objects were counted.",
      minutes: 120,
      keywords: ["object counting", "pretrained YOLO", "COCO"],
      search: [yt("YOLO object counting tutorial ultralytics")],
    },
  },
  {
    id: "m09",
    stage: "s3",
    week: "Weeks 10–11",
    title: "Fine-tune YOLO on your own objects",
    goal: "Collect and label a dataset, fine-tune a YOLO model on a free GPU, and know if it's good.",
    nodeTip: "Dataset prep is ETL. A Node script that renames, splits and validates files is a perfectly good tool here.",
    tasks: [
      {
        id: "m09-data",
        title: "Collect and label a detection dataset",
        learn: "Take or download 100–200 photos of your objects, draw boxes with a free labeling tool, export in YOLO format.",
        doneWhen: "You have a folder of images with a .txt label file for each one.",
        minutes: 180,
        keywords: ["image annotation", "Roboflow", "CVAT", "Label Studio", "YOLO format", "bounding box labels"],
        search: [yt("how to label images for YOLO object detection"), yt("Roboflow annotate dataset tutorial")],
        links: [
          link("Roboflow Universe (free datasets)", "https://universe.roboflow.com/"),
          link("Label Studio (free, open source)", "https://labelstud.io/"),
          link("CVAT (free, open source)", "https://www.cvat.ai/"),
        ],
      },
      {
        id: "m09-format",
        title: "Dataset folders and data.yaml",
        learn: "train/val split, the images/ and labels/ folders, the data.yaml file. Most 'training doesn't start' bugs live here.",
        doneWhen: "Ultralytics reads your dataset with no errors and starts epoch 1.",
        minutes: 60,
        keywords: ["data.yaml", "train val split", "images labels folders", "class names"],
        search: [web("ultralytics detect dataset format yolo data.yaml")],
        links: [link("Ultralytics: Detection datasets", "https://docs.ultralytics.com/datasets/detect/")],
      },
      {
        id: "m09-train",
        title: "Fine-tune on Colab and read the results",
        learn: "yolo train with a pretrained small model, epochs, image size, batch size. Then read results.png: loss curves, mAP50, the confusion matrix, the PR curve.",
        doneWhen: "You trained for 50+ epochs, have a best.pt, and can say your mAP50 and which class is weakest.",
        minutes: 180,
        keywords: ["yolo train", "epochs", "imgsz", "mAP50", "best.pt", "results.png", "data augmentation"],
        search: [yt("train YOLO on custom dataset Google Colab"), yt("YOLO training results mAP confusion matrix explained")],
        links: [link("Ultralytics: Train mode", "https://docs.ultralytics.com/modes/train/")],
      },
      {
        id: "m09-improve",
        title: "Improve a weak detector",
        learn: "More and more varied images, fix wrong labels, augmentation, a bigger model, longer training. Change one thing at a time.",
        doneWhen: "You changed one thing, retrained, and your mAP went up (or you know why it didn't).",
        minutes: 120,
        keywords: ["hard negatives", "label quality", "augmentation", "model size", "overfitting"],
        search: [web("ultralytics tips for best training results"), yt("how to improve YOLO model accuracy")],
        links: [link("Ultralytics: Tips for best training results", "https://docs.ultralytics.com/guides/model-training-tips/")],
      },
      {
        id: "m09-export",
        title: "Export to ONNX and call it from Node",
        learn: "yolo export format=onnx, then run the ONNX file from Node with onnxruntime-node. Your Node skills meet your model.",
        doneWhen: "A Node script loads best.onnx and prints detections for one image.",
        minutes: 150,
        keywords: ["ONNX", "yolo export", "onnxruntime-node", "inference"],
        search: [yt("YOLO ONNX Node.js onnxruntime"), web("ultralytics export onnx")],
        links: [
          link("Ultralytics: Export mode", "https://docs.ultralytics.com/modes/export/"),
          link("onnxruntime for Node.js", "https://onnxruntime.ai/docs/get-started/with-javascript/node.html"),
        ],
      },
    ],
    project: {
      id: "m09-proj",
      label: "Major project · Your own object detector",
      kind: "major",
      title: "Train a YOLO detector for something specific to you (a product on your desk, tools, plants, parking spots). Put it in a Gradio demo or a Node API and write a short README with your mAP.",
      learn: "Your first end-to-end object detection fine-tune.",
      doneWhen: "A demo URL or repo exists, with 2–3 example images and your metrics in the README.",
      minutes: 300,
      keywords: ["custom object detector", "Gradio", "README with metrics"],
      search: [yt("custom object detection project YOLO Gradio demo")],
    },
  },
  {
    id: "m10",
    stage: "s3",
    week: "Week 12",
    title: "More vision models with Hugging Face",
    goal: "Fine-tune open vision models from the Hub (ViT, DETR-style detectors) and speed up labeling with AI.",
    nodeTip: "The Hub is the npm registry for models: search by task, check the license, read the model card.",
    tasks: [
      {
        id: "m10-hf-vision",
        title: "Hugging Face for images",
        learn: "pipelines for image tasks, AutoImageProcessor, loading image datasets, the Trainer API.",
        doneWhen: "You ran an image-classification pipeline on your own photo and read its output.",
        minutes: 90,
        keywords: ["image classification pipeline", "AutoImageProcessor", "Trainer", "ViT", "datasets"],
        search: [yt("Hugging Face computer vision course"), web("Hugging Face image classification task guide")],
        links: [
          link("HF Computer Vision Course (free)", "https://huggingface.co/learn/computer-vision-course"),
          link("HF: Image classification guide", "https://huggingface.co/docs/transformers/tasks/image_classification"),
        ],
      },
      {
        id: "m10-vit",
        title: "Fine-tune a Vision Transformer (ViT)",
        learn: "Same idea as your ResNet fine-tune, with a transformer backbone and the Trainer API.",
        doneWhen: "A ViT fine-tuned on your classes from the classifier project, with its accuracy compared to the ResNet.",
        minutes: 150,
        keywords: ["Vision Transformer", "ViT fine-tune", "TrainingArguments", "evaluate accuracy"],
        search: [yt("fine tune Vision Transformer Hugging Face custom dataset")],
      },
      {
        id: "m10-detr",
        title: "Fine-tune a transformer detector (DETR family)",
        learn: "Detection with the HF object-detection guide. Compare to YOLO: simpler pipeline, usually slower to train.",
        doneWhen: "You ran the HF object-detection guide on a small dataset and compared its mAP with YOLO's.",
        minutes: 180,
        keywords: ["DETR", "RT-DETR", "object detection transformers", "COCO format", "Hugging Face Trainer"],
        search: [yt("fine tune DETR object detection custom dataset Hugging Face")],
        links: [link("HF: Object detection guide", "https://huggingface.co/docs/transformers/tasks/object_detection")],
      },
      {
        id: "m10-autolabel",
        title: "Label faster with AI (auto-labeling)",
        learn: "Use a zero-shot model (Grounding DINO, SAM, or the auto-label in your labeling tool) to propose boxes, then fix them by hand.",
        doneWhen: "You auto-labeled 50 images and corrected the boxes in under half the time of hand labeling.",
        minutes: 90,
        keywords: ["auto-labeling", "Grounding DINO", "Segment Anything", "zero-shot detection"],
        search: [yt("auto label dataset Grounding DINO SAM YOLO"), web("autodistill auto label images")],
      },
    ],
    project: {
      id: "m10-proj",
      label: "Mini project · Detector shootout",
      kind: "mini",
      title: "Train a second detector on the dataset from the YOLO project and write a 10-line comparison: mAP, training time, speed, how easy it was.",
      learn: "Learning to compare models is the real skill.",
      doneWhen: "A small table with both models' mAP, time and your verdict is in your notes.",
      minutes: 150,
      keywords: ["model comparison", "mAP", "inference speed"],
      search: [web("YOLO vs DETR comparison")],
    },
  },

  // ───────────────────────── Stage 4 ─────────────────────────
  {
    id: "m11",
    stage: "s4",
    week: "Weeks 13–14",
    title: "How LLMs work",
    goal: "Know what a language model is, how text becomes tokens, and what attention does, so fine-tuning isn't magic.",
    nodeTip: "A tokenizer is just a very fancy string-to-number-array function. Most LLM weirdness (bad arithmetic, odd spelling) starts there.",
    tasks: [
      {
        id: "m11-intro",
        title: "Big picture: what is an LLM",
        learn: "Pretraining, next-token prediction, parameters, context window, and what changes after fine-tuning. Start with Karpathy's one-hour overview.",
        doneWhen: "You can explain in 3 sentences how a model that only predicts the next token can answer questions.",
        minutes: 90,
        keywords: ["large language model", "next token prediction", "pretraining", "context window", "parameters"],
        search: [yt("Karpathy intro to large language models 1 hour talk"), yt("3Blue1Brown large language models explained briefly")],
      },
      {
        id: "m11-tokens",
        title: "Tokenization",
        learn: "Byte-pair encoding, why models see tokens and not letters, and what a chat template adds.",
        doneWhen: "You pasted a sentence into a tokenizer viewer and understand why some words split into several tokens.",
        minutes: 90,
        keywords: ["tokenizer", "BPE", "byte pair encoding", "vocabulary", "special tokens"],
        search: [yt("Karpathy let's build the GPT tokenizer"), web("tiktokenizer")],
        links: [link("Tiktokenizer (see how text is split)", "https://tiktokenizer.vercel.app/")],
      },
      {
        id: "m11-attn",
        title: "Attention, visually",
        learn: "Queries, keys and values, multi-head attention, positional information. Pictures first, formulas later.",
        doneWhen: "You can say what 'each token looks at the previous tokens and mixes their information' means.",
        minutes: 90,
        keywords: ["self-attention", "query key value", "multi-head attention", "transformer", "positional encoding"],
        search: [yt("3Blue1Brown attention in transformers visually explained"), web("Jay Alammar The Illustrated Transformer")],
        links: [link("The Illustrated Transformer", "https://jalammar.github.io/illustrated-transformer/")],
      },
      {
        id: "m11-gpt",
        title: "Let's build GPT (code along)",
        learn: "Karpathy's GPT-from-scratch video. About 2 hours: do it in 3–4 sittings. The most valuable video on this roadmap.",
        doneWhen: "Your notebook trains a tiny GPT and prints generated text.",
        minutes: 240,
        keywords: ["decoder-only transformer", "causal mask", "layer norm", "residual connection", "nanoGPT"],
        search: [yt("Karpathy let's build GPT from scratch in code spelled out")],
        links: [
          link("Karpathy: Zero to Hero", "https://karpathy.ai/zero-to-hero.html"),
          link("nanoGPT on GitHub", "https://github.com/karpathy/nanoGPT"),
        ],
      },
    ],
    project: {
      id: "m11-proj",
      label: "Mini project · Tiny GPT on your own text",
      kind: "mini",
      title: "Train a tiny GPT on text you pick (lyrics, a book, your own writing) on Colab, and sample from it.",
      learn: "You trained a transformer yourself.",
      doneWhen: "Your tiny GPT generated text in the style of your corpus, and you saved the notebook.",
      minutes: 150,
      keywords: ["nanoGPT", "character-level GPT", "text corpus", "temperature"],
      search: [web("nanoGPT shakespeare char train colab")],
    },
  },
  {
    id: "m12",
    stage: "s4",
    week: "Week 15",
    title: "Hugging Face and running open LLMs",
    goal: "Use the real tools: transformers, datasets, the Hub. Run open models on your own machine and call them from Node.",
    nodeTip: "Ollama exposes an HTTP API and an official npm package, so a local model is just another service you fetch().",
    tasks: [
      {
        id: "p3-hf",
        title: "Hugging Face LLM course, chapters 1–4",
        learn: "pipelines, AutoModel, AutoTokenizer, sharing models on the Hub.",
        doneWhen: "You ran a text-generation pipeline in Colab and pushed a tiny model or dataset to your Hub account.",
        minutes: 240,
        keywords: ["pipeline", "AutoModelForCausalLM", "AutoTokenizer", "Hugging Face Hub", "model card"],
        search: [web("Hugging Face LLM Course"), yt("Hugging Face transformers tutorial")],
        links: [link("Hugging Face LLM Course (free)", "https://huggingface.co/learn/llm-course")],
      },
      {
        id: "m12-ollama",
        title: "Run an open LLM locally with Ollama",
        learn: "Install Ollama, pull a small model (Llama 3.2, Qwen, Gemma), chat with it, and see what hardware it needs.",
        doneWhen: "A local model answers a prompt, and you know roughly how much RAM/VRAM it used.",
        minutes: 60,
        keywords: ["Ollama", "ollama run", "local LLM", "GGUF", "model size VRAM"],
        search: [yt("Ollama tutorial run LLM locally"), web("Ollama library models")],
        links: [link("Ollama", "https://ollama.com/")],
      },
      {
        id: "m12-node",
        title: "Call a local model from Node",
        learn: "Use the ollama npm package or plain fetch: chat, streaming, and a JSON-only response.",
        doneWhen: "A Node script streams a model's answer to the terminal.",
        minutes: 90,
        keywords: ["ollama-js", "streaming", "REST API", "structured output"],
        search: [yt("Ollama Node.js tutorial"), web("ollama-js npm")],
        links: [link("ollama-js", "https://github.com/ollama/ollama-js")],
      },
      {
        id: "m12-prompt",
        title: "Prompting, RAG, or fine-tuning?",
        learn: "When to just prompt, when to add retrieval (RAG), and when fine-tuning is actually worth it. Save yourself wasted training runs.",
        doneWhen: "You can name one task for each of the three approaches.",
        minutes: 45,
        keywords: ["prompt engineering", "RAG", "fine-tuning vs RAG", "few-shot"],
        search: [yt("fine-tuning vs RAG vs prompt engineering when to use"), web("Hugging Face LLM course supervised fine-tuning")],
      },
    ],
    project: {
      id: "m12-proj",
      label: "Mini project · Local model CLI in Node",
      kind: "mini",
      title: "Build a Node CLI that reads a text file and asks a local Ollama model to summarize it. Add streaming output.",
      learn: "Your web skills plus a model: the same shape as your final project.",
      doneWhen: "`node summarize.js notes.txt` streams a summary.",
      minutes: 120,
      keywords: ["Ollama", "Node CLI", "streaming"],
      search: [yt("build a CLI with Ollama and Node.js")],
    },
  },

  // ───────────────────────── Stage 5 ─────────────────────────
  {
    id: "m13",
    stage: "s5",
    week: "Week 16",
    title: "Fine-tuning basics and your dataset",
    goal: "Understand what fine-tuning changes, and build a clean dataset. The data is where fine-tunes win or lose.",
    nodeTip: "Data prep is ETL. Write the scripts that clean raw data into JSONL chat format in Node, since you're fastest there.",
    tasks: [
      {
        id: "m13-sft",
        title: "How LLM fine-tuning works",
        learn: "Pretraining vs supervised fine-tuning (SFT) vs preference tuning. Instruction and chat datasets, chat templates, JSONL.",
        doneWhen: "You can describe an SFT example and where the chat template fits.",
        minutes: 90,
        keywords: ["supervised fine-tuning", "instruction tuning", "chat template", "JSONL dataset", "SFT"],
        search: [yt("fine-tuning LLMs explained for beginners"), web("Maxime Labonne LLM course fine-tuning")],
        links: [
          link("Maxime Labonne: LLM course (free)", "https://github.com/mlabonne/llm-course"),
          link("HF: Chat templates", "https://huggingface.co/docs/transformers/chat_templating"),
        ],
      },
      {
        id: "m13-pick",
        title: "Pick your task and your base model",
        learn: "Choose one narrow task (classify, extract JSON, summarize, answer in your style). Pick a small open model that fits a free Colab GPU.",
        doneWhen: "One sentence: 'Given X, the model should output Y', and a base model chosen.",
        minutes: 45,
        keywords: ["base model vs instruct model", "Llama 3.2 1B 3B", "Qwen", "Gemma", "license"],
        search: [web("best small open source LLMs to fine-tune"), web("Hugging Face open LLM leaderboard small models")],
      },
      {
        id: "m13-data",
        title: "Build 500–1,500 training examples",
        learn: "Collect and clean examples, generate synthetic ones with a stronger model, remove duplicates, and keep a held-out test set you never train on.",
        doneWhen: "A train.jsonl and a test.jsonl exist, and you read 20 random examples to check quality.",
        minutes: 240,
        keywords: ["dataset curation", "synthetic data", "deduplication", "data leakage", "train test split"],
        search: [yt("how to create a dataset for LLM fine-tuning"), web("Hugging Face datasets push_to_hub")],
        links: [link("HF Datasets docs", "https://huggingface.co/docs/datasets")],
      },
    ],
    project: {
      id: "m13-proj",
      label: "Mini project · Publish your dataset",
      kind: "mini",
      title: "Push your cleaned dataset to the Hugging Face Hub (private is fine) with a short README of where the data came from.",
      learn: "Good data habits before the expensive part.",
      doneWhen: "load_dataset('your-name/your-dataset') works in a fresh notebook.",
      minutes: 60,
      keywords: ["push_to_hub", "dataset card"],
      search: [web("Hugging Face datasets upload push_to_hub")],
    },
  },
  {
    id: "m14",
    stage: "s5",
    week: "Weeks 17–18",
    title: "LoRA and QLoRA fine-tuning",
    goal: "The main event: fine-tune a small open LLM on your data on a free GPU.",
    nodeTip: "Start from a working Unsloth/TRL notebook, change only the dataset first, and run it once end to end before tuning anything.",
    tasks: [
      {
        id: "m14-lora",
        title: "LoRA and QLoRA, the idea",
        learn: "Why we train small adapter matrices instead of all the weights. Rank, alpha, target modules, and loading the base model in 4-bit.",
        doneWhen: "You can say why LoRA needs far less GPU memory than full fine-tuning.",
        minutes: 75,
        keywords: ["LoRA", "QLoRA", "PEFT", "rank and alpha", "bitsandbytes 4-bit", "adapter"],
        search: [yt("LoRA low rank adaptation explained"), yt("QLoRA explained")],
        links: [link("Hugging Face PEFT docs", "https://huggingface.co/docs/peft")],
      },
      {
        id: "m14-run",
        title: "Run a free Unsloth Colab notebook end to end",
        learn: "Take Unsloth's Llama / Qwen / Gemma notebook as-is and train on its sample dataset to prove the setup works.",
        doneWhen: "The notebook finished training and the model generated an answer after fine-tuning.",
        minutes: 90,
        keywords: ["Unsloth", "Colab T4", "SFTTrainer", "4-bit", "chat template"],
        search: [yt("Unsloth fine tune Llama Colab tutorial"), web("Unsloth notebooks")],
        links: [
          link("Unsloth docs", "https://docs.unsloth.ai/"),
          link("Unsloth notebooks", "https://docs.unsloth.ai/get-started/unsloth-notebooks"),
          link("Hugging Face TRL docs", "https://huggingface.co/docs/trl"),
        ],
      },
      {
        id: "m14-own",
        title: "Fine-tune on your dataset",
        learn: "Swap in your JSONL from the last module, train, and compare the model's answers before and after on 10 test prompts.",
        doneWhen: "You saved the LoRA adapter, and see at least one clear before/after improvement.",
        minutes: 180,
        keywords: ["SFT on custom data", "learning rate", "epochs", "save adapter", "push adapter to Hub"],
        search: [yt("fine tune LLM on custom dataset Unsloth"), web("Unsloth fine-tuning guide hyperparameters")],
        links: [link("Unsloth: Fine-tuning guide", "https://docs.unsloth.ai/get-started/fine-tuning-llms-guide")],
      },
      {
        id: "m14-debug",
        title: "Read the loss and fix common problems",
        learn: "Loss not dropping, loss near zero (memorizing), out of memory, repeated text, wrong chat template.",
        doneWhen: "You know what you'd change first for: OOM, overfitting, and gibberish output.",
        minutes: 60,
        keywords: ["out of memory", "gradient accumulation", "max_seq_length", "overfitting", "learning rate"],
        search: [yt("LLM fine-tuning common mistakes loss curve"), web("Unsloth fine-tuning troubleshooting")],
      },
    ],
    project: {
      id: "p4-proj",
      label: "Major project · Your fine-tuned LLM",
      kind: "major",
      title: "Fine-tune a small open LLM with QLoRA on your own dataset for the task you picked. Push the adapter to the Hub with a model card.",
      learn: "The headline project of your portfolio.",
      doneWhen: "The adapter and model card are on the Hub, with 3 before/after example outputs.",
      minutes: 300,
      keywords: ["QLoRA", "model card", "adapter"],
      search: [yt("fine tune LLM QLoRA project end to end")],
    },
  },
  {
    id: "m15",
    stage: "s5",
    week: "Weeks 19–20",
    title: "Evaluate, quantize and serve",
    goal: "Prove your fine-tune helped, shrink it, and run it behind a Node API.",
    nodeTip: "A GGUF model in Ollama is an HTTP service. From Node it's a fetch() call.",
    tasks: [
      {
        id: "p6-eval",
        title: "Evaluate your fine-tuned model",
        learn: "A held-out test set, before/after comparison on the same prompts, task metrics (accuracy, ROUGE, JSON validity), and LLM-as-a-judge.",
        doneWhen: "A table: base model vs fine-tuned on the same 30–50 test examples with one clear metric.",
        minutes: 150,
        keywords: ["held-out test set", "ROUGE", "LLM-as-a-judge", "human evaluation", "before after"],
        search: [yt("how to evaluate a fine-tuned LLM"), web("Hugging Face evaluate library")],
        links: [link("HF Evaluate", "https://huggingface.co/docs/evaluate")],
      },
      {
        id: "p5-quant",
        title: "Merge the adapter and export to GGUF",
        learn: "Quantization (Q4_K_M and friends), merging LoRA into the base model, exporting GGUF, the quality vs size trade-off.",
        doneWhen: "You have a .gguf file of your fine-tuned model that is a few GB or less.",
        minutes: 90,
        keywords: ["quantization", "GGUF", "Q4_K_M", "llama.cpp", "merge LoRA adapter"],
        search: [yt("LLM quantization explained GGUF"), web("Unsloth save to GGUF Ollama")],
        links: [link("llama.cpp", "https://github.com/ggml-org/llama.cpp")],
      },
      {
        id: "p5-serve",
        title: "Serve it with Ollama and call it from Node",
        learn: "Write a Modelfile, `ollama create`, then use the REST API from Node with streaming.",
        doneWhen: "Your fine-tuned model answers a prompt through a Node script.",
        minutes: 90,
        keywords: ["Ollama Modelfile", "ollama create", "import GGUF", "streaming"],
        search: [web("Ollama import GGUF Modelfile"), yt("Ollama custom model Modelfile tutorial")],
        links: [link("Ollama docs: Import a model", "https://docs.ollama.com/import"), link("Ollama docs: Modelfile", "https://docs.ollama.com/modelfile")],
      },
      {
        id: "m15-dpo",
        title: "Know what DPO is (optional depth)",
        learn: "Preference tuning with chosen/rejected pairs, and how DPO replaces full RLHF. Just know what it is; do it later if you need it.",
        doneWhen: "You can describe what a chosen/rejected pair is and when you'd use it.",
        minutes: 45,
        keywords: ["DPO", "RLHF", "preference dataset", "chosen rejected"],
        search: [yt("DPO direct preference optimization explained")],
        links: [link("TRL: DPO Trainer", "https://huggingface.co/docs/trl/dpo_trainer")],
      },
    ],
    project: {
      id: "p5-proj",
      label: "Final project · Ship it",
      kind: "major",
      title: "Put your fine-tuned, quantized model behind a small Node.js API (with a minimal web page) and use it for something real. Write the eval result in the README.",
      learn: "Data, training, evaluation and deployment, all yours.",
      doneWhen: "The API runs from a clean clone with the README steps, and shows your eval table.",
      minutes: 300,
      keywords: ["Ollama", "Node.js API", "README", "eval table"],
      search: [yt("build app with Ollama and Node.js Express")],
    },
  },
  {
    id: "m16",
    stage: "s5",
    week: "Weeks 21–22",
    title: "Vision-language models: LLMs that see",
    goal: "Fine-tune a model that takes an image plus a question and answers in text. This joins both of your goals.",
    nodeTip: "A VLM is an LLM with an image encoder in front. Same LoRA ideas, with images in the dataset as well as text.",
    tasks: [
      {
        id: "m16-intro",
        title: "What a vision-language model is",
        learn: "Image encoder + projector + LLM. What they can do: captioning, OCR, document-to-JSON, visual questions. Names to know: Qwen-VL, SmolVLM, PaliGemma, Llama 3.2 Vision.",
        doneWhen: "You can explain how an image becomes tokens an LLM can read.",
        minutes: 60,
        keywords: ["vision language model", "VLM", "Qwen-VL", "SmolVLM", "PaliGemma", "multimodal"],
        search: [yt("vision language models explained"), web("Hugging Face vision language models blog")],
        links: [link("HF: Vision Language Models explained", "https://huggingface.co/blog/vlms")],
      },
      {
        id: "m16-run",
        title: "Run a VLM on your own images",
        learn: "Load a small open VLM in Colab and ask it questions about 5 of your images. Note what it gets wrong.",
        doneWhen: "You have 5 image + question + answer examples, and a list of its mistakes in your note.",
        minutes: 90,
        keywords: ["transformers image-text-to-text", "Qwen2-VL", "SmolVLM", "processor", "chat template with images"],
        search: [yt("run Qwen VL vision language model Colab"), web("Hugging Face image-text-to-text pipeline")],
      },
      {
        id: "m16-ft",
        title: "Fine-tune a VLM with Unsloth",
        learn: "Use Unsloth's free vision notebook: an image+text dataset in, LoRA adapter out. Use a small dataset (200–500 examples).",
        doneWhen: "The fine-tuned VLM does your task better than the base VLM on 10 test images.",
        minutes: 240,
        keywords: ["Unsloth vision", "image text dataset", "LoRA vision", "VLM fine-tuning", "OCR"],
        search: [yt("fine tune vision language model Unsloth Colab"), web("Unsloth vision fine-tuning notebook")],
        links: [link("Unsloth: Vision fine-tuning guide", "https://docs.unsloth.ai/basics/vision-fine-tuning")],
      },
    ],
    project: {
      id: "m16-proj",
      label: "Major project · A vision-language specialist",
      kind: "major",
      title: "Fine-tune a small VLM for one specific job: receipt or invoice photo to JSON, handwritten notes to text, or product photo to description. Publish it on the Hub and make a Gradio demo.",
      learn: "Image and language fine-tuning in one project.",
      doneWhen: "A demo where you upload an image and get structured text, plus before/after numbers in the README.",
      minutes: 360,
      keywords: ["VLM fine-tune", "image to JSON", "Gradio", "Hub"],
      search: [yt("fine tune vision language model for document extraction")],
    },
  },

  // ───────────────────────── Stage 6 ─────────────────────────
  {
    id: "m17",
    stage: "s6",
    week: "Week 23",
    title: "Fine-tune an image generator (Stable Diffusion LoRA)",
    goal: "Teach an open image-generation model a style or a subject with ~15 images.",
    tasks: [
      {
        id: "m17-diff",
        title: "How diffusion models work",
        learn: "Noise in, image out: the idea of denoising step by step, text conditioning, and what a LoRA changes.",
        doneWhen: "You can explain diffusion as 'learn to remove a little noise, repeat'.",
        minutes: 75,
        keywords: ["diffusion model", "denoising", "latent diffusion", "text encoder", "scheduler"],
        search: [yt("how diffusion models work explained"), yt("Stable Diffusion explained for beginners")],
        links: [link("HF Diffusion Models Course (free)", "https://github.com/huggingface/diffusion-models-class")],
      },
      {
        id: "m17-run",
        title: "Generate images with diffusers",
        learn: "Load an open Stable Diffusion / SDXL pipeline in Colab and generate with your own prompts.",
        doneWhen: "You generated 4 images from prompts you wrote.",
        minutes: 60,
        keywords: ["diffusers", "StableDiffusionPipeline", "SDXL", "prompt", "guidance scale"],
        search: [yt("Hugging Face diffusers tutorial Stable Diffusion Colab")],
        links: [link("Diffusers docs", "https://huggingface.co/docs/diffusers")],
      },
      {
        id: "m17-lora",
        title: "Train a LoRA on ~15 images",
        learn: "DreamBooth-style LoRA training with the diffusers script (or a free notebook). Choose a style or an object, caption well.",
        doneWhen: "You can generate an image in your trained style or of your trained subject.",
        minutes: 180,
        keywords: ["DreamBooth LoRA", "Stable Diffusion LoRA", "training images captions", "trigger word"],
        search: [yt("train Stable Diffusion LoRA Colab diffusers DreamBooth"), web("diffusers LoRA training guide")],
        links: [link("Diffusers: LoRA training", "https://huggingface.co/docs/diffusers/training/lora")],
      },
    ],
    project: {
      id: "m17-proj",
      label: "Mini project · Your own style model",
      kind: "mini",
      title: "Train a LoRA for a style or subject you like, generate a gallery of 8 images, and publish the LoRA with examples.",
      learn: "Fine-tuning for images that you create, not just detect.",
      doneWhen: "The LoRA is on the Hub with 8 example images.",
      minutes: 180,
      keywords: ["style LoRA", "gallery", "model card"],
      search: [yt("train style LoRA stable diffusion")],
    },
  },
  {
    id: "m18",
    stage: "s6",
    week: "Weeks 24–26",
    title: "Become the AI developer you want to be",
    goal: "Turn what you built into proof, and decide what to go deeper on next.",
    tasks: [
      {
        id: "p6-writeups",
        title: "Write up each model you trained",
        learn: "One page each: the problem, the data, how you trained, the metrics, what you'd do next. GitHub README and Hub model cards.",
        doneWhen: "Your three best projects each have a README with a picture and a metric.",
        minutes: 180,
        keywords: ["ML case study", "model card", "README", "project write-up"],
        search: [web("Hugging Face model cards guide"), web("machine learning project README examples")],
        links: [link("HF: Model cards", "https://huggingface.co/docs/hub/model-cards")],
      },
      {
        id: "p6-oss",
        title: "Make one open-source contribution",
        learn: "Hugging Face, Ultralytics, Ollama, Unsloth, transformers.js. Docs fixes and small examples count.",
        doneWhen: "A pull request or issue with a reproduction is open on a real project.",
        minutes: 150,
        keywords: ["good first issue", "open source contribution", "pull request"],
        search: [web("huggingface good first issue"), web("ultralytics good first issue")],
      },
      {
        id: "p6-jobs",
        title: "Read 10 AI/ML job posts and pick your next skill",
        learn: "List the skills that keep showing up. Common next steps: RAG, agents/tool calling, evaluation, MLOps and deployment, GPU serving (vLLM).",
        doneWhen: "A ranked list of 3 skills to learn next is saved in your note.",
        minutes: 60,
        keywords: ["AI engineer", "ML engineer", "RAG", "vLLM", "MLOps"],
        search: [web("AI engineer job description skills"), web("ML engineer fine-tuning job requirements")],
      },
    ],
    project: {
      id: "p6-proj",
      label: "Capstone · AI developer portfolio",
      kind: "major",
      title: "One polished page or repo that shows every project: the problem, a demo or screenshot, your metrics, and the stack.",
      learn: "Everything above, in one link.",
      doneWhen: "You can send one link to a stranger and it explains who you are as an AI developer.",
      minutes: 240,
      keywords: ["developer portfolio", "AI projects"],
      search: [web("AI engineer portfolio examples")],
    },
  },
];

function build(m: ModuleIn, index: number): ModuleDoc {
  const tasks: Step[] = m.tasks.map((t) => ({ ...t, links: t.links ?? [] }));
  const project: Project = {
    ...m.project,
    kind: m.project.kind ?? "mini",
    links: m.project.links ?? [],
  };
  return {
    _id: m.id,
    order: index + 1,
    stage: m.stage,
    week: m.week,
    title: m.title,
    goal: m.goal,
    ...(m.nodeTip && { nodeTip: m.nodeTip }),
    tasks,
    project,
    itemIds: [...tasks.map((t) => t.id), project.id],
  };
}

export const MODULES: ModuleDoc[] = MODULES_IN.map(build);
